### ISSUE TITLE
decaffeinate produces a blank result when running on a file ending with .cjsx

### ISSUE THREAD

**Issue by chrisbull** [decaffeinate/decaffeinate#1007]
I'm currently in the middle of porting over my clients coffeescript and cjsx files to es6 and babel. Version 2.53.4 seemed to worked decent for .cjsx files... but now the new version of 2.54.x no longer is. 

Can you please support CJSX? 

Thanks!

**Comment by alangpierce** [comment]
Hi, thanks for the report!

decaffeinate doesn't work with the JSX syntax in CJSX (yet), but it sounds like you've been running decaffeinate on regular CoffeeScript with a file ending with `.cjsx`? I see you have a fork of https://github.com/bugsnag/depercolator . Looking at the 2.54.0 code change, looks like previously it would write the output to a file ending in `.cjsx.js` and now it's writing it to `.cjsx` (the same name as the input file), which presumably runs into filesystem issues. From my local testing (on mac), it seems to just generate a blank file. Is that the issue you're seeing?

**Comment by alangpierce** [comment]
Since it sounds like you're referring to the regression involving file extensions, I'll rename this bug to reflect that (fix should be up soon) and file another bug on actually supporting CJSX natively (hopefully that can work someday, but would definitely be a lot of work).

**Comment by alangpierce** [comment]
Oh, nevermind, looking at the previous code further, it just took off the file extension (everything from the last dot to the end) and replaced it with .js. I can fix it to do that again. I changed the code because we need to change `.coffee.md` to `.js` sometimes, but looks like other cases should stay the same.

**Comment by alangpierce** [comment]
@chrisbull I just released decaffeinate 2.54.2, which I think should have the regression fixed. Let me know if you run into problems with it.
