### ISSUE TITLE
`in` operator reverses execution order

### ISSUE THREAD

**Issue by alangpierce** [decaffeinate/decaffeinate#1038]
decaffeinate is producing the wrong JavaScript based on my CoffeeScript input:

```coffee
console.log('a') in [console.log('b')]
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=console.log('a')%20in%20%5Bconsole.log('b')%5D)

I get this output:

```js
[console.log('b')].includes(console.log('a'));
```

Here's what I expect it to be instead:

```js
var needle;
(needle = console.log('a'), [console.log('b')].includes(needle));
```

(Or some equivalent that evaluates the LHS before the RHS.)

**Comment by eventualbuddha** [comment]
CoffeeScript itself turns `a() in [b()]` into `a() === b()`. In the more general case of `a() in b()`, it does more or less what you outlined by using a temporary variable.

**Comment by alangpierce** [comment]
That's true, I got rid of the `===` special case in decaffeinate a while back ( #508 ) since it was causing other issues and didn't seem much different from `includes`. But I guess in the specific case of a one-element array it makes it easier to keep evaluation order.

The particular test failure for this bug is CoffeeScript's `in should preserve evaluation order`, which does `a() not in [b(),c()]`.
https://github.com/jashkenas/coffeescript/blob/master/test/operators.coffee#L185
