### ISSUE TITLE
for-in loops with indices allow modifying the loop counter when they shouldn't

### ISSUE THREAD

**Issue by alangpierce** [decaffeinate/decaffeinate#1044]
decaffeinate is producing the wrong JavaScript based on my CoffeeScript input:

```coffee
arr = [1, 2, 3]
for val, i in arr
  console.log i
  i = 10
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=arr%20%3D%20%5B1%2C%202%2C%203%5D%0Afor%20val%2C%20i%20in%20arr%0A%20%20console.log%20i%0A%20%20i%20%3D%2010)

I get this output:

```js
let arr = [1, 2, 3];
for (let i = 0; i < arr.length; i++) {
  let val = arr[i];
  console.log(i);
  i = 10;
}
```

Here's what I expect it to be instead (one idea):

```js
let arr = [1, 2, 3];
for (let j = 0; j < arr.length; j++) {
  let i = j;
  let val = arr[i];
  console.log(i);
  i = 10;
}
```

**Comment by eventualbuddha** [comment]
I think your output looks right, but I'd only do that if we can tell the `i` binding is mutated.

**Comment by alangpierce** [comment]
👍 agreed.

I think maybe some of the other loop outputs like [this](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=for%20a%20in%20%5Bb..c%5D%0A%20%20d) could also benefit at least a little from some static analysis like that.

**Comment by alangpierce** [comment]
Hey @eventualbuddha, are you still working on this? (You assigned it to yourself.) It's one of the remaining ones in the CoffeeScript test suite, which I'm trying to get through.

**Comment by eventualbuddha** [comment]
Nope, thought I unassigned it. Go ahead!
