### ISSUE TITLE
Support non-terminal rest params

### ISSUE THREAD

**Issue by eventualbuddha** [decaffeinate/decaffeinate#107]
CoffeeScript allows this:

``` coffee
(keys..., callback) ->
```

But you can't simply turn that into this:

``` js
(function(...keys, callback) {});
```

Because rest params have to be at the end. We'll have to do some juggling to support this.

**Comment by alangpierce** [comment]
[Example repl link](http://decaffeinate-project.org/repl/#?evaluate=false&stage=full&code=(args...%2C%20funcArg)%20-%3E%20new%20Map%20%7B%7D)
