### ISSUE TITLE
Wrong output for string concat with double backslash

### ISSUE THREAD

**Issue by rf-** [decaffeinate/decaffeinate#1081]
decaffeinate is producing the wrong JavaScript based on my CoffeeScript input:

```coffee
(char) -> "\\" + char
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=(char)%20-%3E%20%22%5C%5C%22%20%2B%20char)

I get this output:

```js
char => `\${char}`;
```

Here's what I expect it to be instead:

```js
char => `\\${char}`;
```

Thanks!

**Comment by alangpierce** [comment]
Thanks for reporting! There's already some code that handles escaping when combining strings ( https://github.com/esnext/esnext/blob/master/src/plugins/strings.template.js#L94 ), so I imagine this is just an edge case in that code and should be relatively easy to fix.

**Comment by rf-** [comment]
Thanks for the fix! :+1:
