### ISSUE TITLE
Multiple empty callbacks

### ISSUE THREAD

**Issue by XVincentX** [decaffeinate/decaffeinate#1099]
decaffeinate is crashing on my CoffeeScript input:

```coffee
fn1((done) ->
  fn2('string', (object) ->
    ;
  , (err, data) ->
    p = data
    done(err)
  )
)
```

[decaffeinate-repl](http://decaffeinate-project.org/repl/#?evaluate=false&stage=full&code=fn1((done)%20-%3E%0A%20%20fn2('string'%2C%20(object)%20-%3E%0A%20%20%20%20%3B%0A%20%20%2C%20(err%2C%20data)%20-%3E%0A%20%20%20%20p%20%3D%20data%0A%20%20%20%20done(err)%0A%20%20)%0A))

I get this error:

```
MainStage failed to parse: unexpected ,
  1 | fn1((done) ->
  2 |   fn2('string', (object) ->
> 3 |     ,
    |     ^
  4 |    (err, data) ->
  5 |     p = data
```

[CoffeeScript output](http://coffeescript.org/#try:fn1((done)%20-%3E%0A%20%20fn2('string'%2C%20(object)%20-%3E%0A%20%20%20%20%3B%0A%20%20%2C%20(err%2C%20data)%20-%3E%0A%20%20%20%20p%20%3D%20data%0A%20%20%20%20done(err)%0A%20%20)%0A))

**Comment by alangpierce** [comment]
It looks to me like this isn't valid CoffeeScript. Here's the CoffeeScript output:

http://coffeescript.org/#try:testFunction((fn)%20-%3E%0A%20%20%23%20nothing%0A%2C%20(cb)%20-%3E%20true)
```
Error on line 3: unexpected ,
```

Is there a CoffeeScript version/configuration where this works for you?

**Comment by XVincentX** [comment]
@alangpierce I'm sorry, I've just updated the issue links.

**Comment by alangpierce** [comment]
Ok, thanks! Agreed that it's a bug. This is one of the more annoying types of bugs to fix, but should be doable.

**Comment by XVincentX** [comment]
Well actually as workaround you can simply return something; a simple `true` will do the job here!
