### ISSUE TITLE
Includes method is not supported by IE

### ISSUE THREAD

**Issue by billy-addepar** [decaffeinate/decaffeinate#1101]
Includes method is not supported by IE and some older version of Edge:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes?v=example

Link to the conversion:

http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=if%20a%20not%20in%20%5B'b'%2C%20'c'%5D%0A%20%20console.log('Not%20in')

Can decaffeinate use `indexOf` for checking if an object is present in an array?

**Comment by billy-addepar** [comment]
This issue seems to be mentioned in [here](https://github.com/decaffeinate/decaffeinate/issues/403). Closing this issue

**Comment by alangpierce** [comment]
@billy-addepar this has been requested before, so seems reasonable to add as an option. I just filed #1102 for that. Alternatively, you could set up [babel-polyfill](https://babeljs.io/docs/usage/polyfill/) or similar, depending on your situation.
