### ISSUE TITLE
Option to use lodash' `_.get()` instead of `__guard` functions

### ISSUE THREAD

**Issue by kvz** [decaffeinate/decaffeinate#1103]
Hi! Can't thank you enough for decaffeinate, I've ported some considerable projects over already and it's been working beautifully and saving me sooo much time towards a homogenous ES6 environment.

I do have _one_ feature request.

When porting larger codebases i find `__guard__` functions scattered in many files. I understand why this was chosen as people may not want to use lodash or similar, and it's better to stick to the purpose of just language porting vs including/requiring your users install arbitrary modules just to get the ES5/6 working :+1:

That being said, since JavaScript is so limited in it's capabilities of handling undefined nested properties (e.g. it gets wordy/boilerplatey quickly), I think the practical reality is that a many devs do use helper functions for this, but would likely rather reach for something re-usable such as   [lodash' `get`](https://lodash.com/docs/4.17.4#get) than have a function in every file.

To me personally, I have a better time grocking `let x = _.get(obj, ['one', 'two', 'three', 'levels', 'deep'])`, than the `__guard__` alternative of `let x = __guard__(__guard__(__guard__(__guard__(typeof obj !== 'undefined' && obj !== null ? obj.one : undefined, x4 => x4.two), x3 => x3.three), x2 => x2.levels), x1 => x1.deep)`. Granted, a bit of a contrived sample. Typically you'd likely only be looking at one or two levels deep, but still.

One idea for a possible middle ground, would be to have an opt-in for a `__get__` (and/or `__has__`) helper function that behaves just like [lodash' `get`](https://lodash.com/docs/4.17.4#get) (and/or [`has`](https://lodash.com/docs/4.17.4#has)), and appends those helper functions to each individual source file just like `__guard__` is appended right now. 

When taking that approach, no dependency requirements are introduced, the general approach is the same, but once the developer inspects the decaffeinated source files, they'd have more dense helper function calls to look at, as well as an easy time to replace the duplicated helper functions with e.g.  [lodash' `get`](https://lodash.com/docs/4.17.4#get), by substituting:

```js
function __get__ (obj, path) {
  ...
}
```

with:

```js
const __get__ = require('lodash/get')
```

Would this be a reasonable approach at all?

PS One gotcha with using a string path notation like `let x = _.get(obj, 'one.two.three.levels.deep')` that I got burned by, is it does (obviously) not work for properties that have periods `.` in them already. Hence the array `[]` syntax would be best to tread on the safe side 😄

**Comment by alangpierce** [comment]
Hi, thanks for the kind words! I can probably take a closer look later, but some initial thoughts:

Agreed that `__guard__` is ugly, and probably the part of decaffeinate that has the most room for improvement. I'm certainly open to thinks like `_.get`, either an inline replacement or just expecting people to add lodash as a dependency.

I think generally this idea or others can be implemented behind options as a way of experimenting with different approaches. I also wouldn't be opposed to making something like this the default behavior, especially if it produces significantly better results than `__guard__`. One thing to keep in mind, though, is that the implementation of this stuff is pretty complex and fragile. Ideally there would be a way of having isolated separate implementations, but it's hard to say for sure how reasonable that is.

Also note there's some additional discussion here: https://github.com/decaffeinate/decaffeinate/issues/336 .

One thing to note is that I think `_.get` isn't flexible enough to handle all cases. For example, this works and I think can't be done with `get`:

```coffee
a?.b()?.c?().d += e
```

It won't do the `+=` if any intermediate checks fail. We could still use `get` in some cases and `__guard__` in the remaining cases, but I think function/method calls have been fairly common in the code I've seen.

The `idx` Facebook library has a similar goal and I think is more flexible: https://facebook.github.io/react-native/blog/2017/03/13/idx-the-existential-function.html . It's sort of clever in that it uses try/catch, but has a babel plugin to rewrite it to more performant code. But needing a babel plugin makes it less universal and harder to set up, of course.

It also looks like there's now a stage 1 proposal for this feature in JavaScript: https://github.com/tc39/proposal-optional-chaining and a babel plugin that's still in progress but looks like it will land soon: https://github.com/babel/babel/pull/5813 . Obviously stage 1 is a bit dangerous and probably breaks things like editor support, but seems worth having an option for decaffeinate to generate code using that syntax. I suspect there are differences in behavior, and would have to check that.

**Comment by kvz** [comment]
Thanks about the insightful comment here! I hadn't thought of the `a?.b()?.c?().d += e` case, that seems indeed. Speaking for just my personal use, keeping `__guard__` for those cases and allowing for a lodash-esque approach where easily possible, would already save me a lot of work. But I could understand how a more complete approach would be more desirable.

**Comment by alangpierce** [comment]
Merging with #336, since the two issues have effectively the same goal (make soak operations better).
