### ISSUE TITLE
Crash on expression-style loop with empty body

### ISSUE THREAD

**Issue by alangpierce** [decaffeinate/decaffeinate#1135]
decaffeinate is crashing on my CoffeeScript input:

```coffee
x = for a in b then
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=x%20%3D%20for%20a%20in%20b%20then)

I get this error:

```
Cannot read property 'prefersToPatchAsExpression' of null
```

Yay, a bug caught by TypeScript.

**Comment by eventualbuddha** [comment]
> Yay, a bug caught by TypeScript.

🏆
