### ISSUE TITLE
Gitter

### ISSUE THREAD

**Issue by hneiva** [decaffeinate/decaffeinate#1160]
Not sure if the maintainers of the project are used to [gitter](www.gitter.im) but would be cool if we had an account open. It's usually used for direct support, and I feel works better than github issues for asking questions. Just an idea, what do you guys think?

**Comment by alangpierce** [comment]
Yep, sounds like a great idea. I've actually been meaning to set up a gitter room for a while. I'll get one set up.

Looks like github permissions are making it so gitter isn't recognizing this as one of my projects (which I think is necessary to make a room tied to this project), so I sent an access request to @eventualbuddha (the org owner).

**Comment by alangpierce** [comment]
@hneiva ok, I just set up a gitter room at https://gitter.im/decaffeinate/Lobby, and the README should get updated soon to mention it.
