### ISSUE TITLE
For loop with `when` condition code is incorrectly converted.

### ISSUE THREAD

**Issue by t9md** [decaffeinate/decaffeinate#1170]
First of all, thanks very much for this great project.
I've recently used decaffeinate in several my personal project and worked super well.

One of example I'm working on now.
https://github.com/t9md/atom-vim-mode-plus/pull/823

# For loop with `when` condition code should not be converted to `filter` and `map` JS.

I sometimes use `when` clause to set variable used in `for` loop body.
Decaffeinate failed to correctly convert code to JS in that situation.

decaffeinate is producing the wrong JavaScript based on my CoffeeScript input:

```coffee
getVisibleEditors = ->
  (editor for pane in atom.workspace.getPanes() when editor = pane.getActiveEditor())
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&stage=EsnextStage&code=getVisibleEditors%20%3D%20-%3E%0A%20%20(editor%20for%20pane%20in%20atom.workspace.getPanes()%20when%20editor%20%3D%20pane.getActiveEditor())%0A)

```js
const getVisibleEditors = function() {
  let editor;
  return (Array.from(atom.workspace.getPanes()).filter((pane) => (editor = pane.getActiveEditor())).map((pane) => editor));
};
```

- Original CoffeeScript version do : Return Array of `editor`(result of pane.getActiveEditor() of each pane).
- Decaffeinated version do : Return Array of `editor`.(that editor refer identical editor)

Here's how CoffeeScript compiles to JS.

```js
var getVisibleEditors;

getVisibleEditors = function() {
  var editor, i, len, pane, ref, results;
  ref = atom.workspace.getPanes();
  results = [];
  for (i = 0, len = ref.length; i < len; i++) {
    pane = ref[i];
    if (editor = pane.getActiveEditor()) {
      results.push(editor);
    }
  }
  return results;
};
```

**Comment by alangpierce** [comment]
Interesting, that makes sense. There are already some cases where the `map` and `filter` approach can't be used, so I think it should be reasonable to add this as another case.
