### ISSUE TITLE
Incorrect conversion for variable used in switch body 

### ISSUE THREAD

**Issue by t9md** [decaffeinate/decaffeinate#1171]
decaffeinate is producing the wrong JavaScript based on my CoffeeScript input:

```coffee
letInSwitchBodyIssue = (input)->
  result = 1
  switch input
    when 'case-1'
      a = 1
      result += a

    when 'case-2'
      a = 2
      result += a


  "#{input}: #{result}"

console.log letInSwitchBodyIssue("case-1") # case-1: 2
console.log letInSwitchBodyIssue("case-2") # case-2: 3
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&stage=EsnextStage&code=letInSwitchBodyIssue%20%3D%20(input)-%3E%0A%20%20result%20%3D%201%0A%20%20switch%20input%0A%20%20%20%20when%20'case-1'%0A%20%20%20%20%20%20a%20%3D%201%0A%20%20%20%20%20%20result%20%2B%3D%20a%0A%0A%20%20%20%20when%20'case-2'%0A%20%20%20%20%20%20a%20%3D%202%0A%20%20%20%20%20%20result%20%2B%3D%20a%0A%0A%0A%20%20%22%23%7Binput%7D%3A%20%23%7Bresult%7D%22%0A%0Aconsole.log%20letInSwitchBodyIssue(%22case-1%22)%20%23%20case-1%3A%202%0Aconsole.log%20letInSwitchBodyIssue(%22case-2%22)%20%23%20case-2%3A%203%0A)

```js
const letInSwitchBodyIssue = function(input){
  let result = 1;
  switch (input) {
    case 'case-1':
      let a = 1;
      result += a;
      break;

    case 'case-2':
      a = 2;
      result += a;
      break;
  }


  return `${input}: ${result}`;
};

console.log(letInSwitchBodyIssue("case-1")); // case-1: 2
console.log(letInSwitchBodyIssue("case-2")); // case-2: 3
```

This code crash at `case-2` input with `ReferenceError: a is not defined`.
See how `a` is declared.

Should this declaration be lift up to out of switch?

**Comment by alangpierce** [comment]
Thanks for reporting! Yeah, looks like decaffeinate shouldn't be inferring declarations within switch bodies, or at least it needs to be a lot more careful about it.
