### ISSUE TITLE
Crashing on Input Related to List Comprehension

### ISSUE THREAD

**Issue by aryeh-looker** [decaffeinate/decaffeinate#1172]
Decaffeinate is crashing on my CoffeeScript input (link to REPL [Link to REPL](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=%40sendConditionsForDisplay%3A%20(options%20%3D%20%7B%7D)%20-%3E%0A%20%20(%7Bvalue%3A%20sendCondition%2C%20label%3A%20SendConditionLabels%5BsendCondition%5D%7D%20for%20sendCondition%20in%20%40sendConditions(options)))):

```coffee
@sendConditionsForDisplay: (options = {}) ->
  ({value: sendCondition, label: SendConditionLabels[sendCondition]} for sendCondition in @sendConditions(options))
```

I get this error:

```
cannot edit index 3552 because it is not editable (i.e. outside [3559, 3672))
```

**Comment by alangpierce** [comment]
Looks like this is a reduced test case:
```coffee
(a = 1) ->
  (a)
```
