### ISSUE TITLE
`###` comments in parentheses-scoped functions crash decaffeinate

### ISSUE THREAD

**Issue by samertm** [decaffeinate/decaffeinate#1181]
Decaffeinate is crashing on my CoffeeScript input:

```coffee
() -> (
  ###yo###
  a
)
```

[repl](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=%23%20These%20fail%3A%0A()%20-%3E%20(%0A%20%20%23%23%23yo%23%23%23%0A%20%20a%0A)%0A%0A()%20-%3E%20(%0A%0A%20%20a%0A%20%20%23%23%23yo%23%23%23%0A%20%20b%0A)%0A%0A%23%20These%20work%3A%0A()%20-%3E%20(%0A%20%20%23%20yo%0A%20%20a%0A%20%20b%0A)%0A%0A()%20-%3E%0A%20%20%23%23%23yo%23%23%23%0A%20%20a%0A%0A()%20-%3E%0A%20%20%23%23%23yo%23%23%23%0A%20%20a%0A%20%20b%0A)

I get this error:

```
Expected comment notes to be filtered out by mapBlock rather than processed directly.

node type 'Comment' is not supported: { comment: 'yo',
  locationData: { first_line: 2, first_column: 2, last_line: 2, last_column: 9 } }
```

**Comment by alangpierce** [comment]
Thanks for reporting! As you've noticed, it looks like the parens around the function body are what's causing trouble here, one workaround in the meantime is to just remove them.
