### ISSUE TITLE
incorrect output: multiple object arguments are combined

### ISSUE THREAD

**Issue by samertm** [decaffeinate/decaffeinate#1182]
decaffeinate is producing the wrong JavaScript based on my CoffeeScript input:

```coffee

somefunc 
  hey: 1,
  yo: 2,
,
  sup: 2,
  friend: 3,

# equivalent to: 
# somefunc({
#   hey: 1,
#   yo: 2,
# }, {
#   sup: 2,
#   friend: 3,
# })
```

[repl](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=%23%20doesn't%20work%0Asomefunc%20%0A%20%20hey%3A%201%2C%0A%20%20yo%3A%202%2C%0A%2C%0A%20%20sup%3A%202%2C%0A%20%20friend%3A%203%2C%0A%0A%23%20works%0Asomefunc(%7B%0A%20%20hey%3A%201%2C%0A%20%20yo%3A%202%2C%0A%7D%2C%20%7B%0A%20%20sup%3A%202%2C%0A%20%20friend%3A%203%2C%0A%7D)%0A)

I get this output:

```js
somefunc({ 
  hey: 1,
  yo: 2,

  sup: 2,
  friend: 3
}
);
```

Here's what I expect it to be instead:

```js
somefunc({
  hey: 1,
  yo: 2,
}, {
  sup: 2,
  friend: 3,
});
```

For context, this is a [link to the coffee repl for that code](http://coffeescript.org/#try:%0Asomefunc%20%0A%20%20hey%3A%201%2C%0A%20%20yo%3A%202%2C%0A%2C%0A%20%20sup%3A%202%2C%0A%20%20friend%3A%203%2C%0A%0A%0Asomefunc(%7B%0A%20%20hey%3A%201%2C%0A%20%20yo%3A%202%2C%0A%7D%2C%20%7B%0A%20%20sup%3A%202%2C%0A%20%20friend%3A%203%2C%0A%7D)%0A).

**Comment by alangpierce** [comment]
Yikes, thanks for reporting! There are some cases where decaffeinate removes redundant commas (since commas are often optional) to work around some parsing issues in the CoffeeScript parser, but I guess that's changing the behavior here.
