### ISSUE TITLE
Closure from `do` is not generated correctly when function returns function

### ISSUE THREAD

**Issue by cguenthner** [decaffeinate/decaffeinate#1189]
decaffeinate is producing the wrong JavaScript based on my CoffeeScript input:

```coffee
for i in [0...5]
  setTimeout((do (i) => => console.log(i)), 0);
```

[Link to REPL](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=for%20i%20in%20%5B0...5%5D%0A%20%20setTimeout((do%20(i)%20%3D%3E%20%3D%3E%20console.log(i))%2C%200)%3B)

I get this output:

```js
for (let i = 0; i < 5; i++) {
  setTimeout((i => () => console.log(i)(i)), 0);
}
```

Here's what I expect it to be instead:

```js
for (let i = 0; i < 5; i++) {
  setTimeout((i => () => console.log(i))(i), 0);
}
```

**Comment by alangpierce** [comment]
Thanks for reporting! This will be fixed with #1190.
