### ISSUE TITLE
Support prototype `::` syntax

### ISSUE THREAD

**Issue by wilzbach** [decaffeinate/decaffeinate#120]
In CoffeScript one can write `::`, which is basically just a convenient version of `.prototype`. 
Would be nice to recognize this too ;-)

**Comment by eventualbuddha** [comment]
This [already works](http://decaffeinate.github.io/decaffeinate/repl/#?evaluate=false&code=a%3A%3Ab). Is there a context where you're seeing it fail?

**Comment by greenify** [comment]
Sorry, but maybe that's a different issue then. Try

```
_.extend FooBar::
```

**Comment by eventualbuddha** [comment]
This is fixed by 1e060f7a3b8cc668577734fb54d9e04371113a48, but is not part of a release yet.

**Comment by eventualbuddha** [comment]
This works in v2.7.4, and probably earlier ([repl](http://decaffeinate.github.io/decaffeinate/repl/#?evaluate=false&code=_.extend%20FooBar%3A%3A)).
