### ISSUE TITLE
Variable incorrectly hoisted for => functions.

### ISSUE THREAD

**Issue by samertm** [decaffeinate/decaffeinate#1201]
decaffeinate is producing the wrong JavaScript based on my CoffeeScript input:

```coffee
# a is incorrectly hoisted out of the => functions
() =>
  a = 1
  return

() =>
  a = 2
  return

# b is not hoisted out of -> functions
() ->
  b = 1
  return

() ->
  b = 2
  return
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=%23%20a%20is%20incorrectly%20hoisted%20out%20of%20the%20%3D%3E%20functions%0A()%20%3D%3E%0A%20%20a%20%3D%201%0A%20%20return%0A%0A()%20%3D%3E%0A%20%20a%20%3D%202%0A%20%20return%0A%0A%23%20b%20is%20not%20hoisted%20out%20of%20-%3E%20functions%0A()%20-%3E%0A%20%20b%20%3D%201%0A%20%20return%0A%0A()%20-%3E%0A%20%20b%20%3D%202%0A%20%20return)

I get this output:

```js
// a is incorrectly hoisted out of the => functions
let a;
() => {
  a = 1;
};

() => {
  a = 2;
};

// b is not hoisted out of -> functions
(function() {
  const b = 1;
});

(function() {
  const b = 2;
});
```

Here's what I expect it to be instead:

```js
// a is incorrectly hoisted out of the => functions
(() => {
  var a;
  a = 1;
});

(() => {
  var a;
  a = 2;
});

// b is not hoisted out of -> functions
(function() {
  var b;
  b = 1;
});

(function() {
  var b;
  b = 2;
});
```

[(coffeescript repl)](http://coffeescript.org/#try:%23%20a%20is%20incorrectly%20hoisted%20out%20of%20the%20%3D%3E%20functions%0A()%20%3D%3E%0A%20%20a%20%3D%201%0A%20%20return%0A%0A()%20%3D%3E%0A%20%20a%20%3D%202%0A%20%20return%0A%0A%23%20b%20is%20not%20hoisted%20out%20of%20-%3E%20functions%0A()%20-%3E%0A%20%20b%20%3D%201%0A%20%20return%0A%0A()%20-%3E%0A%20%20b%20%3D%202%0A%20%20return)

**Comment by alangpierce** [comment]
Thanks for reporting! Probably just a missing case in the add-variable-declarations step, hopefully should be an easy fix.

**Comment by dgoldstein0** [comment]
thanks for the quick fix!
