### ISSUE TITLE
Assignment within blockless arrow function is incorrectly hoisted

### ISSUE THREAD

**Issue by alangpierce** [decaffeinate/decaffeinate#1202]
decaffeinate is producing the wrong JavaScript based on my CoffeeScript input:

```coffee
f = => a = 1
a = 2
f()
console.log a
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=f%20%3D%20%3D%3E%20a%20%3D%201%0Aa%20%3D%202%0Af()%0Aconsole.log%20a)

I get this output:

```js
let a;
const f = () => a = 1;
a = 2;
f();
console.log(a);
```

It prints 1.

Here's what I expect it to be instead:

```js
const f = () => {
  let a;
  return a = 1;
}
const a = 2;
f();
console.log(a);
```

It should print 2.

Some additional discussion here: https://github.com/eventualbuddha/add-variable-declarations/pull/79#pullrequestreview-74259022

**Comment by eventualbuddha** [comment]
In your example, `f` actually needs to return `1`. So this is probably more appropriate:

```js
const f = () => {
  let a;
  return a = 1;
};
```

**Comment by alangpierce** [comment]
👍 right, missed that, will edit. I'm glad I'm not converting CoffeeScript by hand anymore. 😄
