### ISSUE TITLE
decaffeinate-project.org/repl is broken

### ISSUE THREAD

**Issue by matixmatix** [decaffeinate/decaffeinate#1215]
Hey,

I wanted to use the REPL and I noticed the website is broken. Nothing can be pasted in the window. 

It seems there are JavaScript errors:

![image](https://user-images.githubusercontent.com/273660/34354675-44af00f8-ea30-11e7-84bf-02da05ea9046.png)

**Comment by alangpierce** [comment]
Thanks for reporting, I'm taking a look now. There haven't been any changes to the website recently, so I think it's probably a problem with the hosting/CDN. There was a similar issue a while back: https://github.com/decaffeinate/decaffeinate/issues/863, so I'll see if I can fix it in a similar way.

**Comment by alangpierce** [comment]
I did a re-publish with new code (just a version bump) and things seem to be working now.
