### ISSUE TITLE
BUG! Could not fix range for LogicalNotOp because it has no raw value

### ISSUE THREAD

**Issue by kvz** [decaffeinate/decaffeinate#122]
Not that this code is pretty or anything:

```coffee
if argv._?[0]? && argv._?[0] not of Frey.commands
  yargs.showHelp()
  console.error ""
  console.error "--> Command '#{argv._?[0]}' is not recognized"
  process.exit 1
```

But just to let you know, it throws a `BUG` exception.

Here's the link: http://decaffeinate.github.io/decaffeinate/repl/#?evaluate=true&code=%0Aif%20argv._%3F%5B0%5D%3F%20%26%26%20argv._%3F%5B0%5D%20not%20of%20Frey.commands%0A%20%20yargs.showHelp()%0A%20%20console.error%20%22%22%0A%20%20console.error%20%22--%3E%20Command%20'%23%7Bargv._%3F%5B0%5D%7D'%20is%20not%20recognized%22%0A%20%20process.exit%201

**Comment by eventualbuddha** [comment]
Thanks, this will likely be fixed soon.

**Comment by eventualbuddha** [comment]
Though `a?[0]` isn't yet supported, the part of this that failed before is working now ([repl](http://decaffeinate.github.io/decaffeinate/repl/#?evaluate=false&code=if%20argv._%5B0%5D%20not%20of%20Frey.commands%0A%20%20yargs.showHelp()%0A%20%20console.error%20%22%22%0A%20%20console.error%20%22--%3E%20Command%20'%23%7Bargv._%5B0%5D%7D'%20is%20not%20recognized%22%0A%20%20process.exit%201)).
