### ISSUE TITLE
Repl is giving a 404

### ISSUE THREAD

**Issue by alangpierce** [decaffeinate/decaffeinate#1221]
<img width="653" alt="screen shot 2018-02-11 at 8 12 26 am" src="https://user-images.githubusercontent.com/211605/36075397-507cfe38-0f03-11e8-9532-07d630671806.png">

@eventualbuddha any ideas? I know you've been looking at changing hosting. I think it stopped working sometime last night.

**Comment by eventualbuddha** [comment]
Yeah, I broke it. Should be fixed now. I was testing out a GAE+GCS solution and only just now got it working. I'll update decaffeinate/decaffeinate-project.org#156 with that version.
