### ISSUE TITLE
Crash on multiline if with `?` token applied to a conditional

### ISSUE THREAD

**Issue by JRigotti** [decaffeinate/decaffeinate#1230]
decaffeinate is crashing on my CoffeeScript input:

```coffee
test  = if \
    cond? \
    then 'true' else 'no'
```

[repl](https://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=test%20%20%3D%20if%20%5C%0A%20%20cond%3F%20%5C%0A%20%20then%20'true'%20else%20'no')

I get this error:

```
AddVariableDeclarationsStage failed to parse: Unexpected token, expected ; (1:52)
```

Changing slightly the code to:

```coffee
test  = if cond? \
    then 'true' else 'no'
```

It works as expected:

```js
const test  = (typeof cond !== 'undefined' && cond !== null) 
    ? 'true' : 'no';
```

The error is basically produced by:
```coffee
if \ # slash to scape to another line
    cond? # add a `?` to the conditional
```

**Comment by alangpierce** [comment]
I just put up a PR to fix: #1231, and a new decaffeinate version will be auto-published once that gets merged.
