### ISSUE TITLE
Repl is broken again

### ISSUE THREAD

**Issue by alangpierce** [decaffeinate/decaffeinate#1240]
It fails with "Uncaught SyntaxError: Unexpected identifier".

This is a fun one. I've done some investigation and I think I mostly understand what's going on, although there may be a few ways to fix.

As of decaffeinate 4.0.0, we now ship CS2, which is the first time we're shipping ES2015 syntax as part of decaffeinate. In particular, there's this code in compiled CS2:
```js
    if (options.inlineMap) {
      encoded = base64encode(JSON.stringify(v3SourceMap));
      sourceMapDataURI = `//# sourceMappingURL=data:application/json;base64,${encoded}`;
      sourceURL = `//# sourceURL=${(ref1 = options.filename) != null ? ref1 : 'coffeescript'}`;
      js = `${js}\n${sourceMapDataURI}\n${sourceURL}`;
    }
```

Browserify seems to get confused by that "sourceMappingURL", and emits this:
```js
    if (options.inlineMap) {
      encoded = base64encode(JSON.stringify(v3SourceMap));
      sourceMapDataURI = `
      sourceURL = `//# sourceURL=${(ref1 = options.filename) != null ? ref1 : 'coffeescript'}`;
      js = `${js}\n${sourceMapDataURI}\n${sourceURL}`;
    }
```
Funny enough, this is actually valid JS, so locally the repl works fine. browserify removed the backtick at the end of the `sourceMapDataURI` line, so that string extends to just after `sourceURL`, and the comment (previously in a string) becomes a JS comment that comments out the last backtick, so it all, strangely, balances out. That means that I can run the repl locally and it works just fine (since this code is never executed).

**But** it still fails in production. Here's what's being served in production:
```js
if(options.inlineMap){encoded=base64encode(JSON.stringify(v3SourceMap));sourceMapDataURI=`
      sourceURL = `js=`${js}\n${sourceMapDataURI}\n${sourceURL}`;}
```
The backtick immediately followed by `js` is a syntax error. In the original code, ASI put a semicolon there, which was necessary. From looking at the headers, it looks like auto-minify is enabled in the Cloudflare config, which is why it's being served differently from the gh-pages file.

So it looks like there are two things going wrong here:
* Browserify is improperly recognizing the sourceMappingURL string as an actual source map directive. CS1 has nearly the same code, but browserify handles it just fine because it's using a double-quoted string. So my impression is browserify has some string-handling code that isn't respecting the new template string syntax.
* Cloudflare minify isn't properly respecting ASI. [Apparently they built their own for performance reasons](https://blog.cloudflare.com/an-all-new-and-improved-autominify/), and I know that ASI is a pain to get right, so it doesn't surprise me that they wouldn't handle this correctly. Possibly this is also caused by the backtick syntax. https://github.com/github/fetch/issues/420 has another mention of this bug.

It looks like the bug is still in latest Browserify, so the quick fix is to disable Cloudflare minification. @eventualbuddha could you do that? I'll look into filing (and maybe fixing) the browserify bug.

**Comment by eventualbuddha** [comment]
Okay, I disabled minification of JavaScript on Cloudflare. Definitely seems like a good thing to report to them, though they’re probably aware.
