### ISSUE TITLE
Incorrect output: doesn't add return statement, but wraps in parentheses instead

### ISSUE THREAD

**Issue by madskonradsen** [decaffeinate/decaffeinate#1254]
decaffeinate is producing the wrong JavaScript based on my CoffeeScript input:

```coffee
define [], () ->
  init: (args) ->

    home.initialize args.home
    component.initialize args
```

[REPL](https://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=define%20%5B%5D%2C%20()%20-%3E%0A%20%20init%3A%20(args)%20-%3E%0A%0A%20%20%20%20home.initialize%20args.home%0A%20%20%20%20component.initialize%20args%0A%0Adefine%20%5B%5D%2C%20()%20-%3E%0A%20%20show%20%3D%20(element%2C%20groups)%20-%3E%0A%0A%20%20%23%20Exports%0A%20%20show%20%3A%20show%0A)

I get this output:

```js
define([], () =>
  ({
    init(args) {

      home.initialize(args.home);
      return component.initialize(args);
    }
  })
);
```

Here's what I expect it to be instead:

```js
define([], () =>
  return {
    init: (args) => {

      home.initialize(args.home);
      return component.initialize(args);
    }
  }
);
```

--------------

I've tried with another case which works just fine:
```coffee
define [], () ->
  show = (element, groups) ->

  # Exports
  show : show
```
which correctly compiles into:
```js
define([], function() {
  const show = function(element, groups) {};

  // Exports
  return {show};
});
```

**Comment by madskonradsen** [comment]
Hmm... Wait... That ain't a bug, right? It just doesn't look that pretty :)

**Comment by alangpierce** [comment]
Interesting example. Note that if you run the output through Prettier afterwards, you get this:
```js
define([], () => ({
  init(args) {
    home.initialize(args.home);
    return component.initialize(args);
  }
}));
```
which I think looks fine. Maybe the formatting and the "arrow function returning and object needs parens" syntax detail looked strange? I know for a while I preferred `() => { return {}; }` over `() => ({})`, but I prefer the second form these days.

decaffeinate makes a decision on when to use an expression-style arrow function and when to use a block-style arrow function, and generally prefers expression-style when possible. It could maybe be tweaked in this case, although IMO the expression-style arrow is fine here. Closing for now, but feel free to reopen if you feel strongly or have a more concrete rule that you think decaffeinate should implement.

**Comment by madskonradsen** [comment]
Yeah, I think you're right. Coming from CoffeeScript, the `() => ({})` syntax just looked strange. :)
