### ISSUE TITLE
New patcher for UnaryExistsOp

### ISSUE THREAD

**Issue by sandfox** [decaffeinate/decaffeinate#126]
First of, thanks so much for writing all this, it's super useful!

I'm using the patchers branch with the decaf-parser and alot of the code I'm currently converting has lots of
```
if data.promocode?
  stuff()

if data.blah?
  something_else()
```

to convert this it looks like a patcher needs to be written for  `UnaryExistsOp` and I'm happy to write it

I've had a look through the existing patchers but something isn't quite clicking.. are there any tips or pointers you could give, or at least suggest a good patcher to start from.

Thanks!

**Comment by eventualbuddha** [comment]
@sandfox I'm working on making it easier to contribute to and writing a quick contribution guide. Stay tuned.

**Comment by eventualbuddha** [comment]
@sandfox does [this](https://github.com/decaffeinate/decaffeinate/blob/master/CONTRIBUTING.md) help? What other questions do you think it should answer?

**Comment by jeffchan** [comment]
Oops, I didn't see this. Started working on this: #127

**Comment by sandfox** [comment]
@eventualbuddha Awesome, I think it'll definately help!, let me try running through it whilst writing a patcher and I'll let you know.
@jeffchan don't worry, I think there are quite a few other patchers I'll need to write and I haven't started writing anything "useful" yet for this, and I'll probably find it useful to see how you build yours!
