### ISSUE TITLE
Existential operator causes error when combined with parenthesis and properties

### ISSUE THREAD

**Issue by ToadKing** [decaffeinate/decaffeinate#129]
The following line parses to an error:

```coffee
(doThing a)?.event
```

The following two variants seem to work.

```coffee
((doThing a)?).event
(doThing a).event # not the same behavior as the example
```

Tested on v1.44.13 via the online REPL: https://decaffeinate.github.io/decaffeinate/repl/

**Comment by eventualbuddha** [comment]
This probably won't be fixed until the next version is released, which will be when #65 lands.

**Comment by madskonradsen** [comment]
Cannot reproduce. The only issue is of course the soak which throws the warning and is covered by #216 and #176 - i think it safely can be closed

**Comment by madskonradsen** [comment]
And now the soak issue is even gone :)
