### ISSUE TITLE
Not binding an anonymous function in Coffeescript executes with `this` bound to `window` ... but arrow functions do not provide a non-null `this`

### ISSUE THREAD

**Issue by hilts-vaughan** [decaffeinate/decaffeinate#1306]
```
 _.defer -> @someWindowProp?
```

I get this output:

```js
_.defer => { ... }
```

Technically, this is not preserving behaviour since `this` is now `null` and this causes an exception to be thrown. In the Coffeescript runtime (i.e: using just `function` then you get a case where you would end up just being run in the `window` context.  In most cases in our code base, it's actually an error! (someone thought they were bound but were not and did a null check for other reasons) but I guess technically this goes against "out of the box correctness"

Not sure how to fix --  I have a few ideas but not 100% there.

**Comment by alangpierce** [comment]
Hey @hilts-vaughan, thanks for the report, although I can't seem to repro (or maybe I'm misunderstanding a detail). I'm seeing it convert to `_.defer(function() { return (this.someWindowProp != null); });`.
[Repl link](https://decaffeinate-project.org/repl/#?useCS2=false&useJSModules=false&loose=false&evaluate=true&stage=full&code=_.defer%20-%3E%20%40someWindowProp%3F)
It should recognize the `this` usage and keep it as a non-arrow function, and that seems to be working in my example.

Could you provide a repl link that shows the issue?

**Comment by hilts-vaughan** [comment]
oops, I may have simplied too much. I'll try and create a REPL for you -- sorry, I can't link to proprietary code and may have "trimmed" out the source of the problem.

Lemme do that for you.

**Comment by hilts-vaughan** [comment]
https://decaffeinate-project.org/repl/#?useCS2=false&useJSModules=false&loose=false&evaluate=true&stage=full&code=class%20A%0A%20%20somethingBound%3A%20%3D%3E%0A%20%20%20%20_.defer%20-%3E%20%40someWindowProp%3F.reflow()%0A%0Aa%20%3D%20new%20A()%3B%0Aa.somethingBound()%3B%20%23%20will%20throw

Open up your console -- and you will see:

```
https://decaffeinate-project.org/repl/#?useCS2=false&useJSModules=false&loose=false&evaluate=true&stage=full&code=class%20A%0A%20%20somethingBound%3A%20%3D%3E%0A%20%20%20%20_.defer%20-%3E%20%40someWindowProp%3F.reflow()%0A%0Aa%20%3D%20new%20A()%3B%0Aa.somethingBound()%3B%20%23%20will%20throw
```

If you run something like that, such as:

```
class A
  somethingBound: =>
    setTimeout ->
      @someWindowProp?.x
      console.log('something should run')
    , 0

a = new A();
a.somethingBound(); # will throw
```

.. inside of the Coffeescript compiler and then evalute it, you will notice it will not throw. If you go out of your way to log `this`, you will notice it's `window`, where as in the output code from decaf, the `this` is NOT `window`, or rather `undefined`:

https://decaffeinate-project.org/repl/#?useCS2=false&useJSModules=false&loose=false&evaluate=true&stage=full&code=class%20A%0A%20%20somethingBound%3A%20%3D%3E%0A%20%20%20%20_.defer%20-%3E%20%0A%20%20%20%20%20%20console.log(this)%0A%20%20%20%20%20%20%40someWindowProp%3F.x%0A%0Aa%20%3D%20new%20A()%3B%0Aa.somethingBound()%3B%20%23%20will%20throw!

**Comment by eventualbuddha** [comment]
I think this is as done as it’s going to be.
