### ISSUE TITLE
Manipulating an argument and calling `super` does not always retain the manipulation to the base class

### ISSUE THREAD

**Issue by hilts-vaughan** [decaffeinate/decaffeinate#1308]
```coffee
class BaseModel
  constructor: (options = {}) ->
    debugger
    @_options = options

class Model extends BaseModel
  constructor: (arg) ->
    # Transform the argument if given the base form
    arg = { id: arg }
    
    # Send up all the arguments
    super

  getId: ->
    return @_options.id

a = new Model('MODEL-A');
alert(a.getId())

```

This is some sample code, you can run it on your REPL [here](https://decaffeinate-project.org/repl/#?useCS2=false&useJSModules=false&loose=false&evaluate=true&stage=full&code=class%20BaseModel%0A%20%20constructor%3A%20(options%20%3D%20%7B%7D)%20-%3E%0A%20%20%20%20%40_options%20%3D%20options%0A%0Aclass%20Model%20extends%20BaseModel%0A%20%20constructor%3A%20(arg)%20-%3E%0A%20%20%20%20%23%20Transform%20the%20argument%20if%20given%20the%20base%20form%0A%20%20%20%20arg%20%3D%20%7B%20id%3A%20arg%20%7D%0A%20%20%20%20%0A%20%20%20%20%23%20Send%20up%20all%20the%20arguments!%0A%20%20%20%20super%0A%0A%20%20getId%3A%20-%3E%0A%20%20%20%20return%20%40_options.id%0A%0Aa%20%3D%20new%20Model('MODEL-A')%3B%0Aalert(a.getId())%0A)

This returns `undefined` as you might expect since you were reassigning the reference of the argument and would not expect it to change the `arguments` being forwarded. 

However, if you compile it using the JS Compiler you get this:

```js
var BaseModel, Model, a,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

BaseModel = (function() {
  function BaseModel(options) {
    if (options == null) {
      options = {};
    }
    debugger;
    this._options = options;
  }

  return BaseModel;

})();

Model = (function(superClass) {
  extend(Model, superClass);

  function Model(arg) {
    arg = {
      id: arg
    };
    Model.__super__.constructor.apply(this, arguments);
  }

  Model.prototype.getId = function() {
    return this._options.id;
  };

  return Model;

})(BaseModel);

a = new Model('MODEL-A');

alert(a.getId());

// ---
// generated by coffee-script 1.9.2
``` 

... which will return "MODEL-A" which is not what I would expect to be honest, but is defined behavior that some code I have relies on...

**Comment by hilts-vaughan** [comment]
This is mostly likely happening because of some well defined behaviour that manipulating the argument that comes in is manipulating `arguments` as well somehow, I guess...

**Comment by alangpierce** [comment]
Looks like this is pretty much the same as #1306: using classes implicitly enables strict mode, and this is a change in behavior with strict mode. Without strict mode, assigning to an argument variable changes the `arguments` object. Strict mode makes it an array of the arg values that were passed in, independent of what the bound variables are assigned to now.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#Making_eval_and_arguments_simpler

**Comment by eventualbuddha** [comment]
Closing as it doesn't look like there's much to do here.
