### ISSUE TITLE
"Bind" technically works different between Coffeescript's and the `.bind` available, prototype property is erased

### ISSUE THREAD

**Issue by hilts-vaughan** [decaffeinate/decaffeinate#1309]
Namely, one of them gets bound anonymously with a `prototype` property where as `Function#bind` and `_.bind` will erase this property. You can use the following example:

https://decaffeinate-project.org/repl/#?useCS2=false&useJSModules=false&loose=false&evaluate=true&stage=full&code=class%20Tree%0A%20%20shake%3A%20%3D%3E%0A%20%20%20%20%40something%0A%20%20%0A%20%20getShakePrototype%3A%20-%3E%0A%20%20%20%20return%20this.shake.prototype%0A%20%20%20%20%0Atree%20%3D%20new%20Tree()%3B%0Aalert(tree.getShakePrototype())%0A

If you run this in the REPL, you get the right result. Backbone does this specifically (wrongly to access the prototype if you ask me, but there's neither here nor there...) 

Not sure if it's worth fixing or not.

**Comment by alangpierce** [comment]
Bizarre that Backbone relies on this. Is the prototype of the anonymous function meaningful, or maybe it just expects that it exists? I'm leaning toward not fixing this (since I don't want to make every `.bind` uglier), but definitely is a bummer if it breaks backbone code.

Also note that CS2 has the same issue that decaffeinate does.

**Comment by hilts-vaughan** [comment]
Yeah, it only has the problem if you override and bind `model` on a Collection. I've worked around this by detecting these all in a JSCodeShift and utilizing an uglier `bind` for them.

It's a bit weird they request the prototype from a function as well but it can be worked around.

**Comment by hilts-vaughan** [comment]
You can see this is the line where it would be a problem: https://github.com/jashkenas/backbone/blob/master/backbone.js#L1102

I'll leave it up to you if you want to address some of these nastiness that come from converting Backbone projects. Otherwise, I will perhaps publish some workarounds we used with the permission of my employer. 

I found a couple others (you noticed some of them, since I posted them) while doing our conversion.

I am happy to announce though, that by far, our project was a clean conversion!

**Comment by eventualbuddha** [comment]
Glad to hear things went well for you, @hilts-vaughan. Closing this as there isn't anything further to do.
