### ISSUE TITLE
Namespaced class not working

### ISSUE THREAD

**Issue by moimael** [decaffeinate/decaffeinate#1319]
decaffeinate is producing the wrong JavaScript based on my CoffeeScript input:

```coffee
class IZ.Controllers.Page extends IZ.Controller
```

I get this output:

```js
const Cls = (IZ.Controllers.Page = class Page extends IZ.Controller {
```

Not sure how the javascript should look like but I get this error:

```
ReferenceError: invalid assignment left-hand side
```

**Comment by alangpierce** [comment]
Hi @moimael, thanks for the report. Could you give a more complete code example showing the error, ideally as a repl link?

If I just run decaffeinate on your code snippet, it gives this output:

```js
IZ.Controllers.Page = class Page extends IZ.Controller {};
```
[Repl link](https://decaffeinate-project.org/repl/#?useCS2=false&useJSModules=true&loose=false&evaluate=false&stage=full&code=class%20IZ.Controllers.Page%20extends%20IZ.Controller%0A)

so I think you'll need a more complete example. Ideally there's a way to trim your code down to a small self-contained test case demonstrating the issue.

From the error, it looks to me like maybe `IZ.Controllers` isn't defined. Keep in mind that `class IZ.Controllers.Page extends IZ.Controller` is a special CoffeeScript syntax that assigns the new class to `IZ.Controllers.Page`, so `IZ.Controllers` needs to already exist. That syntax doesn't exist in JavaScript; classes always are expressions or are assigned to a new normal variable, not an object property.

Also, would be good to double-check that this case works in the CoffeeScript compiler and doesn't work in decaffeinate.

**Comment by moimael** [comment]
Hi,

Here you go:

[REPL](https://decaffeinate-project.org/repl/#?useCS2=false&useJSModules=true&loose=false&evaluate=true&stage=full&code=%23%20Page%20global%20things%20here%2C%20events%20and%20actions%20that%20should%20be%20present%20on%20every%20page%0A%0Aclass%20IZ.Controllers.Page%20extends%20IZ.Controller%0A%20%20el%3A%20%22body%22%0A%0A%20%20initialize%3A%20%3D%3E%0A%20%20%20%20IZ.currentUserDropdown%20%3D%20new%20IZ.Views.CurrentUserDropdown()%0A%20%20%20%20IZ.user%20%3D%20new%20IZ.User%20currentUserData%20if%20window.currentUserData%0A%20%20%20%20IZ.env%20%3D%20%40setupEnv()%0A%0A%20%20%20%20%24.ajaxSetup%0A%20%20%20%20%20%20error%3A%20%40handleUnauthorizedRequest%2C%0A%20%20%20%20%20%20data%3A%20_from%3A%20'ajax'%20%23%20So%20chrome%20does%20not%20cache%20the%20response%20if%20this%20URL%20is%20used%20for%20standard%20HTML%20requests%20too%0A%0A%20%20setupEnv%3A%20%3D%3E%0A%20%20%20%20development%3A%20window.environment%20%3D%3D%20%22development%22%0A%20%20%20%20test%3A%20window.environment%20%3D%3D%20%22test%22%0A%20%20%20%20production%3A%20window.environment%20%3D%3D%20%22production%22%0A%0A%20%20activateOnUnload%3A%20(callback)%20%3D%3E%0A%20%20%20%20window.onbeforeunload%20%3D%20%3D%3E%0A%20%20%20%20%20%20return%20callback()%0A%0A%20%20deactivateOnUnload%3A%20%3D%3E%0A%20%20%20%20window.onbeforeunload%20%3D%20null%0A%0A%20%20activateOnUnloadIfInProgress%3A%20%3D%3E%0A%20%20%20%20%40activateOnUnload%20(%3D%3E%20window.genericTranslation.pendingAjaxResponse%20if%20IZ.ajaxRunning)%0A%0A%20%20%23%20Override%20backbones%20ajax%20handling%20to%20handle%20some%20things%20custom%0A%20%20fixBackbone%3A%20%3D%3E%0A%20%20%20%20Backbone.ajax%20%3D%20(requestData)%20%3D%3E%0A%20%20%20%20%20%20%23%20Handle%20401%20redirects%0A%20%20%20%20%20%20errorCallback%20%3D%20requestData.error%0A%20%20%20%20%20%20requestData.error%20%3D%20(request)%20%3D%3E%0A%20%20%20%20%20%20%20%20%40handleUnauthorizedRequest(request)%0A%20%20%20%20%20%20%20%20errorCallback%3F(request)%0A%0A%20%20%20%20%20%20%23%20Keep%20track%20of%20running%20backbone%20requests%0A%20%20%20%20%20%20beforeSendCallback%20%3D%20requestData.beforeSend%0A%20%20%20%20%20%20requestData.beforeSend%20%3D%20%3D%3E%0A%20%20%20%20%20%20%20%20IZ.ajaxRunning%20%3D%20true%0A%20%20%20%20%20%20%20%20beforeSendCallback%3F.apply%20%24%2C%20arguments%0A%0A%20%20%20%20%20%20completeCallback%20%3D%20requestData.complete%0A%20%20%20%20%20%20requestData.complete%20%3D%20%3D%3E%0A%20%20%20%20%20%20%20%20IZ.ajaxRunning%20%3D%20false%0A%20%20%20%20%20%20%20%20completeCallback%3F.apply%20%24%2C%20arguments%0A%0A%20%20%20%20%20%20%24.ajax.apply%20%24%2C%20arguments%0A%0A%20%20%20%20%23%20Optionally%20namespace%20params%20for%20requests%0A%20%20%20%20oldSync%20%3D%20Backbone.sync%0A%20%20%20%20Backbone.sync%20%3D%20(method%2C%20model%2C%20options)%20-%3E%0A%20%20%20%20%20%20if%20!%20options.data%20%26%26%20model.namespace%0A%20%20%20%20%20%20%20%20data%20%3D%20%7B%7D%0A%20%20%20%20%20%20%20%20data%5Bmodel.namespace%5D%20%3D%20options.attrs%20%7C%7C%20model.toJSON(options)%0A%20%20%20%20%20%20%20%20options.data%20%3D%20JSON.stringify%20data%0A%20%20%20%20%20%20%20%20options.contentType%20%3D%20'application%2Fjson'%0A%20%20%20%20%20%20return%20oldSync.apply%20this%2C%20arguments%0A%0A%20%20%23%20Session%20has%20expired.%20Need%20to%20log%20in%20again..%0A%20%20handleUnauthorizedRequest%3A%20(request)%20%3D%3E%0A%20%20%20%20window.location%20%3D%20%24(%22body%22).data%20%22login-path%22%20if%20request.status%20%3D%3D%20401%0A)

The thing is it is used in a rails project so the imports are handled via the rails asset system. `IZ.Controllers` is defined but in another file. It does work with coffeescript compiler, this is actual (old) production code.

**Comment by moimael** [comment]
@alangpierce Anything else I can do to help solve this issue ?

**Comment by eventualbuddha** [comment]
@moimael I believe this may actually be correct. Your example code in the REPL does not have the same error you initially mentioned (`ReferenceError: invalid assignment left-hand side`), but is instead `IZ is not defined`. That makes perfect sense as nothing defines `IZ` in your example.

However, if there really is a problem with decaffeinate that leads to the error you mentioned (`ReferenceError: invalid assignment left-hand side`), we don't currently have enough information to debug it. Can you produce a REPL link that throws with that error?
