### ISSUE TITLE
Add suggestion comment(s) next to the relevant code

### ISSUE THREAD

**Issue by gitgrimbo** [decaffeinate/decaffeinate#1328]
I have a feature request.

Similar to #1120, can there be the ability to have a suggestion(s) appear next to the line(s) of code that the suggestion applies to?

This would help with further manual changes to be made to the code.

E.g., as well as the leading comment:

```js
/*
 * decaffeinate suggestions:
 * DS101: Remove unnecessary use of Array.from
```

there is also a suggestion comment next to the appropriate line(s) in the code:

```js
  // DS101: Remove unnecessary use of Array.from
  if (Array.from(result.support).includes("x")) {
    out += "ᵖ";
  }
```

Maybe the example given above is a bit obvious (i.e. I could just search the code for use of `Array.from` - but for other suggestions, it is less obvious to which part(s) of the code the suggestion(s) applies).

**Comment by eventualbuddha** [comment]
Thanks for the suggestion. Decaffeinate is pretty much “complete” and will likely not get updates beyond updating dependencies or security fixes. That said, if you wanted to submit a PR for this I’d review it.

**Comment by alangpierce** [comment]
To elaborate a little more, I think ideally the suggestions would be inline, but it makes the implementation a lot trickier. decaffeinate works using carefully-chosen find-and-replace operations to change the CoffeeScript into JavaScript, and there have been lots of bugs like emitting `)}` when it should emit `})`. Inline comments means we'd need to find a place for each one that is both reasonable-looking and correct. In your example, it would need to figure out that the comment shouldn't be directly before the `Array.from`, but instead before the `if` statement.
