### ISSUE TITLE
REPL does not work in Firefox

### ISSUE THREAD

**Issue by blikblum** [decaffeinate/decaffeinate#1352]
REPL is not working in Firefox 64.

To reproduce just go to https://decaffeinate-project.org/repl/

In the console an error occurs:

```
SyntaxError: redeclaration of formal parameter Buffer decaffeinate.js:200:6 note: Previously declared at line 178, column 11decaffeinate.js:178:11
ReferenceError: decaffeinate is not defined
```

Using Firefox 64 on Windows 10

**Comment by alangpierce** [comment]
Yikes, thanks, looks like it's broken in Safari as well. I'll take a look.

**Comment by blikblum** [comment]
Works. Thanks
