### ISSUE TITLE
Add example: How to convert all files in recursive subfolders

### ISSUE THREAD

**Issue by obiwarn** [decaffeinate/decaffeinate#136]
How do I batch run this for my project?

**Comment by obiwarn** [comment]
find ./ -name "*.coffee" -exec decaffeinate {} \;

**Comment by eventualbuddha** [comment]
Added in d29fbe51148262f4d9e8c70d7580ef0b0c2ab3ad, you can point decaffeinate at a folder and it'll find all the `.coffee` files in it and process them. Will be out with the next release.

**Comment by jeffchan** [comment]
I've been using the glob pattern
`decaffeinate ./js/**/*.coffee`

**Comment by eventualbuddha** [comment]
You can now do `decaffeinate path/to/folder` as of v2.0.0.
