### ISSUE TITLE
multiline string as import/export source fails

### ISSUE THREAD

**Issue by eventualbuddha** [decaffeinate/decaffeinate#1368]
decaffeinate is crashing on my CoffeeScript input:

```coffee
import a from """./Search.sass
"""
```

[(repl)](https://decaffeinate-project.org/repl/#?useCS2=true&useJSModules=true&loose=true&evaluate=true&stage=full&code=import%20a%20from%20""".%2FSearch.sass%0A""")

I get this error:

```
AddVariableDeclarationsStage failed to parse: Unexpected token (1:14)
> 1 | import a from `./Search.sass\
    |               ^
  2 | `;
```

I think the normalize stage is turning the multiline string into a template literal, but imports require regular strings and not template literals as the source. This is almost certainly a rare edge case.

**Comment by alangpierce** [comment]
Heh, yeah, newlines in filenames seem like a bad idea 😛. It's actually the main stage that converts to JS template string, so I think a fix shouldn't be so bad. Just change `StringPatcher.shouldBecomeTemplateLiteral` to check the parent to see if this node is the path of an import statement. The CS parser already gives an error if an imported path contains an interpolation, so you can assume that in that case there are no interpolations.
