### ISSUE TITLE
Implicit return ignored

### ISSUE THREAD

**Issue by pskaarup** [decaffeinate/decaffeinate#1371]
```bash
decaffeinate --version
decaffeinate v5.1.10
```
decaffeinate is producing the wrong JavaScript based on my CoffeeScript input:

```coffee
define [
  # Paths to files go here
], (a, b) ->
  
  b: b
  y: a.s

```

[(repl)](https://decaffeinate-project.org/repl/#?useCS2=false&useJSModules=false&loose=false&evaluate=true&stage=full&code=define%20%5B%0A%20%20%23%20Paths%20to%20files%20go%20here%0A%5D%2C%20(a%2C%20b)%20-%3E%0A%20%20%0A%20%20b%3A%20b%0A%20%20y%3A%20a.s%0A)

I get this output:

```js
/*
 * decaffeinate suggestions:
 * DS102: Remove unnecessary code created because of implicit returns
 * Full docs: https://github.com/decaffeinate/decaffeinate/blob/master/docs/suggestions.md
 */
define([
  // Paths to files go here
], (a, b) =>
  
  ({
    b,
    y: a.s
  })
);

```

Here's what I expect it to be instead:

```js
/*
 * decaffeinate suggestions:
 * DS102: Remove unnecessary code created because of implicit returns
 * Full docs: https://github.com/decaffeinate/decaffeinate/blob/master/docs/suggestions.md
 */
define([
  // Paths to files go here
], function(a, b) {
  
  return {
    b,
    y: a.s
  };
});

```

I get expected output from the first example if i choose `MainStage` [(repl)](https://decaffeinate-project.org/repl/#?useCS2=false&useJSModules=false&loose=false&evaluate=true&stage=MainStage&code=define%20%5B%0A%20%20%23%20Paths%20to%20files%20go%20here%0A%5D%2C%20(a%2C%20b)%20-%3E%0A%20%20%0A%20%20b%3A%20b%0A%20%20y%3A%20a.s%0A) or `SemicolonsState` [(repl)](https://decaffeinate-project.org/repl/#?useCS2=false&useJSModules=false&loose=false&evaluate=true&stage=SemicolonsStage&code=define%20%5B%0A%20%20%23%20Paths%20to%20files%20go%20here%0A%5D%2C%20(a%2C%20b)%20-%3E%0A%20%20%0A%20%20b%3A%20b%0A%20%20y%3A%20a.s%0A)

Interesting observation:

If a `noop;` or any statement is added before the implicit return i get the expected result

[(repl)](https://decaffeinate-project.org/repl/#?useCS2=false&useJSModules=false&loose=false&evaluate=true&stage=full&code=define%20%5B%0A%20%20%23%20Paths%20to%20files%20go%20here%0A%5D%2C%20(a%2C%20b)%20-%3E%0A%20%20%0A%20%20noop%0A%20%20%0A%20%20b%3A%20b%0A%20%20y%3A%20a.s%0A)

Input: 
```coffee
define [
  # Paths to files go here
], (a, b) ->
  
  noop
  
  b: b
  y: a.s

```

output:

```js
/*
 * decaffeinate suggestions:
 * DS102: Remove unnecessary code created because of implicit returns
 * Full docs: https://github.com/decaffeinate/decaffeinate/blob/master/docs/suggestions.md
 */
define([
  // Paths to files go here
], function(a, b) {
  
  noop;
  
  return {
    b,
    y: a.s
  };
});

```

**Comment by eventualbuddha** [comment]
Thanks for taking time to file an issue! This is actually correct:

```js
define([
  // Paths to files go here
], (a, b) =>
  
  ({
    b,
    y: a.s
  })
);
```

Since the arrow function (`=>`) lacks a block statement body (`{ … }`) it implicitly returns its expression body, namely the object `{ b, y: a.s }` just as it would in CoffeeScript. I agree that you might not ordinarily write an AMD module this way, but decaffeinate doesn't know not to make that change.

**Comment by pskaarup** [comment]
Thank you for the quick response. 

I'll look into babel, it should be able to convert it the rest of the way.

**Comment by eventualbuddha** [comment]
babel won't preserve your formatting unless you use a tool like recast (or [codemod](https://github.com/codemod-js/codemod), which uses recast) to preserve formatting. If you're planning to reformat using [prettier](https://prettier.io) then you may not care. Perhaps if decaffeinate had a `--no-modernize-js` option that would omit the `esnext` stage that would work for you?

**Comment by pskaarup** [comment]
The reason i ran into above issue is an old version of nashorn which doesn't support fat arrows. Passing source code through babel solved the issue at runtime, which is enough.
