### ISSUE TITLE
Add "Omit the property value in Object declaration"

### ISSUE THREAD

**Issue by giancarlocp** [decaffeinate/decaffeinate#1389]
The decaffeinate goals are improve readability and save typing or hand movement.

### Add a feature that save typing in ES6

> Omit the property value when the assigning a property value matches the property name

from this:
```coffee
# Objects:
math =
  root:   Math.sqrt
  square: square
```
to this:
```coffee
# Objects:
math =
  root: Math.sqrt
  square,
```
### Fix spread notation
Change the Arrow function notation from  `=>` to `->` save hand movement. Good.
But change spread notation from `...foo` to `foo...` save nothing and add needless brain synapses. I think keeping things simple and tight to **ES6** when we gain nothing is the Right choose.

**Comment by giancarlocp** [comment]
### Losing the control
I'm a python dev, and appreciate coffee and this.
But in some situation is overburden in decision, and we lose control over the resulting code.
this:
```coffee
alert "I knew it!" if elvis?
```
should be:
```js
if (elvis) { alert("I knew it!"); }
```
and not this:
```js
if (typeof elvis !== 'undefined' && elvis !== null) { alert("I knew it!"); }
```

because this:
```coffee
alert "I knew it!" if elvis==0?
```
Is converted in:
```js
if (elvis===(0 != null)) { alert("I knew it!"); }
```
instead this:
```js
if (elvis==0) { alert("I knew it!"); }
```
Again it is overburden and we lose control over the result.

**Comment by eventualbuddha** [comment]
Hi @giancarlocp. I don't think I understand exactly what you're asking. In the case of objects with keys/values that have the same name this is exactly what happens [when converting to JavaScript](https://decaffeinate-project.org/repl/#?useCS2=false&useJSModules=false&loose=false&evaluate=true&stage=full&code=%23%20Objects%3A%0Amath%20%3D%0A%20%20root%3A%20%20%20Math.sqrt%0A%20%20square%3A%20square):

```js
// Objects:
const math = {
  root:   Math.sqrt,
  square
};
```

Converting to concise objects happens using the esnext stage, and is not meant to happen in the CoffeeScript-to-CoffeeScript normalize stage.

I don't understand the complaint about `...foo`. Can you provide an example?

**Comment by eventualbuddha** [comment]
If you'd like to continue discussion on this topic please feel free to comment.
