### ISSUE TITLE
AddVariableDeclarationsStage failed to parse

### ISSUE THREAD

**Issue by frchretien** [decaffeinate/decaffeinate#1412]
decaffeinate is producing the wrong JavaScript based on my CoffeeScript input:

```coffee
<FILL THIS IN>
```

<LINK TO REPL>

I get this output:

```js
<FILL THIS IN>
```

Here's what I expect it to be instead:

```js
<FILL THIS IN>
```

**Comment by eventualbuddha** [comment]
Can you edit the description to include the code that's failing? Or is this happening on all code?
