### ISSUE TITLE
Ternary Operator Implies Parenthesis

### ISSUE THREAD

**Issue by thebanjomatic** [decaffeinate/decaffeinate#144]
In the [contribution guide](https://github.com/decaffeinate/decaffeinate/blob/master/CONTRIBUTING.md#patchers-with-children), you wrote:
>Now `a + if b then c else d` will become `a + b ? c : d;` as intended, since the right patcher knows to patch using patchAsExpression instead of patchAsStatement. In reality, PlusOp and several other binary operators are all handled by BinaryOpPatcher.`

Shouldn't this more correctly be patched as `a + (b ? c : d)`? 

Because of the condition `b` is enclosed within the ternary, parenthesis are implied here (and generated by the coffeescript compiler in this case). We probably shouldn't always add parenthesis, but I believe they should become explicit/required as a general case whenever a left-associative operator meets a right-associative operator.

**Comment by eventualbuddha** [comment]
@thebanjomatic you're correct. I'll make a PR soon.
