### ISSUE TITLE
Fails on default values in destructuring arguments

### ISSUE THREAD

**Issue by alexgorbatchev** [decaffeinate/decaffeinate#148]
using 1.44.13

```
Error: Syntax error on line 5, column 38: unexpected '=' (\u003D)
2 : logentries = require 'logentries'
3 :
4 : class Logentries extends winston.Transport
5 :   constructor: ({token, level, levels = winston.levels, secure = true}) ->
^ :                                     ^
6 :     super
7 :
8 :     @name = 'logentries'
```

**Comment by eventualbuddha** [comment]
This works as expected on master. Consider this blocked on #65.

**Comment by eventualbuddha** [comment]
This works in v2.7.4, and probably earlier ([repl](http://decaffeinate.github.io/decaffeinate/repl/#?evaluate=false&code=class%20Logentries%20extends%20winston.Transport%0A%20%20constructor%3A%20(%7Btoken%2C%20level%2C%20levels%20%3D%20winston.levels%2C%20secure%20%3D%20true%7D)%20-%3E%0A%20%20%20%20super%0A%20%20%20%20%40name%20%3D%20'logentries')).
