### ISSUE TITLE
Strange variable name clash with `await`

### ISSUE THREAD

**Issue by IlyaSkriblovsky** [decaffeinate/decaffeinate#1483]
decaffeinate is crashing on my CoffeeScript input:

```coffee
class C
    f: ->
        await g(
            for a in b
                42
        )

        r = {}
        x = r.a
```

[(repl)](https://decaffeinate-project.org/repl/#?useCS2=true&useJSModules=false&loose=false&evaluate=false&stage=full&code=class%20C%0A%20%20%20%20f%3A%20->%0A%20%20%20%20%20%20%20%20await%20g(%0A%20%20%20%20%20%20%20%20%20%20%20%20for%20a%20in%20b%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2042%0A%20%20%20%20%20%20%20%20)%0A%0A%20%20%20%20%20%20%20%20r%20%3D%20%7B%7D%0A%20%20%20%20%20%20%20%20x%20%3D%20r.a)

I get this error:

```
stdin: AddVariableDeclarationsStage failed to parse: Unexpected token (2:8)
  1 | class C {
> 2 |     var a;;
    |         ^
  3 |     async f() {
  4 |         await g((() => {
```

Seems that `a` loop variable somehow clashes with `r.a` field access. It seems misterious to me.

I tried to simplify this code more, but it seems that `await` and `class` are important to reproduce this failure.

**Comment by eventualbuddha** [comment]
This is a weird one. I'm guessing something is wrong with the scope handling.

**Comment by eventualbuddha** [comment]
This particular case is now fixed in v6.0.7, but I think there's still an issue lurking. I never did anything in #1505 to address the variable declaration being created inside the class body. If I can reduce a case that hoists the variable declaration to the wrong scope I'll create a new issue and close this one.

**Comment by eventualbuddha** [comment]
Okay, I isolated #1506 so I'm going to close this.
