### ISSUE TITLE
Missing parentheses in loose mode inside JSX

### ISSUE THREAD

**Issue by IlyaSkriblovsky** [decaffeinate/decaffeinate#1484]
decaffeinate is producing the wrong JavaScript based on my CoffeeScript input:

```coffee
<ul>{
    for item in list ? []
        <li/>
}</ul>
```

[(repl)](https://decaffeinate-project.org/repl/#?useCS2=true&useJSModules=false&loose=true&evaluate=true&stage=full&code=%3Cul%3E%7B%0A%20%20%20%20for%20item%20in%20list%20%3F%20%5B%5D%0A%20%20%20%20%20%20%20%20%3Cli%2F%3E%0A%7D%3C%2Ful%3E%0A)

I get this output:

```js
<ul>{
    typeof list !== 'undefined' && list !== null ? list : [].map((item) =>
        <li/>)
}</ul>;
```

Here's what I expect it to be instead:

```js
<ul>{
    (typeof list !== 'undefined' && list !== null ? list : []).map((item) =>
        <li/>)
}</ul>;
```

Same loop outside of JSX tag works well. Array.from() in strict mode solves the issue too.

**Comment by eventualbuddha** [comment]
This appears to be unrelated to JSX ([repl](https://decaffeinate-project.org/repl/#?useCS2=true&useJSModules=false&loose=true&evaluate=true&stage=full&code=a(b%20for%20c%20in%20d%20%3F%20%5B%5D))):

```coffee
a(b for c in d ? [])
```

Produces:

```js
a(typeof d !== 'undefined' && d !== null ? d : [].map((c) => b));
```

**Comment by IlyaSkriblovsky** [comment]
Thanks!
