### ISSUE TITLE
Promise chaining not supported with indentation

### ISSUE THREAD

**Issue by mariano54** [decaffeinate/decaffeinate#165]
`db('table')\n
    .push myObject
    .then () ->
        console.log "DB entry pushed"`

Is not supported. However this is valid CS and should work. It does work if I unindent the push, then, and log lines.

**Comment by Eden-Sun** [comment]
@eventualbuddha @mariano54 
v2.3.0 works well, why not update to http://decaffeinate.github.io/decaffeinate/repl/ ?

**Comment by eventualbuddha** [comment]
This works in v2.7.4, and probably earlier ([repl](http://decaffeinate.github.io/decaffeinate/repl/#?evaluate=false&code=db('table')%0A%20%20.push%20myObject%0A%20%20.then%20()%20-%3E%20console.log%20%22DB%20entry%20pushed%22)).
