### ISSUE TITLE
REPL / Demo not working

### ISSUE THREAD

**Issue by alexlawrence** [decaffeinate/decaffeinate#168]
When visiting http://decaffeinate.github.io/decaffeinate/repl/ the following errors are thrown:

> TypeError: fs.readdirSync is not a function
> ReferenceError: decaffeinate is not defined

The page does not work at all.

Tested in recent Firefox and Chrome.

**Comment by eventualbuddha** [comment]
Sorry about that. I tried to use the dev version but it doesn't browserify correctly due to eslint. See #174 which will hopefully fix it.

**Comment by sandstrom** [comment]
@eventualbuddha Sounds great! Will the demo update itself automatically (some build pipeline), or is that a manual step?

Decaffeinate is an awesome tool btw! :trophy:

**Comment by eventualbuddha** [comment]
This is fixed now! The update happens [every time I do a release](https://github.com/decaffeinate/decaffeinate/blob/89bf32727a9e85d47099fb17cb70b95d7e1ea694/script/release.sh#L57).

> Decaffeinate is an awesome tool btw!

Thanks 😄
