### ISSUE TITLE
Fails with , beginning of line

### ISSUE THREAD

**Issue by djforth** [decaffeinate/decaffeinate#171]
Hi, just found this and really good tool so fair, but have spotted If you have a , at the beginning of a line like so:

```coffee
this.location_timeout = setTimeout(()->
        that.geoLoc.clearWatch(that.geoID)
        that.getError.call(that)
        # that.lightbox.clearHandler()
      , 10000)
```

I get:

```
Error: Syntax error on line 159, column 6: unexpected ',' (\u002C)
156 :         that.geoLoc.clearWatch(that.geoID)
157 :         that.getError.call(that)
158 :         # that.lightbox.clearHandler()
159 :       , 10000)
^^^ :      ^
160 : 
161 :       this.geoID = this.geoLoc.watchPosition (p)->
162 :         that.clearGeo()
```

**Comment by eventualbuddha** [comment]
This seems to work for me in the latest version ([repl](http://decaffeinate.github.io/decaffeinate/repl/#?evaluate=false&code=this.location_timeout%20%3D%20setTimeout(()-%3E%0A%20%20%20%20%20%20%20%20that.geoLoc.clearWatch(that.geoID)%0A%20%20%20%20%20%20%20%20that.getError.call(that)%0A%20%20%20%20%20%20%20%20%23%20that.lightbox.clearHandler()%0A%20%20%20%20%20%20%2C%2010000))):

```js
export let location_timeout = setTimeout(function(){
        that.geoLoc.clearWatch(that.geoID);
        return that.getError.call(that);
}
        // that.lightbox.clearHandler()
      , 10000);
```

**Comment by maxgalbu** [comment]
This seems to fail when there's a semicolon on the last instruction: 

[without semicolon](http://decaffeinate-project.org/repl/#?evaluate=true&code=setTimeout(()%20-%3E%0A%20%20hello%20%3D%201%3B%0A%20%20test(hello)%0A%2C%20122)) vs [with semicolon](http://decaffeinate-project.org/repl/#?evaluate=true&code=setTimeout(()%20-%3E%0A%20%20hello%20%3D%201%3B%0A%20%20test(hello)%3B%0A%2C%20122))
