### ISSUE TITLE
Interpolation of two variables leads to `cannot find first or last token in node`

### ISSUE THREAD

**Issue by joshma** [decaffeinate/decaffeinate#177]
Running `decaffeinate v2.7.3`: I think this is a minimal repro:

```
"#{PREFIX}_#{SUFFIX}"
###
./test.coffee → test.js
./test.coffee: cannot find first or last token in node
> 1 | "#{PREFIX}_#{SUFFIX}"
    |
  2 |

[1]    24919 exit 1     ./node_modules/.bin/decaffeinate ./test.coffee
```

Weirdly enough, this doesn't error:
```
"#{PREFIX}#{SUFFIX}"
###
./test.coffee → test.js
```

**Comment by Eden-Sun** [comment]
https://github.com/decaffeinate/decaffeinate-parser/pull/8

**Comment by eventualbuddha** [comment]
Thanks @Eden-Sun! This is fixed in v2.7.7 ([repl](http://decaffeinate.github.io/decaffeinate/repl/#?evaluate=false&code=%22%23%7BPREFIX%7D_%23%7BSUFFIX%7D%22)).

**Comment by eventualbuddha** [comment]
This is still failing, apparently (see [repl](http://decaffeinate.github.io/decaffeinate/repl/#?evaluate=true&code=%20s%20%3D%20%22%23%7Ba%7D%20%23%7Bb%7D%22)).

**Comment by eventualbuddha** [comment]
Okay, *now* it's working. Thanks @Eden-Sun!
