### ISSUE TITLE
new release did not update the gh-pages to newest version .

### ISSUE THREAD

**Issue by Eden-Sun** [decaffeinate/decaffeinate#186]
http://decaffeinate.github.io/decaffeinate/repl/  is not actually working on the version as it showed (v2.7.8).

**Comment by eventualbuddha** [comment]
I'm not sure I understand. The version on npm is v2.7.8, the version on the repl says v2.7.8, checking the version in the console of the repl (`decaffeinate.version`) says `"2.7.8"`. What's wrong with it?

**Comment by Eden-Sun** [comment]
You have close #177 and v2.7.8 CLI did passed all tests.
But there is still problems interpolating two variables .
http://decaffeinate.github.io/decaffeinate/repl/#?evaluate=true&code=%20s%20%3D%20%22%23%7Ba%7D%20%23%7Bb%7D%22

**Comment by Eden-Sun** [comment]
https://github.com/decaffeinate/decaffeinate/commit/c991ebe408457916fbf5fae41a2388dbc53cb988
It removed your previous additions. 
Maybe you just need to push it again?

**Comment by eventualbuddha** [comment]
@Eden-Sun Your example seems to work now that I've pushed v2.7.9.
