### ISSUE TITLE
ES2020 optional chaining instead of guard

### ISSUE THREAD

**Issue by aminya** [decaffeinate/decaffeinate#1909]
It would be nice if decaffeinate generates optional chaining that is introduced in ES2020, and is supported by the latest browsers and Babel/TypeScript.

**Comment by piittis** [comment]
I've been moving to Typescript using this tool and it's been pretty great! Optional chaining is missing though.

Might look into it at some point when I have time! If you badly need it In the meantime, you can do this hack to leave original coffeescript chains in place (which should be correct javascript in most situations?):

In decaffeinate install location, find all `_shouldSkipSoakPatch = false` and replace with `_shouldSkipSoakPatch = true`

**Comment by aminya** [comment]
@piittis Does `_shouldSkipSoakPatch` include anything else? if not adding a compiler option for skipping this is very easy!

**Comment by piittis** [comment]
Don't know the codebase that much, so I can't say. Also AFAIK the semantics are not 1-to-1 between coffeescript and javascript. So a proper transpilation would be better of course.

**Comment by krissrex** [comment]
I tried this on my codebase by patching `_shouldSkipSoakPatch`, and it seems the syntax produced for array access is wrong:

* original coffee: `if rows?[0]`
* generated: `if (rows?[0]) {`
* expected: `if (rows?.[0]) {` 

(I used [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#Array_item_access_with_optional_chaining) as the reference for correct js.)

**Comment by aminya** [comment]
This only fixes property access and not function calls.

See the ongoing PR here https://github.com/decaffeinate/decaffeinate/pull/1969

**Comment by krissrex** [comment]
> This only fixes property access and not function calls.
> 
> See the ongoing PR here #1969. You can try it using:
> 
> ```
> # in the cloned branch
> npm link .
> ```
> 
> ```
> # in your target repo
> npm link decaffeinate
> ```

I'm trying now. Here is my process:

```bash
npm uninstall -g decaffeinate
npm install -g yarn
git clone https://github.com/aminya/decaffeinate
cd decaffeinate
git checkout optionalChaining
yarn install
```

after install, `prebuild` was triggered, and eslint reported some issues:
```
decaffeinate\test\cli_test.ts
  9:72  error  Type boolean trivially inferred from a boolean literal, remove type annotation  @typescript-eslint/no-inferrable-types

decaffeinate\test\utils\toUnix.ts
  7:2  error  Insert `␍⏎`  prettier/prettier
```
so I had to fix that first.

> Sidenote: use a fixed version of prettier: 
> no:  "prettier": "^1.19.0"
> yes: "prettier": "1.19.0",
> see https://prettier.io/docs/en/install.html, they recommend `--save-exact`.


```diff
diff --git a/test/cli_test.ts b/test/cli_test.ts
index 3a1c7e9..fcebc4b 100644
--- a/test/cli_test.ts
+++ b/test/cli_test.ts
@@ -6,7 +6,7 @@ import { copySync } from 'fs-extra';
 import stripSharedIndent from '../src/utils/stripSharedIndent';
 import { toUnix } from './utils/toUnix';

-function runCli(argStr: string, stdin: string, expectedStdout: string, convertToUnix: boolean = false): void {
+function runCli(argStr: string, stdin: string, expectedStdout: string, convertToUnix = false): void {
   if (stdin[0] === '\n') {
     stdin = stripSharedIndent(stdin);
   }
diff --git a/test/utils/toUnix.ts b/test/utils/toUnix.ts
index 564628e..fc42897 100644
--- a/test/utils/toUnix.ts
+++ b/test/utils/toUnix.ts
@@ -4,4 +4,4 @@ export function toUnix(s: string): string {
     s = s.replace(double, '/');
   }
   return s;
-}
\ No newline at end of file
+}
```

Then I tried again
```bash
yarn build
npm link .
```

**Comment by aminya** [comment]
Yes. It is strange that Eslint does not understand that the type-annotation in the function head is used for safety, and the inference is not much relevant there. 😄

**Comment by krissrex** [comment]
> Yes. It is strange that Eslint does not understand that the type-annotation in the function head is used for safety, and the inference is not much relevant there. 😄

Eslint understands it, but a typescript rule says it's a bad practice. The default value is already specifying the parameter to be a boolean, so the type declaration is unnecessary.
See [no-inferrable-types](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-inferrable-types.md):
> Explicit types where they can be easily inferred may add unnecessary verbosity.

Anyways, the array access is still not working in your branch. Did you add tests for that case?

**Comment by krissrex** [comment]
For now, I think I just convert those files without `--optional-chaining`, and manually replace the `guard`. 
@aminya's fix seems to work for the other cases. (I still have to run my tests on the converted code to verify correctness, however.)

**Comment by aminya** [comment]
If you can make a PR to my PR, we will solve it. 

The conversion is pretty simple, but the code is written in a complex way, which makes it hard to adjust. @eventualbuddha can help us. 

I have added TODO functions:
- `a.b?() to a.b?.()` [here](https://github.com/decaffeinate/decaffeinate/pull/1969/files#diff-944a89de225737371918a33ded7ee542R127)
- `a[b]?() to a[b]?.()` [here](https://github.com/decaffeinate/decaffeinate/pull/1969/files#diff-944a89de225737371918a33ded7ee542R164)

**Comment by eventualbuddha** [comment]
You can now enable optional chaining on the website too. [Here's an example from the CoffeeScript web page](https://decaffeinate-project.org/repl/#?useCS2=true&useJSModules=false&loose=false&optionalChaining=true&evaluate=false&stage=full&code=zip%20%3D%20lottery.drawWinner%3F().address%3F.zipcode%0A).

**Comment by aminya** [comment]
Awesome! :tada:
