### ISSUE TITLE
Drop trailing `return` in functions

### ISSUE THREAD

**Issue by eventualbuddha** [decaffeinate/decaffeinate#193]
If the last statement of a function is an explicit return without an argument, we should just remove it since that's a pretty typical way to avoid the implicit return mechanism of CoffeeScript (from #187).

**Comment by banderson5144** [comment]
Still having an issue with this. Only way I am able to convert is commenting out the empty return

**Comment by alangpierce** [comment]
@banderson5144 could you give a link to the repl ( http://decaffeinate-project.org/repl/ ) showing a case that doesn't work? Also, to be clear, the original issue here didn't cause conversion failures, it just made it so there was an unnecessary `return;` at the end of JS functions.

**Comment by banderson5144** [comment]
Wasnt using REPL, Will send screenshots

**Comment by banderson5144** [comment]
![image](https://cloud.githubusercontent.com/assets/2395774/20434150/93c43356-ad74-11e6-81c9-0ed1036dfd5e.png)

![image](https://cloud.githubusercontent.com/assets/2395774/20434176/abada63c-ad74-11e6-8217-fe695973757e.png)

**Comment by alangpierce** [comment]
I'm not able to reproduce the issue from your screenshot; it may depend on the details of the above code that's cut off, or the parsing details of the intermediate code, which I didn't exactly transcribe. If you paste the code into the repl, it should show the same error at the bottom, and the URL will change to a shareable link that you can paste, which would make it easier to track down. You could also try narrowing down the issue by removing/simplifying pieces of code until you have a code snippet that's simpler and still gives the same error.

**Comment by banderson5144** [comment]
https://raw.githubusercontent.com/joeferraro/MavensMate-Atom/master/lib/watchers/atom-watcher.coffee

**Comment by banderson5144** [comment]
http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=emitter%20%3D%20require('..%2Femitter').pubsub%0D%0A%0D%0ARepeat%20%3D%20require%20'repeat'%0D%0A%0D%0A%23%20use%20this%20class%20to%20register%20watchers%20for%20atom-specific%20attributes%20(font%20size%2C%20settings%2C%20etc)%0D%0A%23%20emit%20events%20for%20subscription%20by%20other%20plugin%20classes%0D%0Aclass%20AtomWatcher%0D%0A%0D%0A%20%20constructor%3A%20()%20-%3E%0D%0A%20%20%20%20atom.mavensmate.currentFontSize%20%3D%20jQuery(%22atom-text-editor%3A%3Ashadow%20div.editor-contents--private%22).css(%22font-size%22)%0D%0A%20%20%20%20%40startWatching()%0D%0A%0D%0A%20%20startWatching%3A%20-%3E%0D%0A%20%20%20%20Repeat(%40watchFontSize).every(100%2C%20'ms').start.now()%0D%0A%0D%0A%20%20%23%20watches%20editor%20font%20size%2C%20emits%20event%20when%20it%20changes%20so%20that%20mavensmate%20views%20can%20update%20accordingly%0D%0A%20%20watchFontSize%3A%20-%3E%0D%0A%20%20%20%20newFontSize%20%3D%20jQuery(%22atom-text-editor%3A%3Ashadow%20div.editor-contents--private%22).css(%22font-size%22)%0D%0A%20%20%20%20if%20newFontSize%20!%3D%20atom.mavensmate.currentFontSize%0D%0A%20%20%20%20%20%20atom.mavensmate.currentFontSize%20%3D%20newFontSize%0D%0A%20%20%20%20%20%20emitter.emit%20'mavensmate%3Afont-size-changed'%2C%20atom.mavensmate.currentFontSize%0D%0A%20%20%20%20return%0D%0A%0D%0Awatcher%20%3D%20new%20AtomWatcher()%0D%0Aexports.mm%20%3D%20watcher

**Comment by alangpierce** [comment]
Thanks! That seems to be working for me in the repl ([link](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=emitter%20%3D%20require('..%2Femitter').pubsub%0A%0ARepeat%20%3D%20require%20'repeat'%0A%0A%23%20use%20this%20class%20to%20register%20watchers%20for%20atom-specific%20attributes%20(font%20size%2C%20settings%2C%20etc)%0A%23%20emit%20events%20for%20subscription%20by%20other%20plugin%20classes%0Aclass%20AtomWatcher%0A%0A%20%20constructor%3A%20()%20-%3E%0A%20%20%20%20atom.mavensmate.currentFontSize%20%3D%20jQuery(%22atom-text-editor%3A%3Ashadow%20div.editor-contents--private%22).css(%22font-size%22)%0A%20%20%20%20%40startWatching()%0A%0A%20%20startWatching%3A%20-%3E%0A%20%20%20%20Repeat(%40watchFontSize).every(100%2C%20'ms').start.now()%0A%0A%20%20%23%20watches%20editor%20font%20size%2C%20emits%20event%20when%20it%20changes%20so%20that%20mavensmate%20views%20can%20update%20accordingly%0A%20%20watchFontSize%3A%20-%3E%0A%20%20%20%20newFontSize%20%3D%20jQuery(%22atom-text-editor%3A%3Ashadow%20div.editor-contents--private%22).css(%22font-size%22)%0A%20%20%20%20if%20newFontSize%20!%3D%20atom.mavensmate.currentFontSize%0A%20%20%20%20%20%20atom.mavensmate.currentFontSize%20%3D%20newFontSize%0A%20%20%20%20%20%20emitter.emit%20'mavensmate%3Afont-size-changed'%2C%20atom.mavensmate.currentFontSize%0A%20%20%20%20return%0A%0Awatcher%20%3D%20new%20AtomWatcher()%0Aexports.mm%20%3D%20watcher)), and it looks like your error might be one of a few bugs that I fixed relatively recently. Can you make sure you're on the latest version of decaffeinate?

**Comment by banderson5144** [comment]
literally did a npm install -g 10 minutes ago

**Comment by alangpierce** [comment]
Thanks, I tracked it down. Looks like decaffeinate isn't properly handling Windows line endings (I'm on Mac, so when I copied and pasted into the repl on my machine it worked fine). As a workaround, you may be able to convert the code to unix line endings (LF instead of CR-LF) before running it through decaffeinate. I'll file a separate task.

**Comment by banderson5144** [comment]
ahhhhh makes sense
