### ISSUE TITLE
how to use import

### ISSUE THREAD

**Issue by Eden-Sun** [decaffeinate/decaffeinate#211]
how to have
```js
import fs from "fs";
```

**Comment by eventualbuddha** [comment]
I'm not sure I understand. You can get this as *output* by using [this](http://decaffeinate.github.io/decaffeinate/repl/#?evaluate=true&code=fs%20%3D%20require%20'fs') as input:

```coffee
fs = require 'fs'
```

**Comment by Eden-Sun** [comment]
Actually I know it . But isn't it strange transferring  `require` to -> `import` ?
Both of them are not standard yet.
Compiling to `import` means we must use babel as register. 
Without `import` , compiled code might ran in modern node natively. 
Would it be better or just choose the more poetical one?
