### ISSUE TITLE
fat arrow functions bound before calls to super render constructors invalid

### ISSUE THREAD

**Issue by smurp** [decaffeinate/decaffeinate#2141]
decaffeinate is producing the wrong JavaScript based on my CoffeeScript input:

```coffee
class SuperClass
  constructor: () ->
    @a = 1
class SubClass extends SuperClass
  fatArrowFunction: () =>
    @b = 1
    return
```
I get this output:

```js
/*
 * decaffeinate suggestions:
 * DS002: Fix invalid constructor
 * Full docs: https://github.com/decaffeinate/decaffeinate/blob/master/docs/suggestions.md
 */
class SuperClass {
  constructor() {
    this.a = 1;
  }
}
class SubClass extends SuperClass {
  constructor(...args) {
    this.fatArrowFunction = this.fatArrowFunction.bind(this);
    super(...args);
  }

  fatArrowFunction() {
    this.b = 1;
  }
}
```

Here's what I expect it to be instead:

```js
class SuperClass {
  constructor() {
    this.a = 1;
  }
}
class SubClass extends SuperClass {
  constructor(...args) {
    super(...args);
    this.fatArrowFunction = this.fatArrowFunction.bind(this);
  }

  fatArrowFunction() {
    this.b = 1;
  }
}
```

**Comment by eventualbuddha** [comment]
Previously decaffeinate would produce code that worked around this when using Babel or TypeScript to transpile to ES5 or lower, but Babel changed in a way that broke the workaround. Given that the workaround didn't work when using real ES6 classes, I just decided to remove it in https://github.com/decaffeinate/decaffeinate/commit/14ab7975138cc63366324a07956a7a30f78903c3.

Note that the output you posted does indicate that you should fix the invalid constructor. Most of the time you can simply change it manually to be as you wrote it, but it's possible that you'd been relying on the ordering that bound the method first, so that's how it leaves it.

**Comment by eventualbuddha** [comment]
That's a fair point, though the only way I can think of to fix this is to use ES5-style classes. That's almost certainly more work than anyone is willing to put in.

**Comment by smurp** [comment]
I know nothing about decaffeinate's internals -- forgive me -- but given that decaffeinate introduces the `.bind(this)` lines itself, can't it have control over whether they come before the call to `super`?

**Comment by eventualbuddha** [comment]
@smurp I noticed in looking into this that CS2 binds methods after calling `super` to be compatible with ES6 classes. I submitted #2143 to fix that. Once that's in, you can do `--use-cs2` to opt into that behavior. It may change other things too, though.

**Comment by grassick** [comment]
I'm still seeing this one in version 6.1.8 with option `--use-cs2`. See attached input and output:

[Failed conversion.zip](https://github.com/decaffeinate/decaffeinate/files/6681288/Failed.conversion.zip)

e.g.:

```
 constructor(props) {
      this.handleAnswerChange = this.handleAnswerChange.bind(this);
      this.handleEntryDataChange = this.handleEntryDataChange.bind(this);
      this.handleAdd = this.handleAdd.bind(this);
      this.handleRemove = this.handleRemove.bind(this);
      this.handleCellChange = this.handleCellChange.bind(this);
      this.handleSort = this.handleSort.bind(this);
      this.renderEntry = this.renderEntry.bind(this);
      super(props);

      this.state = {
        validationErrors: {}  // Map of "<rowindex>_<columnid>" to validation error
      };
    }

```

Is there some reason the fix isn't being used in this case?

**Comment by softgripper** [comment]
Same issue as above.

Having a CoffeeScript sub class that calls super is putting all the binds before the super call, regardless of the ```--use-cs2``` flag.

[valid-and-invalid.zip](https://github.com/decaffeinate/decaffeinate/files/8558993/valid-and-invalid.zip)

**Comment by danwashusen** [comment]
@softgripper and I spent some time debugging yesterday and came up with the following fix for the issue he documents:
https://github.com/sixtydigits/decaffeinate/commit/b43dbde30c0318aa4d27672a8fc3609ce537c875

As noted in the commit message, this change assumes you're always using `--use-cs2`. I'd say more work is required before it could be merged into decaffinate proper...
