### ISSUE TITLE
Cannot parse some switch statements

### ISSUE THREAD

**Issue by sethyates** [decaffeinate/decaffeinate#215]
This switch statement results in `SyntaxError: Unexpected token`.  It appears that the parser requires some sort of operator between `when` and `then`, and having just an identifier results in a syntax error.

```
grade = (score) ->
  switch
    when true then 'F'
    when score < 70 then 'D'
    when score < 80 then 'C'
    when score < 90 then 'B'
    else 'A'
```

**Comment by Eden-Sun** [comment]
What is this case used for ? Coffeescript compiles to
```js
var grade;

grade = function(score) {
  switch (false) {
    case !true:
      return 'F';
    case !(score < 70):
      return 'D';
    case !(score < 80):
      return 'C';
    case !(score < 90):
      return 'B';
    default:
      return 'A';
  }
};
```
Without any switching element, It always returns first case . 
I mean. This works .    
http://decaffeinate.github.io/decaffeinate/repl/#?evaluate=true&code=grade%20%3D%20(score)%20-%3E%0A%20%20switch%20score%0A%20%20%20%20when%20true%20then%20'F'%0A%20%20%20%20when%20score%20%3C%2070%20then%20'D'%0A%20%20%20%20when%20score%20%3C%2080%20then%20'C'%0A%20%20%20%20when%20score%20%3C%2090%20then%20'B'%0A%20%20%20%20else%20'A'

**Comment by sethyates** [comment]
It was a contrived example, copied and modified from the CoffeeScript website.  In our real code, we use variables.  Really, seems that anything that doesn't include an operator causes this.

**Comment by madskonradsen** [comment]
I agree, stuff like the following does compile perfectly to coffeescript, so should of course not throw errors in decaffeinate:

```javascript
myVar = "something"

grade = (score) ->
  switch
    when myVar then 'F'
    when score < 70 then 'D'
    when score < 80 then 'C'
    when score < 90 then 'B'
    else 'A'
```

**Comment by alangpierce** [comment]
Looks like this is fixed now.
