### ISSUE TITLE
no patcher available for node type: SoakedDynamicMemberAccessOp

### ISSUE THREAD

**Issue by sethyates** [decaffeinate/decaffeinate#216]
```
$ echo 'myObject?[myKey]' | decaffeinate
stdin: no patcher available for node type: SoakedDynamicMemberAccessOp (props: expression, indexingExpr)
> 1 | myObject?[myKey]
    | ^^^^^^^^^^^^^^^^
  2 |
```

**Comment by madskonradsen** [comment]
Kind of dupe of #176 
Join our discussion

**Comment by sethyates** [comment]
Kind of, but different error message and different application type, and I didn't see this particular use case listed when I looked at that issue (I did check before raising).  I don't know anything about the parser/patcher, so it might be a different code path as well.

**Comment by eventualbuddha** [comment]
It's essentially the same as #176, but I'll leave it open to people can find it more easily.
