### ISSUE TITLE
AddVariableDeclarationsStage failed to parse: Unexpected token (4:0)

### ISSUE THREAD

**Issue by icai** [decaffeinate/decaffeinate#2169]
my code:

```coffee
class app.views.Content extends app.View
  @el: '._content'
  @loadingClass: '_content-loading'

  @events:
    click: 'onClick'

  @shortcuts:
    altUp:      'scrollStepUp'
    altDown:    'scrollStepDown'
    pageUp:     'scrollPageUp'
    pageDown:   'scrollPageDown'
    pageTop:    'scrollToTop'
    pageBottom: 'scrollToBottom'
    altF:       'onAltF'

  @routes:
    before: 'beforeRoute'
    after:  'afterRoute'

  init: ->
    @scrollEl = if app.isMobile()
      (document.scrollingElement || document.body)
    else
      @el
    @scrollMap = {}
    @scrollStack = []

    @rootPage     = new app.views.RootPage
    @staticPage   = new app.views.StaticPage
    @settingsPage = new app.views.SettingsPage
    @offlinePage  = new app.views.OfflinePage
    @typePage     = new app.views.TypePage
    @entryPage    = new app.views.EntryPage

    @entryPage
      .on 'loading', @onEntryLoading
      .on 'loaded', @onEntryLoaded

    app
      .on 'ready', @onReady
      .on 'bootError', @onBootError

    return

  show: (view) ->
    @hideLoading()
    unless view is @view
      @view?.deactivate()
      @html @view = view
      @view.activate()
    return

  showLoading: ->
    @addClass @constructor.loadingClass
    return

  isLoading: ->
    @el.classList.contains @constructor.loadingClass

  hideLoading: ->
    @removeClass @constructor.loadingClass
    return

  scrollTo: (value) ->
    @scrollEl.scrollTop = value or 0
    return

  smoothScrollTo: (value) ->
    if app.settings.get('fastScroll')
      @scrollTo value
    else
      $.smoothScroll @scrollEl, value or 0
    return

  scrollBy: (n) ->
    @smoothScrollTo @scrollEl.scrollTop + n
    return

  scrollToTop: =>
    @smoothScrollTo 0
    return

  scrollToBottom: =>
    @smoothScrollTo @scrollEl.scrollHeight
    return

  scrollStepUp: =>
    @scrollBy -80
    return

  scrollStepDown: =>
    @scrollBy 80
    return

  scrollPageUp: =>
    @scrollBy 40 - @scrollEl.clientHeight
    return

  scrollPageDown: =>
    @scrollBy @scrollEl.clientHeight - 40
    return

  scrollToTarget: ->
    if @routeCtx.hash and el = @findTargetByHash @routeCtx.hash
      $.scrollToWithImageLock el, @scrollEl, 'top',
        margin: if @scrollEl is @el then 0 else $.offset(@el).top
      $.highlight el, className: '_highlight'
    else
      @scrollTo @scrollMap[@routeCtx.state.id]
    return

  onReady: =>
    @hideLoading()
    return

  onBootError: =>
    @hideLoading()
    @html @tmpl('bootError')
    return

  onEntryLoading: =>
    @showLoading()
    if @scrollToTargetTimeout
      clearTimeout @scrollToTargetTimeout
      @scrollToTargetTimeout = null
    return

  onEntryLoaded: =>
    @hideLoading()
    if @scrollToTargetTimeout
      clearTimeout @scrollToTargetTimeout
      @scrollToTargetTimeout = null
    @scrollToTarget()
    return

  beforeRoute: (context) =>
    @cacheScrollPosition()
    @routeCtx = context
    @scrollToTargetTimeout = @delay @scrollToTarget
    return

  cacheScrollPosition: ->
    return if not @routeCtx or @routeCtx.hash
    return if @routeCtx.path is '/'

    unless @scrollMap[@routeCtx.state.id]?
      @scrollStack.push @routeCtx.state.id
      while @scrollStack.length > app.config.history_cache_size
        delete @scrollMap[@scrollStack.shift()]

    @scrollMap[@routeCtx.state.id] = @scrollEl.scrollTop
    return

  afterRoute: (route, context) =>
    if route != 'entry' and route != 'type'
      resetFavicon()

    switch route
      when 'root'
        @show @rootPage
      when 'entry'
        @show @entryPage
      when 'type'
        @show @typePage
      when 'settings'
        @show @settingsPage
      when 'offline'
        @show @offlinePage
      else
        @show @staticPage

    @view.onRoute(context)
    app.document.setTitle @view.getTitle?()
    return

  onClick: (event) =>
    link = $.closestLink $.eventTarget(event), @el
    if link and @isExternalUrl link.getAttribute('href')
      $.stopEvent(event)
      $.popup(link)
    return

  onAltF: (event) =>
    unless document.activeElement and $.hasChild @el, document.activeElement
      @find('a:not(:empty)')?.focus()
      $.stopEvent(event)

  findTargetByHash: (hash) ->
    el = try $.id decodeURIComponent(hash) catch
    el or= try $.id(hash) catch
    el

  isExternalUrl: (url) ->
    url?[0..5] in ['http:/', 'https:']

```

I get this error:

[(REPL)](https://decaffeinate-project.org/repl/#?useCS2=false&useJSModules=false&loose=false&optionalChaining=false&evaluate=false&stage=full&code=class%20app.views.Content%20extends%20app.View%0A%20%20%40el%3A%20'._content'%0A%20%20%40loadingClass%3A%20'_content-loading'%0A%0A%20%20%40events%3A%0A%20%20%20%20click%3A%20'onClick'%0A%0A%20%20%40shortcuts%3A%0A%20%20%20%20altUp%3A%20%20%20%20%20%20'scrollStepUp'%0A%20%20%20%20altDown%3A%20%20%20%20'scrollStepDown'%0A%20%20%20%20pageUp%3A%20%20%20%20%20'scrollPageUp'%0A%20%20%20%20pageDown%3A%20%20%20'scrollPageDown'%0A%20%20%20%20pageTop%3A%20%20%20%20'scrollToTop'%0A%20%20%20%20pageBottom%3A%20'scrollToBottom'%0A%20%20%20%20altF%3A%20%20%20%20%20%20%20'onAltF'%0A%0A%20%20%40routes%3A%0A%20%20%20%20before%3A%20'beforeRoute'%0A%20%20%20%20after%3A%20%20'afterRoute'%0A%0A%20%20init%3A%20-%3E%0A%20%20%20%20%40scrollEl%20%3D%20if%20app.isMobile()%0A%20%20%20%20%20%20(document.scrollingElement%20%7C%7C%20document.body)%0A%20%20%20%20else%0A%20%20%20%20%20%20%40el%0A%20%20%20%20%40scrollMap%20%3D%20%7B%7D%0A%20%20%20%20%40scrollStack%20%3D%20%5B%5D%0A%0A%20%20%20%20%40rootPage%20%20%20%20%20%3D%20new%20app.views.RootPage%0A%20%20%20%20%40staticPage%20%20%20%3D%20new%20app.views.StaticPage%0A%20%20%20%20%40settingsPage%20%3D%20new%20app.views.SettingsPage%0A%20%20%20%20%40offlinePage%20%20%3D%20new%20app.views.OfflinePage%0A%20%20%20%20%40typePage%20%20%20%20%20%3D%20new%20app.views.TypePage%0A%20%20%20%20%40entryPage%20%20%20%20%3D%20new%20app.views.EntryPage%0A%0A%20%20%20%20%40entryPage%0A%20%20%20%20%20%20.on%20'loading'%2C%20%40onEntryLoading%0A%20%20%20%20%20%20.on%20'loaded'%2C%20%40onEntryLoaded%0A%0A%20%20%20%20app%0A%20%20%20%20%20%20.on%20'ready'%2C%20%40onReady%0A%20%20%20%20%20%20.on%20'bootError'%2C%20%40onBootError%0A%0A%20%20%20%20return%0A%0A%20%20show%3A%20(view)%20-%3E%0A%20%20%20%20%40hideLoading()%0A%20%20%20%20unless%20view%20is%20%40view%0A%20%20%20%20%20%20%40view%3F.deactivate()%0A%20%20%20%20%20%20%40html%20%40view%20%3D%20view%0A%20%20%20%20%20%20%40view.activate()%0A%20%20%20%20return%0A%0A%20%20showLoading%3A%20-%3E%0A%20%20%20%20%40addClass%20%40constructor.loadingClass%0A%20%20%20%20return%0A%0A%20%20isLoading%3A%20-%3E%0A%20%20%20%20%40el.classList.contains%20%40constructor.loadingClass%0A%0A%20%20hideLoading%3A%20-%3E%0A%20%20%20%20%40removeClass%20%40constructor.loadingClass%0A%20%20%20%20return%0A%0A%20%20scrollTo%3A%20(value)%20-%3E%0A%20%20%20%20%40scrollEl.scrollTop%20%3D%20value%20or%200%0A%20%20%20%20return%0A%0A%20%20smoothScrollTo%3A%20(value)%20-%3E%0A%20%20%20%20if%20app.settings.get('fastScroll')%0A%20%20%20%20%20%20%40scrollTo%20value%0A%20%20%20%20else%0A%20%20%20%20%20%20%24.smoothScroll%20%40scrollEl%2C%20value%20or%200%0A%20%20%20%20return%0A%0A%20%20scrollBy%3A%20(n)%20-%3E%0A%20%20%20%20%40smoothScrollTo%20%40scrollEl.scrollTop%20%2B%20n%0A%20%20%20%20return%0A%0A%20%20scrollToTop%3A%20%3D%3E%0A%20%20%20%20%40smoothScrollTo%200%0A%20%20%20%20return%0A%0A%20%20scrollToBottom%3A%20%3D%3E%0A%20%20%20%20%40smoothScrollTo%20%40scrollEl.scrollHeight%0A%20%20%20%20return%0A%0A%20%20scrollStepUp%3A%20%3D%3E%0A%20%20%20%20%40scrollBy%20-80%0A%20%20%20%20return%0A%0A%20%20scrollStepDown%3A%20%3D%3E%0A%20%20%20%20%40scrollBy%2080%0A%20%20%20%20return%0A%0A%20%20scrollPageUp%3A%20%3D%3E%0A%20%20%20%20%40scrollBy%2040%20-%20%40scrollEl.clientHeight%0A%20%20%20%20return%0A%0A%20%20scrollPageDown%3A%20%3D%3E%0A%20%20%20%20%40scrollBy%20%40scrollEl.clientHeight%20-%2040%0A%20%20%20%20return%0A%0A%20%20scrollToTarget%3A%20-%3E%0A%20%20%20%20if%20%40routeCtx.hash%20and%20el%20%3D%20%40findTargetByHash%20%40routeCtx.hash%0A%20%20%20%20%20%20%24.scrollToWithImageLock%20el%2C%20%40scrollEl%2C%20'top'%2C%0A%20%20%20%20%20%20%20%20margin%3A%20if%20%40scrollEl%20is%20%40el%20then%200%20else%20%24.offset(%40el).top%0A%20%20%20%20%20%20%24.highlight%20el%2C%20className%3A%20'_highlight'%0A%20%20%20%20else%0A%20%20%20%20%20%20%40scrollTo%20%40scrollMap%5B%40routeCtx.state.id%5D%0A%20%20%20%20return%0A%0A%20%20onReady%3A%20%3D%3E%0A%20%20%20%20%40hideLoading()%0A%20%20%20%20return%0A%0A%20%20onBootError%3A%20%3D%3E%0A%20%20%20%20%40hideLoading()%0A%20%20%20%20%40html%20%40tmpl('bootError')%0A%20%20%20%20return%0A%0A%20%20onEntryLoading%3A%20%3D%3E%0A%20%20%20%20%40showLoading()%0A%20%20%20%20if%20%40scrollToTargetTimeout%0A%20%20%20%20%20%20clearTimeout%20%40scrollToTargetTimeout%0A%20%20%20%20%20%20%40scrollToTargetTimeout%20%3D%20null%0A%20%20%20%20return%0A%0A%20%20onEntryLoaded%3A%20%3D%3E%0A%20%20%20%20%40hideLoading()%0A%20%20%20%20if%20%40scrollToTargetTimeout%0A%20%20%20%20%20%20clearTimeout%20%40scrollToTargetTimeout%0A%20%20%20%20%20%20%40scrollToTargetTimeout%20%3D%20null%0A%20%20%20%20%40scrollToTarget()%0A%20%20%20%20return%0A%0A%20%20beforeRoute%3A%20(context)%20%3D%3E%0A%20%20%20%20%40cacheScrollPosition()%0A%20%20%20%20%40routeCtx%20%3D%20context%0A%20%20%20%20%40scrollToTargetTimeout%20%3D%20%40delay%20%40scrollToTarget%0A%20%20%20%20return%0A%0A%20%20cacheScrollPosition%3A%20-%3E%0A%20%20%20%20return%20if%20not%20%40routeCtx%20or%20%40routeCtx.hash%0A%20%20%20%20return%20if%20%40routeCtx.path%20is%20'%2F'%0A%0A%20%20%20%20unless%20%40scrollMap%5B%40routeCtx.state.id%5D%3F%0A%20%20%20%20%20%20%40scrollStack.push%20%40routeCtx.state.id%0A%20%20%20%20%20%20while%20%40scrollStack.length%20%3E%20app.config.history_cache_size%0A%20%20%20%20%20%20%20%20delete%20%40scrollMap%5B%40scrollStack.shift()%5D%0A%0A%20%20%20%20%40scrollMap%5B%40routeCtx.state.id%5D%20%3D%20%40scrollEl.scrollTop%0A%20%20%20%20return%0A%0A%20%20afterRoute%3A%20(route%2C%20context)%20%3D%3E%0A%20%20%20%20if%20route%20!%3D%20'entry'%20and%20route%20!%3D%20'type'%0A%20%20%20%20%20%20resetFavicon()%0A%0A%20%20%20%20switch%20route%0A%20%20%20%20%20%20when%20'root'%0A%20%20%20%20%20%20%20%20%40show%20%40rootPage%0A%20%20%20%20%20%20when%20'entry'%0A%20%20%20%20%20%20%20%20%40show%20%40entryPage%0A%20%20%20%20%20%20when%20'type'%0A%20%20%20%20%20%20%20%20%40show%20%40typePage%0A%20%20%20%20%20%20when%20'settings'%0A%20%20%20%20%20%20%20%20%40show%20%40settingsPage%0A%20%20%20%20%20%20when%20'offline'%0A%20%20%20%20%20%20%20%20%40show%20%40offlinePage%0A%20%20%20%20%20%20else%0A%20%20%20%20%20%20%20%20%40show%20%40staticPage%0A%0A%20%20%20%20%40view.onRoute(context)%0A%20%20%20%20app.document.setTitle%20%40view.getTitle%3F()%0A%20%20%20%20return%0A%0A%20%20onClick%3A%20(event)%20%3D%3E%0A%20%20%20%20link%20%3D%20%24.closestLink%20%24.eventTarget(event)%2C%20%40el%0A%20%20%20%20if%20link%20and%20%40isExternalUrl%20link.getAttribute('href')%0A%20%20%20%20%20%20%24.stopEvent(event)%0A%20%20%20%20%20%20%24.popup(link)%0A%20%20%20%20return%0A%0A%20%20onAltF%3A%20(event)%20%3D%3E%0A%20%20%20%20unless%20document.activeElement%20and%20%24.hasChild%20%40el%2C%20document.activeElement%0A%20%20%20%20%20%20%40find('a%3Anot(%3Aempty)')%3F.focus()%0A%20%20%20%20%20%20%24.stopEvent(event)%0A%0A%20%20findTargetByHash%3A%20(hash)%20-%3E%0A%20%20%20%20el%20%3D%20try%20%24.id%20decodeURIComponent(hash)%20catch%0A%20%20%20%20el%20or%3D%20try%20%24.id(hash)%20catch%0A%20%20%20%20el%0A%0A%20%20isExternalUrl%3A%20(url)%20-%3E%0A%20%20%20%20url%3F%5B0..5%5D%20in%20%5B'http%3A%2F'%2C%20'https%3A'%5D%0A)

I get this output:

```
AddVariableDeclarationsStage failed to parse: Unexpected token (4:0)
  2 |   constructor(...args) {
  3 |     this.scrollToTop = this.scrollToTop.bind(this);
> 4 | ,    this.scrollToBottom = this.scrollToBottom.bind(this);
    | ^
  5 | ,    this.scrollStepUp = this.scrollStepUp.bind(this);
  6 | ,    this.scrollStepDown = this.scrollStepDown.bind(this);
```

**Comment by eventualbuddha** [comment]
Reduced version:

```coffee
class A
  a: =>
  b: =>
```

([REPL](https://decaffeinate-project.org/repl/#?useCS2=false&useJSModules=false&loose=false&optionalChaining=false&evaluate=false&stage=full&code=class%20A%0A%20%20a%3A%20%3D%3E%0A%20%20b%3A%20%3D%3E))

Thanks for reporting this! Definitely seems like a bug. I'm not sure what's putting that extra comma in there, but I'll take a look.
