### ISSUE TITLE
error converting multi line single/double quoted strings. 

### ISSUE THREAD

**Issue by iainb** [decaffeinate/decaffeinate#220]
example code that causes decaffeinate to crash:
```coffeescript
x = "double quoted
     multi line string"
```
becomes the following when converted to js
```js
var x;

x = "doube quoted multi line string";
```

decaffeinate leaves the new line in place and produces invalid code, from memory (when debugging) something similar to this:
```es6
let x = "double quoted
    multi line string"
```
possibly related issue in coffee-lex: https://github.com/decaffeinate/coffee-lex/issues/6

**Comment by alangpierce** [comment]
Looks like this was fixed by https://github.com/decaffeinate/decaffeinate/commit/981c44ee6311e83e906e2512ec399d4cc2325274 , so should be safe to close.
