### ISSUE TITLE
String.replace() in template-interpolation makes decaffeinate crash

### ISSUE THREAD

**Issue by madskonradsen** [decaffeinate/decaffeinate#229]
The following line crashes decaffeinate:

```coffee
"something.#{someString.replace("{{", "").replace("}}", "")}"
```

Even though it does look a bit nasty, it is valid coffeescript.

EDIT: At first i thought it was just REPL, but it also makes $ decaffeinate go crazy.

**Comment by Eden-Sun** [comment]
Wow , it loops .  How did find this example.

**Comment by eventualbuddha** [comment]
I'll leave this open to track the fix in decaffeinate, but the bug is in decaffeinate-parser. See https://github.com/decaffeinate/decaffeinate-parser/issues/14.

**Comment by madskonradsen** [comment]
@Eden-Sun Hah, i found it in some code i had lying around... It ain't pretty...

**Comment by lee-houghton** [comment]
A couple more examples from #287 (in case they're not the same thing).

```coffee
"#{f(x + "abc")}"
```

This syntax error also seems to cause it.
```coffee
"#{'b}"
```
