### ISSUE TITLE
Error involving nested object literals in a function call

### ISSUE THREAD

**Issue by NMandapaty** [decaffeinate/decaffeinate#235]
This is a very specific issue I ran into today. I found that if you include the parentheses for a function call _and_ exclude the brackets on the _inner_ object literal, decaffeinate will crash.
```
$ cat test1.coffee
fn(prop1: {prop2: val})
$ decaffeinate test1.coffee
test1.coffee → test1.js
$
$ cat test2.coffee
fn prop1: prop2: val
$ decaffeinate test2.coffee
test2.coffee → test2.js
$ 
$ cat testfails.coffee
fn(prop1: prop2: val)
$ decaffeinate testfails.coffee
testfails.coffee → testfails.js
/usr/local/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:9025
        throw err;
              ^
SyntaxError: Unexpected token (1:23)
...
```

**Comment by madskonradsen** [comment]
Hmmm... it actually looks like this work now? Apart from that it ads a newline before the closing curly-braces?

**Comment by madskonradsen** [comment]
...and now that kink is even ironed out... for sure fixed :)

**Comment by alangpierce** [comment]
Yep, this seems to be fixed: [repl](http://decaffeinate-project.org/repl/#?evaluate=false&stage=full&code=fn(prop1%3A%20prop2%3A%20val)).
