### ISSUE TITLE
Unexpected literal: "debugger" ?

### ISSUE THREAD

**Issue by nickperkinslondon** [decaffeinate/decaffeinate#2393]
x = 1
debugger
x = 2

Unexpected literal: {"value":"debugger","locationData":{"first_line":1,"first_column":0,"last_line":1,"last_column":7}}

Why does this happen?  This is valid coffeescript!

**Comment by eventualbuddha** [comment]
It’s the `debugger` statement. Somehow I guess I never properly added support for it! Amazing. Anyway, it’ll be fixed in the next release. Thanks for filing the issue!
