### ISSUE TITLE
Option to wrap decaffeinate output in IIFE

### ISSUE THREAD

**Issue by svicalifornia** [decaffeinate/decaffeinate#2412]
I have a feature request.

There should be an option `--iife` to wrap decaffeinate's code output (below the decaffeinate suggestions comment, if any) in an IIFE. The CoffeeScript compiler wraps its JS output in an IIFE, and decaffeinate should too, or at least there should be an option to do so automatically.

**Comment by eventualbuddha** [comment]
I'm curious in what context you're using decaffeinate that this makes sense. The intention is to use decaffeinate to replace your CoffeeScript code with modern JavaScript such that _you no longer have CoffeeScript_. It's still assumed that you're running in NodeJS or otherwise have a build toolchain that bundles for the browser. What's your build setup?

**Comment by svicalifornia** [comment]
Back when CoffeeScript was more popular, NodeJS and CommonJS imports and exports were not nearly as common as they are today. Lots of CoffeeScript projects use older build pipelines with gulp, grunt, Middleman, Sprockets, or other such tools, which simply run the CoffeeScript compiler on each `.coffee` file and concatenate the output. This was possible because the CoffeeScript compiler wrapped each module's compiled JS in an IIFE, preventing modules from clobbering each other's variables. Each module exposes its exports to the global scope by assigning to `window.<whatever>` — usually to a project-specific namespace that is known not to collide with other global variables.

Because it was so common in the early 2010's for JS modules to be combined in this way (either in the build process or later in the browser itself), @jashkenas (the creator of CoffeeScript) decided that each module's output should automatically be wrapped in an IIFE, so that CoffeeScript developers wouldn't need to worry about doing it themselves.

Just to be clear, here's an example CoffeeScript file, `test.coffee`:

```coffeescript
a = 1
```

If I run `coffee -c test.coffee`, it will write the following JS to output file `test.js`:

```js
(function() {
  var a;

  a = 1;

}).call(this);
```

The CoffeeScript compiler wraps the output in an IIFE, so that if it gets concatenated or otherwise combined in a global scope with other modules, they won't clobber each other. This is an *intentional feature of CoffeeScript,* yet for some reason **decaffeinate doesn't do that,** which means that **decaffeinate is functionally inconsistent with the CoffeeScript compiler** and therefore **functionally incorrect.**

Since decaffeinate doesn't use IIFEs, I have to manually edit its output to add the IIFE to each and every JS file it outputs, or write a script or build step to do it — all of which is frankly pretty stupid, when decaffeinate should be doing that itself to produce a functionally equivalent result to the CoffeeScript compiler.

Sure, it would be nice to rewrite all the JS output of decaffeinate to use CommonJS `export` or `module.exports`, but for large projects, that's a heavy investment that makes it harder to get management buy-in on the Coffee-to-JS effort. And it's totally unnecessary work — the existing build chains work with concatenated IIFEs from the CoffeeScript compiler. The problem is that decaffeinate isn't actually outputting valid CoffeeScript-compatible output, because it's not wrapping its output in IIFEs.

Furthermore, I understand that decaffeinate has been around for a while now, so I'm not asking for its inconsistent behavior to be changed in its default usage. However, it's not at all unreasonable to ask for an `--iife` option to make decaffeinate output functionally equivalent code to the CoffeeScript compiler's output, which is what decaffeinate really should be able to do if it claims to be a valid CoffeeScript transpiler.

So, can we get on to discussing how and when this issue can be addressed and solved?

**Comment by svicalifornia** [comment]
I don't want to keep the `.coffee` files. I want to run decaffeinate (once) on an old CoffeeScript project and turn all the CoffeeScript into JS, then never use CoffeeScript (or decaffeinate) on that project again.

But I shouldn't have to rewrite all that JS to use CommonJS exports at the same time. That would turn a 30-minute conversion and code review task into a multi-week project, as well as greatly increasing the risk, which would make management nix the whole idea.

If decaffeinate would output an IIFE for each module (like the CoffeeScript compiler does), then we can keep the project's same old JS concatenation buildchain and just rip out the CoffeeScript compile step. Quick and easy to do, and easy to sell to management.

**Comment by svicalifornia** [comment]
And in case you're wondering about the benefits of merely moving from CoffeeScript to JS, but not all the way to CommonJS, here are a few:

* Empowering JS devs who don't know CoffeeScript to read and work on that project
* Enabling IDE code completion, highlighting, and static checking (e.g. VS Code Intellisense)
* Supporting other tools (e.g. code coverage) that work on JS but not on CoffeeScript

Of course, over a longer timeline, we would continue to refactor the JS modules and migrate them to CommonJS conventions, Webpack/Vite, and TypeScript. But we shouldn't need to do that all at once — hence IIFEs are the first step.
