### ISSUE TITLE
support for .vue files?

### ISSUE THREAD

**Issue by robguthrie** [decaffeinate/decaffeinate#2478]
Hello, I've got a fairly large project that uses coffeescript with vue.js. 

We have a lot of component files that look like this:
https://github.com/loomio/loomio/blob/master/vue/src/components/thread/preview.vue

Do you have any suggestions for how I might go about replacing the coffee in these files with JS?

Thank you

**Comment by eventualbuddha** [comment]
You could write a wrapper around `decaffeinate` that uses it as a library. You'd want some sort of HTML parser (maybe whatever Vue uses?) that can find `script[type="coffee"]` and replace the contents with the decaffeinate-converted JS.

**Comment by robguthrie** [comment]
Yea, thanks for considering my question! I think that I might just start manually decaffeinating files as I work on them.
