### ISSUE TITLE
Destructuring and assigning to `this` is incorrect

### ISSUE THREAD

**Issue by bioball** [decaffeinate/decaffeinate#251]
This snippet:

```coffee
foo = ({ @bar, @baz }) ->
```

Should transpile to this:

```js
let foo = function({ bar, baz }) {
  this.bar = bar;
  this.baz = baz;
  return;
};
```

The actual output is:

```js
let foo = function({ bar1, baz1 }) {
  this.bar = bar;
  this.bar = bar1;
  this.baz = baz;
  this.baz = baz1;
  return;
};
```

This will throw a `ReferenceError` because `bar` and `baz` don't exist. Also, the keys matched to the destructuring call should be kept as `bar` and `baz`.

**Comment by madskonradsen** [comment]
Isn't this a duplicate of #213 ? :)

**Comment by bioball** [comment]
Ah, yes. I'll close this one, then.
