### ISSUE TITLE
Destructuring assignment in function doesn't compile at all

### ISSUE THREAD

**Issue by edi9999** [decaffeinate/decaffeinate#254]
```
class TableManager
  constructor:(@tables=@tables)->
    console.log(1)
```

gives an error.

**Comment by madskonradsen** [comment]
Dupe of #232 ?

**Comment by alangpierce** [comment]
Looks like this is fixed now: [repl](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=class%20TableManager%0A%20%20constructor%3A(%40tables%3D%40tables)-%3E%0A%20%20%20%20console.log(1))
