### ISSUE TITLE
expected IF token at start of conditional, but got IDENTIFIER

### ISSUE THREAD

**Issue by niieani** [decaffeinate/decaffeinate#275]
Breaking example:

```coffee
extraFunctions =
  addExt: (file, ext) ->
    if not ext
      file
    else
      ext = '.' + ext if ext[0] isnt '.'             # this is the offending line
      file + if _.endsWith(file, ext) then '' else ext
```

Interestingly, the offending line compiles on its own:

```coffee
ext = '.' + ext if ext[0] isnt '.'
```

but breaks when in context of the `else`

**Comment by eventualbuddha** [comment]
This happens because `ConditionalPatcher` checks to see whether the body of the alternate is a `Conditional` and, if it is, assumes it needs to create an `else if` in the output. The trouble is it's ignoring the newline token after the `else` that should tell it that it's not an `else if`.

**Comment by madskonradsen** [comment]
Looks like it have been fixed :)

**Comment by niieani** [comment]
Does look that way.
