### ISSUE TITLE
Feature request: force emit broken code

### ISSUE THREAD

**Issue by niieani** [decaffeinate/decaffeinate#277]
Since decaffeinate isn't yet feature complete, it would be good to have a fallback in case of errors or unsupported features.

The fallback could be to try and replace the line containing the unsupported code with a dummy statement and retry compilation, leaving together a comment with the original CoffeeScript code in its place. 
This would arguably make decaffeinate much more useful, by making it easy to convert whole code-bases and then manually going through the files to correct the remaining problems. Right now that process is manual and requires decaffeinating files one-by-one, trying to comment out and/or replace statements -- until things work. :D

**Comment by alangpierce** [comment]
It seems like there are enough distinct types of errors that it would be really hard to always have a good fallback. For example, if an intermediate step accidentally outputs unbalanced parens, it's not obvious what later stages could do or what could be modified in the original code to make the transform work. But I bet this could be done for the most common unimplemented features.

A similar idea is that if a missing feature is hard to make 100% correct, decaffeinate could emit a rough version of the new code with a TODO comment to make sure it's actually right, or something like that. Although it's hard to say if I prefer that or the safer approach of decaffeinate failing.

FWIW, I've been using decaffeinate with a wrapper script that makes the "fix existing files to be decaffeinate-friendly" workflow a bit easier, at least in my codebase. I add a bunch of paths to a `files_to_decaffeinate.txt` file and it does a dry run of all of those files and tells me which ones failed, and provides an option to open each one in the repl. I can then tweak the coffeescript until all files are decaffeinate-compatible, then run decaffeinate and a few follow-up scripts. So if we want to make decaffeinate more useful even with missing features, another approach may be to make it easier to identify and fix CoffeeScript code to work around those missing features. That's what I was going for with #272 and #278.

**Comment by alangpierce** [comment]
Closing this out since I think decaffeinate is stable enough there aren't any areas where it's reasonable to have a fallback. Most the remaining issues are things like unbalanced parens, and it's very hard to "continue anyway" in that case since the parser in the next stage will crash. Of course, for any really tricky one-off bugs, decaffeinate can still try to be as helpful as possible as an intermediate step before the bug is fixed.

**Comment by niieani** [comment]
Good call, too much effort vs the benefit. Great work!
