### ISSUE TITLE
Show the full context when reporting errors in the repl

### ISSUE THREAD

**Issue by alangpierce** [decaffeinate/decaffeinate#278]
I recently made it so errors like "Unexpected token" show the full context in the CLI, but it turns out the repl just takes `error.message` rather than pretty-printing the error. It would be especially nice to have the full context in the repl to make it easy to quickly go through a file and make it decaffeinate-friendly.

I have two PRs for this coming up soon, just filing this issue for tracking. Here's a sneak peek:
http://www.alangpierce.com/decaffeinate/repl/#?evaluate=true&code=(a)%20-%3E%0A%20%20(a%20not%20in%20b.map(a%2C%20(e)%20-%3E%20%0A%20%20%20%20e)%0A%20%20)

**Comment by niieani** [comment]
Fantastic job!

**Comment by eventualbuddha** [comment]
Nice! Looking forward to the PRs!

**Comment by eventualbuddha** [comment]
… which I see you already submitted. Will look soon!

**Comment by alangpierce** [comment]
Fixed with https://github.com/decaffeinate/decaffeinate/commit/d77ebba2e88d594eed00516281fe33980b660e84 and https://github.com/decaffeinate/decaffeinate/commit/e10504110a5f16111a1851127545338a151ba9b9.
