### ISSUE TITLE
Provide sample CoffeeScript in repl when no query string exists

### ISSUE THREAD

**Issue by eventualbuddha** [decaffeinate/decaffeinate#285]
Probably code taken from CoffeeScript.org

**Comment by madskonradsen** [comment]
I believe this have been fixed :)

**Comment by alangpierce** [comment]
Looks like it shows the sample code for a split second when loading existing code in the repl, which would be nice to fix.

![visual_issue](https://cloud.githubusercontent.com/assets/211605/16696322/3d0a9368-44f9-11e6-8cf7-c21130dc1449.gif)
