### ISSUE TITLE
Infinite loop with interpolated strings

### ISSUE THREAD

**Issue by lee-houghton** [decaffeinate/decaffeinate#287]
Try typing this into the decaffeinate repl. You'll see that it hangs.

```coffee
"#{f(x + "abc")}"
```

This syntax error also seems to cause it.
```coffee
"#{'b}"
```

**Comment by madskonradsen** [comment]
Might be related to #229

**Comment by lee-houghton** [comment]
Hmm, it looks pretty likely that it is. I've added the examples I found to that ticket so that they can be tested against any fixes. I don't see any point keeping this ticket open.
