### ISSUE TITLE
operators priorities

### ISSUE THREAD

**Issue by Eden-Sun** [decaffeinate/decaffeinate#291]
here show a simple demo 
http://decaffeinate-project.org/repl/#?evaluate=true&code=console.log%200xff%20%5E%200x1%20%26%200xf%0Aconsole.log%20%600xff%20%5E%200x1%20%26%200xf%60

**Comment by eventualbuddha** [comment]
Yikes, I was afraid of this. We should incorporate [this table](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence) to determine whether it's safe to add parentheses and how.

**Comment by alangpierce** [comment]
A similar issue I just ran into: `true or false and false`. In JS, `&&` binds tighter than `||`, so the whole thing is supposed to evaluate to `true`, and does in CoffeeScript, but after decaffeinate parens are incorrectly added. Annoyingly, the CoffeeScript parser views it as `(true or false) and false`, but just happens to not add parens, so JS can correctly parse it later.

[decaffeinate repl](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=console.log%20true%20or%20false%20and%20false)
[CoffeeScript repl](http://coffeescript.org/#try:console.log(true%20or%20false%20and%20false))

One approach is to avoid adding parens in decaffeinate, but I think another possible approach is to try to fix the CoffeeScript parser to use the right precedence rules. It looks like grammar.coffee in the CoffeeScript source code already defines some precedence rules, so this may just be a matter of fixing some bugs in that.
