### ISSUE TITLE
In classes, prototype properties transpile wrong AND local vars fail with no so great message.

### ISSUE THREAD

**Issue by anodynos** [decaffeinate/decaffeinate#293]
``` coffeescript
class Animal extends Lifeform  
  #varLocalToClass = 1            # fails to transpile 
  aPrototypeProperty: 'value'    # wrong intepretation
  instanceMethod: (arg1, @storeInThis, splat...) -> 'returnValue' # OK
```

becomes

``` ES6
class Animal extends Lifeform {  
  //varLocalToClass = 1              // fails to transpile with 
            // "expected a colon between the key and expression of a class property"
  aPrototypeProperty = 'value';   // wrong intepretation, 
           // Its not a local variable but a prototype property. 
           // Also it isn't actually valid ES6, local variables inside a class aren't allowed. 
  instanceMethod(arg1, storeInThis, ...splat) { this.storeInThis = storeInThis; return 'returnValue'; } // OK
}
```

Also, please check my https://github.com/jashkenas/coffeescript/issues/4078#issuecomment-231439273 comment.

**Comment by alangpierce** [comment]
I've run into the class properties issue as well. My impression was that it was that decaffeinate was converting the code to class fields as described in this stage 1 proposal: https://github.com/jeffmo/es-class-fields-and-static-properties .

However, using stage 1 features is a little risky and the semantics aren't quite the same, so it was causing problems for me, particularly in Backbone classes. The implementation in the proposal assigns properties to instances after the constructor finishes, whereas coffeescript assigns them to the prototype.

More info here:
http://benmccormick.org/2015/04/07/es6-classes-and-backbone-js/
http://benmccormick.org/2015/07/06/backbone-and-es6-classes-revisited/

I think a good alternative is to write the code to put the properties on the prototype, maybe in a static method so it can still be at the top of the class. But I imagine that keeping comments and formatting intact may be a pain.

**Comment by eventualbuddha** [comment]
> I think a good alternative is to write the code to put the properties on the prototype, maybe in a static method so it can still be at the top of the class. But I imagine that keeping comments and formatting intact may be a pain.

This is a good example of preserving semantics versus converting to code that you would actually write by hand. Unless I was forced somehow, I wouldn't write a `class` followed by a property set on its prototype. However, as you pointed out, CoffeeScript uses prototype properties.

The local variable inside the class block is actually worse, as it maps well to the IIFE that CoffeeScript generates but not at all to ES6 classes. As a result, the right thing to do there is probably to have alternate versions of of the class patchers that generate `function Foo` and `Foo.prototype.bar = …`. I would be happy to provide guidance and review a PR for such a feature.

**Comment by alangpierce** [comment]
Closing now that #466 has landed. The example now gets converted to correct code (although it could be made prettier with more work or an option to use JS class fields).
