### ISSUE TITLE
Add support for %%

### ISSUE THREAD

**Issue by alangpierce** [decaffeinate/decaffeinate#303]
e.g. `a %% b`

http://decaffeinate-project.org/repl/#?evaluate=true&code=a%20%25%25%20b

Currently it gives the error "cannot traverse unknown node type: ModuloOp".

**Comment by eventualbuddha** [comment]
This needs to be added in two places to be traversed properly, unfortunately. Both in [traverse.js](https://github.com/decaffeinate/decaffeinate/blob/master/src/utils/traverse.js) and decaffeinate-traverse.

To write the actual patcher, we might do best just to follow CoffeeScript's lead and [emit a helper function](http://coffeescript.org/#try:A()%20%25%25%20b). See [`InOpPatcher`](https://github.com/decaffeinate/decaffeinate/blob/master/src/stages/main/patchers/InOpPatcher.js) for an example.

**Comment by alangpierce** [comment]
Cool, thanks for the pointers, I'll try that.
