### ISSUE TITLE
Unable to have an if statement with empty branch

### ISSUE THREAD

**Issue by thebanjomatic** [decaffeinate/decaffeinate#305]
I have encountered this pattern in my code once or twice, but I just ran into this issue again when trying to come up with a minimum reproducer for another issue.

```coffee
if someCondition
   # intentionally blank
else
   doSomething()
```

Produces the following error:
```
Cannot read property 'contentStart' of null
> 1 | if someCondition
> 2 |    # intentionally blank
> 3 | else
> 4 |    doSomething()
```

[REPL Reproducer](http://decaffeinate-project.org/repl/#?evaluate=true&code=if%20someCondition%0D%0A%20%20%20%23%20intentionally%20blank%0D%0Aelse%0D%0A%20%20%20doSomething())

**Comment by eventualbuddha** [comment]
[`ConditionalPatcher`](https://github.com/decaffeinate/decaffeinate/blob/df5c240b1435d99854c72563532380d1ce0e8736/src/stages/main/patchers/ConditionalPatcher.js) needs to account for `consequent` being `null`. Currently it assumes that can't happen.
