### ISSUE TITLE
Default parameters value semantic mismatch in ES6

### ISSUE THREAD

**Issue by an-sh** [decaffeinate/decaffeinate#312]
```coffeescript
fn = (x=1) ->
  console.log x # 1

fn(null)
```

```javascript
let fn = (x=1) => console.log(x); // null

fn(null);
```

This compiles without warning, but in ES6 only `undefined` triggers the default value assignment. Could it emit a warning during conversion? Or probably has some configuration options?

**Comment by Eden-Sun** [comment]
same #125

**Comment by eventualbuddha** [comment]
As @Eden-Sun points out, this is a duplicate. I think a warning is appropriate in such a case. For configuration options, what would you expect to see? Perhaps `defaultParam: 'es6' | 'es5'`?
