### ISSUE TITLE
Repeated var declarations at inner scopes

### ISSUE THREAD

**Issue by avonwyss** [decaffeinate/decaffeinate#316]
I'm not sure if this behavior is "by design", but it is against best practices (triggers warnings in static code analysis tools) and also not as CoffeeScript does it.
([repl](http://decaffeinate-project.org/repl/#?evaluate=true&code=fn%20%3D%20%28a%2C%20b%29%20-%3E%0D%0A%20%20if%20%28a%29%0D%0A%20%20%20%20if%20%28b%29%0D%0A%20%20%20%20%20%20r%20%3D%200%0D%0A%20%20%20%20else%0D%0A%20%20%20%20%20%20r%20%3D%201%0D%0A%20%20else%0D%0A%20%20%20%20r%20%3D%202%0D%0A%20%20return%20r%0D%0A))

``` coffee
fn = (a, b) ->
  if (a)
    if (b)
      r = 0
    else
      r = 1
  else
    r = 2
  return r
```

decaffeniate re-declares the return variable `r` on each "first" occurence in an inner scope, instead of generating one `var` (or even better, `let`) at the outmost scope where the variabler is used.

``` js
let fn = function(a, b) {
  if (a) {
    if (b) {
      var r = 0;
    } else {
      var r = 1;
    }
  } else {
    var r = 2;
  }
  return r;
};
```

This is different from the original CoffeeScript which does generate this code:

``` js
var fn;
fn = function(a, b) {
  var returnValue;
  if (a) {
    if (b) {
      returnValue = item[0];
    } else {
      returnValue = item[1];
    }
  } else {
    returnValue = item[2];
  }
  return returnValue;
};
```

**Comment by eventualbuddha** [comment]
I created https://github.com/eventualbuddha/add-variable-declarations/issues/8 to track this in the library responsible for this behavior. I probably won't have time for this in the near future, but I'd review a PR 😉
