### ISSUE TITLE
Wrong behavior when using a range with "by" in a "for in" loop

### ISSUE THREAD

**Issue by alangpierce** [decaffeinate/decaffeinate#322]
It looks like when you loop over a range and use the `by` keyword, that forces the direction of the iteration, rather than the direction being decided based on whether the range goes forward or backward. This is useful to avoid a gotcha where iterating over `[1..0]` ends up iterating over 1 and then 0. However, decaffeinate ignores this behavior and just computes the range first, then loops over it like normal.

Here's a simple example:

``` coffee
for a in [1..0] by 1
  b()
```

([decaffeinate repl](http://decaffeinate-project.org/repl/#?evaluate=true&code=for%20a%20in%20%5B1..0%5D%20by%201%0A%20%20b%28%29))
([coffeescript repl](http://coffeescript.org/#try:for%20a%20in%20%5B1..0%5D%20by%201%0A%20%20b%28%29))

The correct behavior is to do nothing, but the decaffeinate output loops over 1 and then 0.

Here's a more realistic example with the same problem (which is in the same form as some code I actually ran into):

``` coffee
for a in [1..len-1] by 1
  b()
```

([decaffeinate repl](http://decaffeinate-project.org/repl/#?evaluate=true&code=for%20a%20in%20%5B1..len-1%5D%20by%201%0A%20%20b%28%29))
([coffeescript repl](http://coffeescript.org/#try:for%20a%20in%20%5B1..len-1%5D%20by%201%0A%20%20b%28%29))

**Comment by eventualbuddha** [comment]
Related, decaffeinate shouldn't even generate the range in most of these cases.

**Comment by eventualbuddha** [comment]
@alangpierce can you confirm this is working for you now?

**Comment by Eden-Sun** [comment]
It does.

**Comment by alangpierce** [comment]
Yep, looks good to me! Closing.
