### ISSUE TITLE
Error with object literals where name of key and value are the same

### ISSUE THREAD

**Issue by thebanjomatic** [decaffeinate/decaffeinate#325]
decaffeinate is crashing on my CoffeeScript input:

```coffee
points.push {x:x, y:y}
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&code=points.push%20%7Bx%3Ax%2C%20y%3Ay%7D%0A)

I get this error:

```
Cannot overwrite a zero-length range – use insertLeft or insertRight instead
```

The shorthand form works correctly:
```coffee 
points.push {x, y}
```

**Comment by eventualbuddha** [comment]
Fixed in v2.17.5.
