### ISSUE TITLE
POST-`for-in` expression with implicit function call crashes

### ISSUE THREAD

**Issue by eventualbuddha** [decaffeinate/decaffeinate#333]
decaffeinate is crashing on my CoffeeScript input:

``` coffee
(a for a in b c)
```

([repl](http://decaffeinate-project.org/repl/#?evaluate=true&code=%28a%20for%20a%20in%20b%20c%29))

I get this error:

```
unexpected ')' at 22
```

The fix for this is probably similar to https://github.com/decaffeinate/decaffeinate/pull/330.

**Comment by niieani** [comment]
I'm actually getting: 

```
unexpected then
```

With this code:

```coffee
(b for b in (c))
```
http://decaffeinate-project.org/repl/#?evaluate=false&code=(b%20for%20b%20in%20(c))

**Comment by madskonradsen** [comment]
Looks like the initial issue have been fixed, but @niieani 's issue does still exist

**Comment by alangpierce** [comment]
Great, thanks for calling that out. I guess we should keep this open track the other issue. I haven't looked at it too deeply, but I suspect that the original issue was fixed with https://github.com/Rich-Harris/magic-string/pull/89 .
