### ISSUE TITLE
Switch statements with empty cases cause a crash

### ISSUE THREAD

**Issue by alangpierce** [decaffeinate/decaffeinate#340]
For example, this code:

```coffee
switch a
  when b then
    # Do nothing
  else
    null
```

breaks with this error:

```
Cannot read property 'outerStart' of null
  1 | switch a
> 2 |   when b then
    |   ^^^^^^
  3 |     # Do nothing
  4 |   else
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&code=switch%20a%0A%20%20when%20b%20then%0A%20%20%20%20%23%20Do%20nothing%0A%20%20else%0A%20%20%20%20null)

Looks like the code in `SwitchCasePatcher` is assuming that `this.consequent` is non-null. One other issue that I noticed is that the `then` token is after `this.outerEnd` for `SwitchCasePatcher`, which makes it harder to find and remove it.

**Comment by madskonradsen** [comment]
Probably not directly related, but the same issue of assuming that `this.consequent` can't be null is present in #305 :)
