### ISSUE TITLE
`in` with single-element literal array can be simplified

### ISSUE THREAD

**Issue by eventualbuddha** [decaffeinate/decaffeinate#347]
decaffeinate is producing the wrong JavaScript based on my CoffeeScript input:

``` coffee
a() in [b]
```

[repl](http://decaffeinate-project.org/repl/#?evaluate=false&code=a%28%29%20in%20%5Bb%5D)

I get this output:

``` js
let ref;
(ref = a()) === b;
```

Here's what I expect it to be instead:

``` js
a() === b;
```

**Comment by Eden-Sun** [comment]
Isn't this too miner ? The evaluation is correct.

**Comment by alangpierce** [comment]
After #508 this is obsolete since `in` patching no longer uses `makeRepeatable`. The output `[b].includes(a())` is a little strange, but no stranger than the original CoffeeScript.
