### ISSUE TITLE
"for" with square brackets causes "Unexpected token"

### ISSUE THREAD

**Issue by evmorov** [decaffeinate/decaffeinate#351]
decaffeinate is crashing on my CoffeeScript input:

```coffee
arr = [1, 5, 10, 20]
console.log (i for i in arr when i % 2 is 0)[0]
```

http://decaffeinate-project.org/repl/#?evaluate=true&code=arr%20%3D%20%5B1%2C%205%2C%2010%2C%2020%5D%0Aconsole.log%20(i%20for%20i%20in%20arr%20when%20i%20%25%202%20is%200)%5B0%5D

I get this error:

```
AddVariableDeclarationsStage failed to parse: Unexpected token (2:13)
```

Version: decaffeinate@2.19.5

**Comment by alangpierce** [comment]
This seems to be working now.
