### ISSUE TITLE
the error

### ISSUE THREAD

**Issue by roughsoft** [decaffeinate/decaffeinate#360]
```
class QueryRange
  @infinite: ->
    return new QueryRange({limit: null, offset: null})

  @rangeWithUnion: (a, b) ->
    return QueryRange.infinite() if a.isInfinite() or b.isInfinite()
    if not a.isContiguousWith(b)
      throw new Error('You cannot union ranges which do not touch or intersect.')

    new QueryRange
      start: Math.min(a.start, b.start)
      end: Math.max(a.end, b.end)

  @rangesBySubtracting: (a, b) ->
    return [] unless b

    if a.isInfinite() or b.isInfinite()
      throw new Error("You cannot subtract infinite ranges.")

    uncovered = []
    if b.start > a.start
      uncovered.push new QueryRange({start: a.start, end: Math.min(a.end, b.start)})
    if b.end < a.end
      uncovered.push new QueryRange({start: Math.max(a.start, b.end), end: a.end})
    uncovered


  Object.defineProperty @prototype, "start",
    enumerable: false
    get: -> @offset

  Object.defineProperty @prototype, "end",
    enumerable: false
    get: -> @offset + @limit

  constructor: ({@limit, @offset, start, end} = {}) ->
    @offset ?= start if start?
    @limit ?= end - @offset if end?
    throw new Error("You must specify a limit") if @limit is undefined
    throw new Error("You must specify an offset") if @offset is undefined

  clone: ->
    return new QueryRange({@limit, @offset})

  isInfinite: ->
    return @limit is null and @offset is null

  isEqual: (b) ->
    return @start is b.start and @end is b.end

  # Returns true if joining the two ranges would not result in empty space.
  # ie: they intersect or touch
  isContiguousWith: (b) ->
    return true if @isInfinite() or b.isInfinite()
    return @start <= b.start <= @end or @start <= b.end <= @end

  toString: ->
    "QueryRange{#{@start} - #{@end}}"

module.exports = QueryRange
```

**Comment by alangpierce** [comment]
Hi, thanks for the report, but it needs some more information to be useful:
* Can you say what error you saw?
* Try to avoid including code that's irrelevant to the error. You can do this using the repl at http://decaffeinate-project.org/repl/#?evaluate=true&code= . Paste the code into the left side, tweak the code until it's as small as possible while still demonstrating the error, then update the bug report to only have the small snippet of code that causes the problem. Also, the URL in the repl will update to a link that makes it easy to see the error in the repl, so it would be good if you included that link.
* Make sure the bug isn't a duplicate. There are already a number of bugs reported in the issues page.
* The code you pasted isn't formatted properly. Use markdown code blocks (\`\`\`) to have GitHub show an area of text as code.

**Comment by alangpierce** [comment]
Looks like the underlying issue here is the use of `Object.defineProperty` within a class. Currently, decaffeinate doesn't handle things other than methods within classes, which is discussed in https://github.com/decaffeinate/decaffeinate/issues/293 and https://github.com/decaffeinate/decaffeinate/issues/123 . Closing in favor of those.
