### ISSUE TITLE
Use Array.prototype.includes instead of an __in__ helper

### ISSUE THREAD

**Issue by alangpierce** [decaffeinate/decaffeinate#363]
Currently this code:

``` coffee
a in b
```

translates to:

``` js
__in__(a, b);
function __in__(needle, haystack) {
  return haystack.indexOf(needle) >= 0;
}
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&code=a%20in%20b)

But I think we could just translate it to `b.includes(a)`.

According to [this StackOverflow post](http://stackoverflow.com/questions/35370222/array-prototype-includes-vs-array-prototype-indexof), the only difference is when checking if `NaN` is in an array. It seems like this is an obscure enough case that we don't need to care about it, and probably any usage of `NaN` in existing code is a bug. And CoffeeScript already does some extra stuff where it works on array-like objects, not just objects with `indexOf`.

Another concern is that not everyone using modern JavaScript has a polyfill for `Array.prototype.includes`. It's in ES2016, so it's officially in JavaScript, but not in ES6. I think it probably makes sense to just say that it's a requirement for decaffeinate, but we could also have an option to generate strictly ES6 code if if causes trouble.

**Comment by thebanjomatic** [comment]
I have been manually replacing `__in__(needle, haystack)` with `_.contains(haystack, needle)` in my own code since we already have a dependency on lodash. It would be nice to be able to configure these helpers somehow, but that might be more work than its worth.

**Comment by alangpierce** [comment]
Yeah, agreed that making the helpers more configurable would be nice. I actually ran into exactly the same issue recently (replacing `__in__` with `_.contains`, since my codebase doesn't support `includes` yet). But it's hard to say exactly how a general solution would work. The configuration could get complicated if we wanted to be really flexible, and adding an import to underscore/lodash if necessary could be tricky, especially if we want to be careful about avoiding name clashes.

Another thought is that you could write a JS -> JS codemod (e.g. using jscodeshift) that you run afterward that gets rid of helpers and changes usages to use underscore. There are already a few cases where I do that kind of thing.

Still, in this specific case, I feel like `includes` is the way everyone's going to be doing it in the long run, so it would be nice to support that, maybe as the default.

**Comment by andrewaustin** [comment]
@alangpierce Would there be any interest in adding a feature flag to opt out of using .includes?

**Comment by alangpierce** [comment]
@andrewaustin yeah, seems reasonable. What's your use case, out of curiosity? Usually babel-polyfill makes it fairly easy to add it, but I guess in some situations like library code that's undesirable.

**Comment by alangpierce** [comment]
@andrewaustin I just filed #1102 to add an option to skip the .includes conversion.
