### ISSUE TITLE
Emits close-paren in the wrong place

### ISSUE THREAD

**Issue by madskonradsen** [decaffeinate/decaffeinate#370]
decaffeinate is crashing on my CoffeeScript input:

```coffee
define [
], () ->

  somefunc 'something', ['something', (ContactService) ->
  
  ]
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&code=define%20%5B%0A%5D%2C%20()%20-%3E%0A%0A%20%20somefunc%20'something'%2C%20%5B'something'%2C%20(ContactService)%20-%3E%0A%20%20%0A%20%20%5D)
I get this error:

```
AddVariableDeclarationsStage failed to parse: Unexpected token (6:5)
  4 |   return somefunc('something', ['something', function(ContactService) {}
  5 | 
> 6 |   ]);)
    |      ^
  7 | };```

**Comment by alangpierce** [comment]
Ugh, yeah, this type of problem seems to be one of the big remaining issues. I already changed the paren-adding process to happen in the NormalizeStage before most of the other work, but it might be best to isolate it even further or try some other approach that's more robust.

FYI, with these "misplaced parens" issues, you can usually tweak them to be decaffeinate-friendly by manually adding parens for implicit function calls (function calls that don't use parentheses). Here's the simple change that fixes this case: [repl](http://decaffeinate-project.org/repl/#?evaluate=true&code=define%20%5B%0A%5D%2C%20()%20-%3E%0A%0A%20%20somefunc('something'%2C%20%5B'something'%2C%20(ContactService)%20-%3E%0A%0A%20%20%5D)).
