### ISSUE TITLE
Extra dot operator being added in ||= expression with instance variable (causes Unexpected token in AddVariableDeclarationsStage)

### ISSUE THREAD

**Issue by rmacklin** [decaffeinate/decaffeinate#372]
decaffeinate is crashing on my CoffeeScript input:

```coffee
$el ||= @options
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&code=%24el%20%7C%7C%3D%20%40options%0A)

I get this error:

```
AddVariableDeclarationsStage failed to parse: Unexpected token (1:23)
> 1 | if (!$el) { $el = this..options };
    |                        ^
  2 | 
```

so it seems to be transforming to `this..options` rather than `this.options`.

**Comment by alangpierce** [comment]
Looks like this is fixed now.
