### ISSUE TITLE
`super` as sole argument to function causes crash

### ISSUE THREAD

**Issue by eventualbuddha** [decaffeinate/decaffeinate#375]
decaffeinate is crashing on my CoffeeScript input:

``` coffee
class A
  b: ->
    c(super)
```

([repl](http://decaffeinate-project.org/repl/#?evaluate=false&stage=full&code=class%20A%0A%20%20b%3A%20-%3E%0A%20%20%20%20c%28super%29))

I get this error:

```
cannot edit index 28 because it is not editable (i.e. outside [22, 27))
  1 | class A
  2 |   b: ->
> 3 |     c(super)
    |       ^^^^^
```

Originally from https://github.com/decaffeinate/decaffeinate/issues/310#issuecomment-236412146. Caused by https://github.com/decaffeinate/decaffeinate/pull/263.

**Comment by alangpierce** [comment]
Looks like this doesn't crash anymore, but the output it gives is incorrect:

```js
class A {
  b() {
    return c(super.b)(...arguments);
  }
}
```
