### ISSUE TITLE
Nested "if" expressions within a function call don't get transformed

### ISSUE THREAD

**Issue by alangpierce** [decaffeinate/decaffeinate#388]
decaffeinate is crashing on my CoffeeScript input:

```coffee
a(if b
    if c
      null)
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=a(if%20b%0A%20%20%20%20if%20c%0A%20%20%20%20%20%20null))

I get this error:

```
AddVariableDeclarationsStage failed to parse: Unexpected token (1:2)
> 1 | a(if b
    |   ^
  2 |     if c
  3 |       null);
```

**Comment by alangpierce** [comment]
This appears to hit the `// TODO: IIFE` case within the main stage `ConditionalPatcher`. I tried playing around with it, but couldn't get it to transform the nested statements correctly, so this may end up being more than just a bug fix. It looks like it's trying to handle the case where an `if` expression contains a complex block within it.

FWIW, CoffeeScript produces relatively good code here: `a(b ? c ? null : void 0 : void 0);`.

**Comment by jannehietamaki** [comment]
This doesn't need to be a function call. Nested if statements fail also when defining a variable:
```
c =
  if a
    x = 0
    x = x + 1 if b
    x
  else
    1
```

```
stdin: AddVariableDeclarationsStage failed to parse: Unexpected token (2:2)
 1 | c =
> 2 |   if a
    |   ^
  3 |     x = 0
  4 |     if b then x = x + 1
```

**Comment by alangpierce** [comment]
Yep, it's really when any `if` with enough complexity is used as an expression (as opposed to a statement).
