### ISSUE TITLE
"expected operator between binary operands" when using string interpolation

### ISSUE THREAD

**Issue by alangpierce** [decaffeinate/decaffeinate#389]
decaffeinate is crashing on my CoffeeScript input:

```coffee
"#{a}" + "#{b}"
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=%22%23%7Ba%7D%22%20%2B%20%22%23%7Bb%7D%22)

I get this error:

```
expected operator between binary operands
> 1 | "#{a}" + "#{b}"
    | ^^^^^
```

It looks like the problem is decaffeinate-parser isn't correctly recognizing the left side as a template literal, so a later stage is getting confused when it expects to find an actual `+` operator.

**Comment by madskonradsen** [comment]
I think this is actually a dupe of #194 :)

... and while we are at it, I think that #215 , #372 and #375 can be closed... :)

**Comment by alangpierce** [comment]
Thanks! Closing as duplicate. I also closed the first two bugs you pointed out, although looks like the third one still gives wrong output.
