### ISSUE TITLE
Escaping spaces before new-line in multi-line string not supported

### ISSUE THREAD

**Issue by kasbah** [decaffeinate/decaffeinate#406]
decaffeinate is producing the wrong JavaScript based on my CoffeeScript input:

``` coffee
a = "a\
b"
```

http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=a%20%3D%20%22a%5C%0Ab%22

I get this output:

``` js
let a = "a\ b";
```

Here's what I expect it to be instead:

``` js
let a = "a" 
+ "b"
```

**Comment by kasbah** [comment]
Semi related is:

```coffee
a = "b 
#{c}"
```
http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=a%20%3D%20%22b%20%0A%23%7Bc%7D%22

gives
```js
let a = `b 
${c}`;
```

but should be

```js
let a = `b ${c}`;
```

**Comment by alangpierce** [comment]
Thanks, looks like the second one is a separate issue will likely have a separate fix, so I'll file a different issue for that and this issue will be for the newline escaping issue.
