### ISSUE TITLE
Make require translation optional

### ISSUE THREAD

**Issue by kasbah** [decaffeinate/decaffeinate#407]
When targeting Node, which now supports most of ES6, people will want to stick with `require`. 

I have another use case which is for packaging a Firefox extension with JPM. I can't babel the resulting module code with the es2015 preset because that also translates the global `this` to `undefined`, but it is needed to get advanced extension functionality. I need to use the es2015-script preset but of course that doesn't translate `import` and `export`.

**Comment by alangpierce** [comment]
👍 another reason this might be preferable is that converting code to ES2015 modules is one of the more fragile pieces in decaffeinate and can cause correctness issues if you're not careful. The fix-imports step in [bulk-decaffeinate](https://github.com/alangpierce/bulk-decaffeinate) fixes inconsistencies with named/default exports, but another issue that imports are always evaluated first in a file, so converting `require` to `import` can change execution order.
