### ISSUE TITLE
Add option to customize when to add implicit returns

### ISSUE THREAD

**Issue by eventualbuddha** [decaffeinate/decaffeinate#409]
There are a number of places that can be determined ahead of time for a particular codebase to not need implicit returns. In Ember, for example, you almost never want implicit returns in actions:

``` coffee
# components/profile.coffee
module.exports = Ember.Component.extend
  actions:
    hello: (name) ->
      console.log("Hello", name)
```

This is what decaffeinate generates now:

``` js
export default Ember.Component.extend({
  actions: {
    hello(name) {
      return console.log("Hello", name);
    }
  }
});
```

But there's no reason to return in the `hello` action, so we should generate this:

``` js
export default Ember.Component.extend({
  actions: {
    hello(name) {
      console.log("Hello", name);
    }
  }
});
```

We should add an option to control implicit returns, something like `shouldImplicitlyReturn(fn: Node): boolean`.

**Comment by andrewaustin** [comment]
This seems to also lead to a bug: 

http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=_.forIn%20tags%2C%20(val%2C%20key)%20-%3E%0A%20%20tag%20%3D%20log.c%20'tag'%2C%20%7B%20name%3A%20key%2C%20value%3A%20value%20%7D%0A
