### ISSUE TITLE
AddVariableDeclarationsStage failed to parse

### ISSUE THREAD

**Issue by andrewaustin** [decaffeinate/decaffeinate#410]
decaffeinate is crashing on my CoffeeScript input:

```coffee
@server.on 'sioDisconnect', =>
	@_statuses = {}
```

http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=%40server.on%20'sioDisconnect'%2C%20%3D%3E%0A%09%40_statuses%20%3D%20%7B%7D

I get this error:

```
AddVariableDeclarationsStage failed to parse: Unexpected token (2:28)
  1 | this.server.on('sioDisconnect', () => {
> 2 | 	return this._statuses = {};)
    |                             ^
 3| };
```

**Comment by johnking** [comment]
Same issue here: 

## coffee source code 
```
viewForItem: (item) ->
   "<li>#{item.replace(/\/\/(.*?)\//, "// <big>$1</big> /")}</li>"

```

## conversion error
```
AddVariableDeclarationsStage failed to parse: Unexpected token (11:1)
   9 |  viewForItem(item) {
  10 |    return `<li>${item.replace(/\/\/(.*?)\//, "// <big>$1</big> /`;)}</li>"
> 11 |  }
     |  ^
```

**Comment by alangpierce** [comment]
@johnking my guess is that your error is a different bug with the same error message. That error message basically just means "decaffeinate generated invalid JS", and in your case it looks like a bug in a string interpolation edge case (it's inserting the `` `; `` way too early).

**Comment by johnking** [comment]
@alangpierce 

thank Alan, 

Below are my steps to solve my own problem, it might be helpful to others :) 

- I commented out these lines in the coffee code
- use defcaffeinate to generate the ES6 scripts 
- manually convert the commented code ...

it works ...

**Comment by alangpierce** [comment]
@johnking yep, that's generally the approach I take, too. Ideally decaffeinate would handle everything, but working around bugs like that usually isn't so bad.
