### ISSUE TITLE
wrong parse or operator

### ISSUE THREAD

**Issue by wasap** [decaffeinate/decaffeinate#423]
result.isShow or = targetArray.toString() is [1,2,3].toString()
became 
if (result.isShow) { result.isShow = targetArray.toString() === [1,2,3].toString(); }
but has to be 
if (**!**result.isShow) { result.isShow = targetArray.toString() === [1,2,3].toString(); }

**Comment by alangpierce** [comment]
Thanks for reporting! I just put up PR #424 to fix this.
