### ISSUE TITLE
cannot find first or last token in PlusOp node

### ISSUE THREAD

**Issue by danielbprice** [decaffeinate/decaffeinate#425]
I am using decaffeinate 2.23.1.  decaffeinate is crashing on my CoffeeScript input:

``` coffee

abc = "Hello there,"

x = "#{abc} this should trigger a message about" + \
    "invalid plusops"
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=%23%23%23%0A%23%20Examples%20taken%20from%20coffeescript.org%0A%23%23%23%0A%0Aabc%20%3D%20%22Hello%20there%2C%22%0A%0Ax%20%3D%20%22%23%7Babc%7D%20this%20should%20trigger%20a%20message%20about%22%20%2B%20%5C%0A%20%20%20%20%22invalid%20plusops%22)
<LINK TO REPL>

```
a.coffee: cannot find first or last token in PlusOp node
  2 | abc = "Hello there,"
  3 |
> 4 | x = "#{abc} this should trigger a message about" + \
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  5 |     "invalid plusops"
  6 |
```

**Comment by danielbprice** [comment]
(removing the "plus" from line 4 and using a simple string works fine).

**Comment by danielbprice** [comment]
Might be related to bug #389.

**Comment by alangpierce** [comment]
Thanks for the report! Here's the decaffeinate-parser output for a minified test case: [repl](http://decaffeinate-project.org/repl/#?evaluate=true&stage=decaffeinate-parser&code=%22%23%7Ba%7Db%22%20%2B%20%22c%22).

Looks to me like a decaffeinate-parser bug: it's parsing it as two `PlusOp`s when it should be parsing it to a `TemplateLiteral`. The CoffeeScript lexer/parser loses template literal information, so decaffeinate-parser tries to reconstruct it, and it looks like that's what's going wrong here.
