### ISSUE TITLE
Crash converting for .. in .. when .. in

### ISSUE THREAD

**Issue by danielbprice** [decaffeinate/decaffeinate#429]
decaffeinate is crashing on my CoffeeScript input:

``` coffee
x = [1, 2, 3]
z = [1]
res = (s for s in x when s in z)
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=x%20%3D%20%5B1%2C%202%2C%203%5D%0Az%20%3D%20%5B1%5D%0Ares%20%3D%20%28s%20for%20s%20in%20x%20when%20s%20in%20z%29)

I get this error:

```
AddVariableDeclarationsStage failed to parse: Unexpected token (3:43)
 1 | x = [1, 2, 3];
 2 | z = [1];
>3 | res = (x.filter((s) => s, z)).map((s) => s));
   |                                            ^
 4 | function __in__(needle, haystack) {
 5 | return haystack.indexOf(needle) >= 0;
```

**Comment by alangpierce** [comment]
Looks like this is fixed now.
