### ISSUE TITLE
this assignment within a destructure parameter results in incorrect code

### ISSUE THREAD

**Issue by alangpierce** [decaffeinate/decaffeinate#431]
decaffeinate is producing the wrong JavaScript based on my CoffeeScript input:

```coffee
({@a}) ->
  return
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=(%7B%40a%7D)%20-%3E%0A%20%20return)
<LINK TO REPL>

I get this output:

```js
(function({a1}) {
  this.a = a;
  this.a = a1;
});
```

Here's what I expect it to be instead:

```js
(function({a}) {
  this.a = a;
});
```

**Comment by madskonradsen** [comment]
That bug have existed for quite some time, #213 :)

**Comment by alangpierce** [comment]
Ooh, thanks for pointing that out! I was worried that I had broken it with https://github.com/decaffeinate/decaffeinate/pull/426 , but I guess not. Closing in favor of the other issue.
