### ISSUE TITLE
conditional with assignment fails to decaffeinate

### ISSUE THREAD

**Issue by neouser99** [decaffeinate/decaffeinate#434]
decaffeinate is crashing on my CoffeeScript input:

```coffee
fn() unless foo = bar
```

this too:
```coffee
unless foo = bar
  fn()
```

<LINK TO REPL>

I get this error:

```
AddVariableDeclarationsStage failed to parse: Invalid left-hand side in assignment expression (1:4)
> 1 | if (!foo = bar) { fn(); }
    |     ^
```

this works:

```coffee
if foo = bar
  fn foo
```

```javascript
let foo;
if (foo = bar) {
  fn(foo);
}
```

I think in the unless case, parenthesis need to be wrapped around the assignment is all.

**Comment by alangpierce** [comment]
Thanks for the report! I just submitted #436, which should fix this issue.
