### ISSUE TITLE
Newline inside .on / .off causes weird bugs

### ISSUE THREAD

**Issue by stilist** [decaffeinate/decaffeinate#437]
These bugs require the specific combination of `.on` / `.off` and `.` in a trailing position.

    a.
    on('', c)

parses as

    a.
    on('', c))

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=false&stage=NormalizeStage&code=a.%0Aon(''%2C%20b))

    a.
    on('')

throws the error `Cannot overwrite a zero-length range – use insertLeft or insertRight instead`.

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=false&stage=NormalizeStage&code=a.%0Aon(''))

**Comment by alangpierce** [comment]
Thanks! This should be fixed by https://github.com/decaffeinate/coffee-lex/pull/52.
