### ISSUE TITLE
Incorrect parsing for nested class + condition statement

### ISSUE THREAD

**Issue by stilist** [decaffeinate/decaffeinate#438]
This may be the same as #370, or at least related.

The nested statement under `if` injects `a`'s closing parenthesis at the wrong point:

```
a ->
  class b
    c: ->
      if d
        ''
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=false&stage=MainStage&code=a%20-%3E%0A%20%20class%20b%0A%20%20%20%20c%3A%20-%3E%0A%20%20%20%20%20%20if%20d%0A%20%20%20%20%20%20%20%20'')

```
a(function() {
  return class b {
    c() {
      if (d) {
        return '';
      }
    }
)
  }
};
```

Moving `''` to before the `if` throws an error:

```
a ->
  class b
    c: ->
      '' if d
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=false&stage=MainStage&code=a%20-%3E%0A%20%20class%20b%0A%20%20%20%20c%3A%20-%3E%0A%20%20%20%20%20%20''%20if%20d)

```
MainStage failed to parse: unexpected string
  3 |     c: ->
  4 |       if d then
> 5 | )''
    |  ^^
```

In both cases, the code parses correctly if `a ->` or the if statement are removed.

**Comment by stilist** [comment]
After poking around a little more, the second issue is clearer in NormalizeStage.

```coffee
a ->
  class b
    c: ->
      '' if d

# parsed

a(->
  class b
    c: ->
      if d then 
)''
```

There's also an interesting variation with comments.

```coffee
a ->
  class b
    c: -> #

# parsed

a(->
  class b
    c: ->
) #
```

(Note that in this latter case changing `#` to `""` produces the correct result. Perhaps a separate issue?)

**Comment by stilist** [comment]
I can get the correct result by wrapping the contents of `c` with parentheses.

```coffee
a ->
  class b
    c: ->
      (if d
        "")

# parsed in NormalizeStage

a(->
  class b
    c: ->
      (if d
        "")
)
```

**Comment by stilist** [comment]
One last note: this error only seems to happen with the last conditional inside the class.

```coffee
a ->
  class b
    c: ->
      'd' if e
    
    f: ->
      'g' if h

# parsed in NormalizeStage

a(->
  class b
    c: ->
      if e then 'd'
    
    f: ->
      if h then 
)'g'```

**Comment by alangpierce** [comment]
Looks like this is fixed now, probably from https://github.com/decaffeinate/coffeescript/pull/10.
