### ISSUE TITLE
Conditional assignment of function parses incorrectly

### ISSUE THREAD

**Issue by stilist** [decaffeinate/decaffeinate#439]
I don't *think* this is the same issue as #434, despite the similar titles.

    a or= -> b

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=false&stage=MainStage&code=a%20or%3D%20-%3E%20b)

    if (!a) { a = function() function() { return return b; }; } };

The error changes slightly if the function has parameters:

    a or= (b) -> c

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=false&stage=MainStage&code=a%20or%3D%20(b)%20-%3E%20c)

    if (!a) { a = functionfunction(b) { return return c; }; } };

**Comment by alangpierce** [comment]
Thanks, just submitted a fix for this: #440.
