### ISSUE TITLE
Strangly omitted parantheses-end

### ISSUE THREAD

**Issue by madskonradsen** [decaffeinate/decaffeinate#458]
decaffeinate is crashing on my CoffeeScript input:

``` coffee
app().directive 'something', ->
  link: () ->
    if something
      callback()
```

[repl](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=app%28%29.directive%20'something'%2C%20-%3E%0A%20%20link%3A%20%28%29%20-%3E%0A%20%20%20%20if%20something%0A%20%20%20%20%20%20callback%28%29%0A)

I get this error:

```
AddVariableDeclarationsStage failed to parse: Unexpected token (9:0)
   7 |     }
   8 |   };
>  9 | )
     | ^
  10 | };
```

**Comment by alangpierce** [comment]
Looks like this is the same as #460. Maybe you meant to put different code for this one?

**Comment by madskonradsen** [comment]
Hah! I think that I just wasn't properly awake when I did it! Closing #460
