### ISSUE TITLE
`this` lost on conditional call

### ISSUE THREAD

**Issue by marcandre** [decaffeinate/decaffeinate#462]
decaffeinate is producing the wrong JavaScript based on my CoffeeScript input:

```coffee
foo = {bar: -> alert(this is foo) }
foo.bar?();
```

 [(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=foo%20%3D%20%7Bbar%3A%20-%3E%20alert(this%20is%20foo)%20%7D%0Afoo.bar%3F()%3B)

I get this output:

```js
let foo = {bar() { return alert(this === foo); } };
__guardFunc__(foo.bar, f => f());
function __guardFunc__(func, transform) {
  return typeof func === 'function' ? transform(func) : undefined;
}
```
This alerts `false`, while the CS alerts `true`.

The context (`this`) is lost.
Ideally it to would produce instead:

```js
let foo = {bar() { return alert(this === foo); } };
if typeof foo.bar === 'function' {
  foo.bar();
}
```

Related to #336 (because current output is indeed ugly), but way worse because it just doesn't work...

**Comment by alangpierce** [comment]
Yikes, thanks for catching. I thought I thought through that case when implementing the `__guard__` and `__guardFunc__` stuff, but I guess the approach ended up not working. Unfortunately I don't think there's a really easy fix, but I imagine there's a way to make it work.
