### ISSUE TITLE
Disable Converting require to import

### ISSUE THREAD

**Issue by andrewaustin** [decaffeinate/decaffeinate#477]
I'm converting a large node project to from CoffeeScript to ES6. Because Node 6 LTS does not support ```import``` module loading, I would like to not convert my CoffeeScript ```require``` statements to ```import``` but instead let/const. Is it possible to disable to avoid using Babel?

**Comment by madskonradsen** [comment]
Dupe of #407 ? :)

**Comment by andrewaustin** [comment]
Looks like, will close this one :)
