### ISSUE TITLE
Unexpected token using `when` in for-of loop with `?`

### ISSUE THREAD

**Issue by leonyu** [decaffeinate/decaffeinate#483]
decaffeinate is crashing on my CoffeeScript input:

```coffee
filteredData = {}
for k, v of data when v?
  filteredData[k] = v
```

http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=data%20%3D%20%7Ba%3A1%7D%0AfilteredData%20%3D%20%7B%7D%0Afor%20k%2C%20v%20of%20data%20when%20v%3F%0A%20%20filteredData%5Bk%5D%20%3D%20v

I get this error:

```
AddVariableDeclarationsStage failed to parse: Unexpected token (4:21)
```

**Comment by Eden-Sun** [comment]
same for-in
```coffee
for a in b when c?
  d()
```
