### ISSUE TITLE
Cannot represent Block as an expression

### ISSUE THREAD

**Issue by amcnamara** [decaffeinate/decaffeinate#484]
Decaffeinate is crashing on my CoffeeScript input:

```coffee
(if pred
  thing
else if pred2
  thing2
)
```

I get this error:

```
/Users/amcnamara/test → /Users/amcnamara/test.js
/Users/amcnamara/test: cannot represent Block as an expression
  1 | (if pred
  2 |   thing
> 3 | else if pred2
> 4 |   thing2
  5 | )
  6 |
```

However, decaffeinate runs just fine if there is a closing else statement, ex:

```coffee
(if pred
  thing
else if pred2
  thing2
else
  thing3
)
```

**Comment by alangpierce** [comment]
Hmm, it seems to be working for me, and it works in the repl: [link](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=(if%20pred%0A%20%20thing%0Aelse%20if%20pred2%0A%20%20thing2%0A))

Maybe try updating to the latest version of decaffeinate and see if that fixes it?

**Comment by amcnamara** [comment]
Hey Alan,

Sorry about the confusion, I thought I had updated but npm was still referencing an older version. Updating fixed this, thanks for the fast response and for your work on the tool!

Closing.
