### ISSUE TITLE
Using functions in an `or` chain does not work

### ISSUE THREAD

**Issue by leonyu** [decaffeinate/decaffeinate#500]
decaffeinate is crashing on my CoffeeScript input:

``` coffee
b = a or () -> 'hello world'
```

http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=b%20%3D%20a%20or%20()%20-%3E%20'hello%20world'%0A

I get this error:

```
EsnextStage failed to parse: Unexpected token (1:14)
> 1 | var b = a || function() { return 'hello world'; };
    |               ^
  2 | 
```

**Comment by alangpierce** [comment]
The error message wasn't very useful in this case. Here's a better error from a patched version of the code that I have locally:
```
EsnextStage failed to parse: Error running plugin functions.arrow: Unexpected token (1:14)
> 1 | var b = a || () => 'hello world';
    |               ^
```
It looks like JS arrow functions don't work nicely with binary operators, so probably the code converting the function to an arrow function needs to wrap it in parens in this case.
