### ISSUE TITLE
Empty file with only comment block causes crash

### ISSUE THREAD

**Issue by leonyu** [decaffeinate/decaffeinate#505]
decaffeinate is crashing on my CoffeeScript input:

```coffee
# empty file
```

http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=%23%20empty%20file%0A

I get this error:

```
unexpected 'null' index, perhaps you forgot to check the result of 'indexOfTokenContainingSourceIndex'?
```

**Comment by alangpierce** [comment]
Fixed with https://github.com/decaffeinate/decaffeinate-parser/pull/72.

**Comment by leonyu** [comment]
wow you guys are fast

**Comment by eventualbuddha** [comment]
That's all @alangpierce's doing these days ;) Great work!

**Comment by alangpierce** [comment]
Thanks. :-)
