### ISSUE TITLE
escaped backtick errors when used in addition

### ISSUE THREAD

**Issue by leonyu** [decaffeinate/decaffeinate#506]
decaffeinate is crashing on my CoffeeScript input:

``` coffee
text = "\`" + 1
```

http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=text%20%3D%20%22%5C%60%22%20%2B%201%0A

I get this error:

```
EsnextStage failed to parse: Unexpected token, expected ; (1:15)
> 1 | var text = "\`" + 1;
    |                ^
  2 | 
```

**Comment by alangpierce** [comment]
The error message wasn't very useful in this case. Here's a better error from a patched version of the code that I have locally:
```
EsnextStage failed to parse: Error running plugin strings.template: Unexpected token, expected ; (1:15)
> 1 | let text = `\\`${1}`;
    |                ^
```
It looks like the code to convert the string to a template string is escaping the backtick character, but there's already a backslash there, so the backtick is being interpreted as the end of the string.

Seems reasonable to fix, although I'm pretty sure there's no need to escape backticks in CoffeeScript strings, so an easy way to address this before it's fixed is just to remove the backslash from the code.
