### ISSUE TITLE
Wrong call to `slice` produced for ranges ending with `-1` (last character)

### ISSUE THREAD

**Issue by bengotow** [decaffeinate/decaffeinate#524]
decaffeinate is producing the wrong JavaScript based on my CoffeeScript input.

When slicing strings using CoffeeScript's `str[a..b]` syntax, specifying the end of the string / last character of the string (`b = -1`) causes Decaffeinate to produce output which is incorrect. We've been bitten by this a few times because it's pretty subtle.

```coffee
myFunction = =>
  str = "This is a:string"
  index = str.indexOf(":")
  return str[index..-1]
```

<LINK TO REPL>

I get this output:

```js
let myFunction = () => {
  let str = "This is a:string";
  let index = str.indexOf(":");
  return str.slice(index, -1 + 1);     << this is not correct! Always returns an empty string.
};
```

Here's what I expect it to be instead:

```js
let myFunction = () => {
  let str = "This is a:string";
  let index = str.indexOf(":");
  return str.slice(index);
};
```

**Comment by alangpierce** [comment]
Thanks for reporting. Omitting the argument seems reasonable when the end index is exactly the expression `-1`, but if it's a variable or something more complicated, then it might be necessary sometimes.

Here's what I'm thinking. Transform this:

```coffee
str[a..-1]
```

into this:

```js
str.slice(a)
```

and transform this:

```coffee
str[a..b]
```

into this:

```js
str.slice(a, b + 1 || undefined)
```

Does that seem like the right behavior? It seems fairly consistent with the [CoffeeScript approach](http://coffeescript.org/#try:str%5Ba..b%5D).

**Comment by eventualbuddha** [comment]
Ah, I didn't understand why CoffeeScript did the `|| undefined` thing, but that makes sense.
