### ISSUE TITLE
Destructuring Assignments to already declared variables as last statement of function crashes

### ISSUE THREAD

**Issue by marcmenn** [decaffeinate/decaffeinate#527]
decaffeinate is crashing on my CoffeeScript input:

```coffee
foo = null
->
  {foo} = bar
```

http://decaffeinate-project.org/repl/#?evaluate=false&stage=full&code=foo%20%3D%20null%0A-%3E%0A%20%20%7Bfoo%7D%20%3D%20bar%0A

I get this error:

```
EsnextStage failed to parse: Invalid left-hand side in assignment expression (2:0)
  1 | var foo = null;
> 2 | (function() {
    | ^
  3 |   return {foo} = bar;
  4 | });```

**Comment by alangpierce** [comment]
The error message wasn't very useful in this case. Here's a better error from a patched version of the code that I have locally:
```
EsnextStage failed to parse: Error running plugin functions.arrow: Invalid left-hand side in assignment expression (2:0)
  1 | var foo = null;
> 2 | () => {foo} = bar;
    | ^
```
It looks like the issue here is that if an arrow function expression body would start with a `{` token, then it needs to be wrapped in parens to avoid a parser issue.
