### ISSUE TITLE
Destructuring Assignemnts with require sometimes break

### ISSUE THREAD

**Issue by marcmenn** [decaffeinate/decaffeinate#528]
decaffeinate is crashing on my CoffeeScript input:

```coffee
{foo} = require('bar').x
```

http://decaffeinate-project.org/repl/#?evaluate=false&stage=full&code=%7Bfoo%7D%20%3D%20require('bar').x%0A

I get this error:

```
Property local of ImportSpecifier expected node to be of a type ["Identifier"] but instead got "ObjectPattern"
```

**Comment by alangpierce** [comment]
Thanks for reporting. This is a duplicate of #404, so closing in favor of that one.
