### ISSUE TITLE
Error converting empty switch with functions in cases

### ISSUE THREAD

**Issue by elanhami** [decaffeinate/decaffeinate#562]
decaffeinate is producing the wrong JavaScript based on my CoffeeScript input.
This is a pretty big issue as it inverts the whole logic of the switch control flow.

```coffee
func: (str) ->
  switch
    when a(str)
      "A"
    when b(str)
      "B"
```

http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=func%3A%20(str)%20-%3E%0A%20%20switch%0A%20%20%20%20when%20a(str)%0A%20%20%20%20%20%20%22A%22%0A%20%20%20%20when%20b(str)%0A%20%20%20%20%20%20%22B%22

I get this output:

```js
  func(str) {
    switch (false) {
      case a(str):
        return "A";
      case b(str):
        return "B";
    }
  }
```

Here's what I expect it to be instead:

```js
  func: function(str) {
    switch (false) {
      case !a(str):
        return "A";
      case !b(str):
        return "B";
    }
  }
```

http://coffeescript.org/#try:func%3A%20(str)%20-%3E%0A%20%20switch%0A%20%20%20%20when%20a(str)%0A%20%20%20%20%20%20%22A%22%0A%20%20%20%20when%20b(str)%0A%20%20%20%20%20%20%22B%22

**Comment by alangpierce** [comment]
Yikes, thanks for reporting. Looks like there is code that tries to negate the two case expressions, but it's not working in this case. Hopefully should be a relatively easy fix.
