### ISSUE TITLE
Incorrect output when attribute defined using 'unless' inside of an object

### ISSUE THREAD

**Issue by Kequc** [decaffeinate/decaffeinate#566]
Hello, there is an unfortunate reversal when defining an attribute using unless inside of an object.

```coffee
isValid = true

testing = {
    test: "Hello world" unless isValid
}
```

http://decaffeinate-project.org/repl/#?evaluate=false&stage=full&code=isValid%20%3D%20true%0A%0Atesting%20%3D%20%7B%0A%20%20%20%20test%3A%20%22Hello%20world%22%20unless%20isValid%0A%7D

I get this output:

```js
let isValid = true;

let testing = {
    test: isValid ? "Hello world" : undefined
};
```

Here's what I expect it to be instead:

```js
let isValid = true;

let testing = {
    test: isValid ? undefined : "Hello world"
};
```

**Comment by alangpierce** [comment]
Thanks for reporting, and sorry for the subtle correctness issue. It looks to me like `unless` is respected when a conditional is used in a statement context, but it's ignored in an expression context. Hopefully should be an easy fix.
