### ISSUE TITLE
Certain callbacks involving arguments fail to decaffeinate

### ISSUE THREAD

**Issue by wavebeem** [decaffeinate/decaffeinate#579]
decaffeinate is crashing on my CoffeeScript input:

```coffee
foo =>
  if quux
    bar arguments
```

It seems like the callback, the `if` statement, and specifically `arguments` are all necessary to trigger this bug.

[(link to repl)](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=foo%20%3D%3E%0A%20%20if%20true%0A%20%20%20%20%23%20%60arguments%60%20is%20critical%20to%20repro%20here.%0A%20%20%20%20bar%20arguments%0A)

I get this error:

```
AddVariableDeclarationsStage failed to parse: Unexpected token (5:3)
  3 |     // `arguments` is critical to repro here.
  4 |     return bar(arguments);
> 5 |   }.bind(this)
    |    ^
  6 | });
  7 | 
```

**Comment by eventualbuddha** [comment]
Interesting. This is what the main stage generates:

```js
foo(function() {
  if (true) {
    // `arguments` is critical to repro here.
    return bar(arguments);
  }.bind(this)
});
```

As you can see, the `.bind(this)` is attached to the braces on the conditional rather than the function body, which is clearly wrong.
