### ISSUE TITLE
chokes on line continuation

### ISSUE THREAD

**Issue by jloveric** [decaffeinate/decaffeinate#58]
Very useful project.  I was just experimenting with converting rivescript,js (https://github.com/aichaos/rivescript-js/) and ran into this issue.  decaffeinate chokes on the line continuation for multi-line text (likely anything using the line continuation)

    rs.say "Collecting trigger list for topic #{topic} (depth=#{depth}; " \
        + "inheritance=#{inheritance}; inherited=#{inherited})"

The problem is resolved when I eliminate the line continuation and put everything on one line.

**Comment by eventualbuddha** [comment]
Thanks for the kind words!

This appears to be a CoffeeScriptRedux bug as the [online demo doesn't support it either](https://michaelficarra.github.io/CoffeeScriptRedux/#try:a%20%5C%0A%20%20b). I've been investigating switching to the official CoffeeScript parser but it'd require a lot of work.

**Comment by eventualbuddha** [comment]
Switching the parser is now tracked as #65.

**Comment by eventualbuddha** [comment]
Interestingly, this is still a problem in v2. I'll see what's up.

**Comment by Eden-Sun** [comment]
What do you think ```"a#{b}" + "c"``` should be?
coffeescript compiles to ```("a" + b) + "c";```
 ``` `a${b}c` ``` ?

**Comment by eventualbuddha** [comment]
Well, it appears that `"a#{b}" + "c"` fails to transform properly (tracked as #194). But if it did, decaffeinate would turn it into ``` `a${b}` + "c"` ``` in the main stage and esnext would turn that into ``` `a${b}c` ``` in the final stage. Is that related to continuations?

**Comment by eventualbuddha** [comment]
Fixed in v2.7.11.

**Comment by Eden-Sun** [comment]
No relations . Just found the code @jloveric pasted is not compiled.

**Comment by eventualbuddha** [comment]
@Eden-Sun yep, that's a separate issue and is tracked as #195.
