### ISSUE TITLE
Support nested ternary expressions

### ISSUE THREAD

**Issue by eventualbuddha** [decaffeinate/decaffeinate#59]
[This](https://eventualbuddha.github.io/decaffeinate/repl/#?evaluate=false&experimental=false&playground=false&loose=false&spec=false&code=%23%20%60if%60%20expression%20with%20multiple%20alternates%0Aa(if%20b%20then%20c%20else%20if%20d%20then%20e%20else%20f)%0A):

```coffee
# `if` expression with multiple alternates
a(if b then c else if d then e else f)
```

Should become:

```js
// `if` expression with multiple alternates
a(b ? c : d ? e : f);
```

Or perhaps:

```js
// `if` expression with multiple alternates
a(b ? c : (d ? e : f));
```

This is follow-up from #23.

**Comment by acao** [comment]
nested ternary expressions (not all ternary expressions) are commonly seen as an anti-pattern in es2015land:
https://github.com/eslint/eslint/blob/master/docs/rules/no-nested-ternary.md

These above should ideally be converted to proper, readable conditional expressions.

**Comment by eventualbuddha** [comment]
@acao do you have an example for an alternative to my proposed one above?

**Comment by bouk** [comment]
@eventualbuddha this is probably best translated using the do expression, so:

```js
a(do {
  if (b) {
    c;
  } else if (d) {
    e;
  } else {
    f;
});
```

Which Babel supports (and translates to a ternary)

**Comment by eventualbuddha** [comment]
This is now working ([repl](http://decaffeinate.github.io/decaffeinate/repl/#?evaluate=false&code=a(if%20b%20then%20c%20else%20if%20d%20then%20e%20else%20f))).
