### ISSUE TITLE
Resulting JS can incorrectly have this before super in a constructor

### ISSUE THREAD

**Issue by alangpierce** [decaffeinate/decaffeinate#591]
decaffeinate is producing the wrong JavaScript based on my CoffeeScript input:

```coffee
class A extends B
  constructor: ->
    @c = d
    super
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=class%20A%20extends%20B%0A%20%20constructor%3A%20-%3E%0A%20%20%20%20%40c%20%3D%20d%0A%20%20%20%20super)

I get this output:

```js
class A extends B {
  constructor() {
    this.c = d;
    super(...arguments);
  }
}
```

Here's a [babel repl link](http://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&code=class%20A%20extends%20B%20%7B%0A%20%20constructor()%20%7B%0A%20%20%20%20this.c%20%3D%20d%3B%0A%20%20%20%20super(...arguments)%3B%0A%20%20%7D%0A%7D) that shows the error here: "'this' is not allowed before super()".

I don't have any great ideas on how decaffeinate can handle this, but it affects 11 files in my codebase, so it seems useful to address or at least acknowledge the problem. Here are some possible ideas:
* Maybe decaffeinate could detect this case and generate CS-style classes instead of JS classes, so that it's allowed to use `this` before `super`. One downside here, though, is that JS and CS classes have interop issues, so it's best to use only JS classes if possible.
* There may be some clever way to rewrite the code to be correct. My best idea at the moment in the above code example is to change `c` into a getter, which I think means that it will be accessible to the super constructor, but obviously the general case is likely much harder.
* We could document that this is an issue and provide suggestions on how to fix it.
* decaffeinate could detect this case and give an error or a warning so that people are aware of it earlier rather than running into a babel failure after decaffeinate is finished.

**Comment by alangpierce** [comment]
This is probably the biggest remaining issue in my codebase, so I've been thinking about this a bit more and doing more research. At the very least, it should be reasonable to make decaffeinate fail in these cases with a helpful message saying you have to rework your CoffeeScript code. And maybe we could have a flag to convert anyway if people prefer to rework their code on the JavaScript side.

Still, I've also been thinking about possible ways to convert this code anyway, ideally while still sticking with JS classes. One thought that I've been playing with is to do something like converting this:

```coffee
class A extends B
  constructor:
    @c = d
    super
```

to this:

```js
class A extends __wrapSuperclass__(B) {
  _constructor() {
    this.c = d;
    super._constructor();
  }
}

function __wrapSuperclass__(c) {
  ???
}
```

Point is, instead of the code being in the real constructor, it's just a normal method called `_constructor`, and `__wrapSuperclass__` somehow figures out how to call that method at the right time. I haven't figure out a way to actually implement `__wrapSuperclass__` to do that, but maybe there's a way.

Another thing that I figured out recently is that babel-generated classes are hooked up in a way that they have a `this` instance before the `super` call, but babel just tries to stop you from being able to access it, but with hacks it's possible to make it work. Here's a [babel repl link](http://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=true&presets=es2015%2Creact%2Cstage-2&code=class%20B%20%7B%0A%20%20constructor()%20%7B%0A%20%20%20%20console.log('blah%20is%20'%20%2B%20this.blah)%3B%0A%20%20%7D%0A%7D%0A%0Aclass%20A%20extends%20B%20%7B%0A%20%20constructor()%20%7B%0A%20%20%20%20if%20(false)%20%7B%20super()%3B%20%7D%20%20%2F%2F%20Hack%20to%20trick%20babel's%20compile-time%20check.%0A%20%20%20%20eval('_this%20%3D%20this%3B')%3B%20%20%2F%2F%20Hack%20to%20make%20it%20so%20modifying%20%60this%60%20works.%0A%20%20%20%20this.blah%20%3D%20%22abc%22%0A%20%20%20%20super()%3B%0A%20%20%7D%0A%7D%0A%0Anew%20A()%3B) that seems to work around this using `eval` and a static analysis trick. I'm thinking of making decaffeinate insert this hack, probably behind a preference (and just in the relatively rare cases where it's necessary). This approach doesn't work at all with real JS classes, though.

**Comment by eventualbuddha** [comment]
The quickest fix for this is probably to translate `super` in the constructor to something similar to what babel would generate:

```js
  constructor() {
    Object.getPrototypeOf(this.prototype.constructor).apply(this, arguments);
  }
```

We can probably make this happen only in out-of-order cases.

**Comment by alangpierce** [comment]
Makes sense, although I think it's not quite as easy as that:

* If you're running with babel, the `this` will get translated to `_this` instead of the real `this`, so you can't just put that code in a class constructor like that. Also, it will hit the compile-time check that you don't use `this` before `super`. You can get around that using `eval` like in my example. I think it should also be possible to omit the constructor and make a separate function that takes the place of the constructor and does all of the stuff that babel does, but that seems more difficult.
* If you're trying to run without babel, this will crash because you can only use `new` or `Reflect.construct` to instantiate a real JS class (neither of which let you specify the initial `this`, I think). This also means that babel classes can't extend real JS classes.

If we're working at this level, we may need a pref for whether or not people are using babel. Maybe the best we can do is give an error if people aren't using babel and do some babel-compatible thing if people are using babel. In my codebase, we use babel for everything, so something babel-specific would be fine.

Also, there are two other correctness issues I've run into that are related to this that could probably be fixed in a similar way:
* Constructors in CS are allowed to just never call `super`, which I think has the behavior of never running the init code for the superclass.
* Bound methods in CS (e.g. `foo: => bar` in a class body) get bound before the constructor runs at all. I've hit some cases where the super constructor expects all methods to already be bound. In these cases, we could generate `this.foo = this.foo.bind(this);` before the `super` if we already have some way to use `this` before `super`.
