### ISSUE TITLE
Chaining function calls on separate lines generates invalid JS

### ISSUE THREAD

**Issue by christopherthielen** [decaffeinate/decaffeinate#63]
see: http://bit.ly/1M6tUYk
This coffeescript:
```
$stateProvider
.state 'foo'
.state 'bar'
```
should generate something like `$stateProvider.state('foo').state('bar');`

It generates invalid JS:
```
$stateProvider
.state( 'foo'
.state( 'bar'
)
);
```

**Comment by christopherthielen** [comment]
dupe #51

**Comment by eventualbuddha** [comment]
Believe it or not this isn't a dupe of #51. The parsing seems to be happening correctly but decaffeinate isn't inserting the parentheses in the right place.

**Comment by eventualbuddha** [comment]
Fixed in the latest version ([repl](http://decaffeinate.github.io/decaffeinate/repl/#?evaluate=false&code=%24stateProvider%0A.state%20'foo'%0A.state%20'bar')).
