### ISSUE TITLE
Wrong behavior when using a range with a negative "by" value in a "for in" loop

### ISSUE THREAD

**Issue by daniel-wer** [decaffeinate/decaffeinate#640]
decaffeinate is producing the wrong JavaScript based on my CoffeeScript input:

```coffee
a = 5
b = 0
for u in [a..b] by -1
  console.log(u)
```

http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=a%20%3D%205%0Ab%20%3D%200%0Afor%20u%20in%20%5Ba..b%5D%20by%20-1%0A%20%20console.log(u)

I get this output:

```js
let a = 5;
let b = 0;
for (let u = a; u <= b; u++) {
  console.log(u);
}
```

Here's what I expect it to be instead:

```js
let a = 5;
let b = 0;
for (let u = a; u >= b; u--) {
  console.log(u);
}
```

I noticed this does work if a and b in the coffeescript range are substituted by their values. However in the presented case it seems to be ignored that the `by` value is negative.

**Comment by alangpierce** [comment]
Thanks for reporting! Looks like this probably won't be too bad to fix soon.
