### ISSUE TITLE
for-own on null or undefined causes a crash

### ISSUE THREAD

**Issue by alangpierce** [decaffeinate/decaffeinate#644]
decaffeinate is producing the wrong JavaScript based on my CoffeeScript input:

```coffee
for own a of undefined
  console.log(a);
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=for%20a%20of%20undefined%0A%20%20console.log(a)%3B)

I get this output:

```js
for (let a of Object.keys(undefined)) {
  console.log(a);
}
```

The problem is that `Object.keys` crashes on `null` or `undefined`, but CS for-own turns into a JS for-in loop, which can iterate over `null`/`undefined` without crashing.

Here's what I expect it to be instead:

```js
for (let a of Object.keys(undefined || {})) {
  console.log(a);
}
```

At least, it seems like that should be correct. I think the expected behavior for all falsy values is to not iterate at all.

This causes the last remaining test failure in the Hubot project.

**Comment by eventualbuddha** [comment]
Why not just use `for-in` like CS does?

**Comment by alangpierce** [comment]
@eventualbuddha for CS `for own` in particular I think it's cleaner and more understandable to do a JS `for-of` over `Object.keys` (even with the null check) than to have to do the `hasOwnProperty` check in the loop. It's also a little easier to implement on the decaffeinate side, I think.

In general, because of the nuances with own properties, I try to avoid ever using `for-in` in new JS code. You can do basically everything you need with `for-of`, and I think it makes the language a little more approachable to just have one type of loop. Also, FWIW, it looks like the Airbnb eslint style completely disallows `for-in`.
