### ISSUE TITLE
Crash on this-assign with a keyword property in an parameter

### ISSUE THREAD

**Issue by alangpierce** [decaffeinate/decaffeinate#666]
decaffeinate is crashing on my CoffeeScript input:

```coffee
(@case) ->
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=(%40case)%20-%3E)

I get this error:

```
replacement content must be a string
> 1 | (@case) ->
    | ^^^^^^^^^^
```

I think maybe we'll need to make `claimFreeBinding` avoid reserved words.

**Comment by eventualbuddha** [comment]
> I think maybe we'll need to make claimFreeBinding avoid reserved words.

Yep, sounds right.
