### ISSUE TITLE
Loop statements with an inline body no longer work

### ISSUE THREAD

**Issue by alangpierce** [decaffeinate/decaffeinate#674]
decaffeinate is crashing on my CoffeeScript input:

```coffee
loop a
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=loop%20a)

I get this error:

```
MainStage failed to parse: unexpected identifier
> 1 | while true a
    |            ^
```

@eventualbuddha looks like this was caused by https://github.com/decaffeinate/decaffeinate/commit/4178ee0c4edc3a8d35bdfb1e5ced91afdbd199

I think in the inline form, it needs to convert to `while true then a`. Another case that needs to work correctly is `loop then a`, so I think the most straightforward fix is to check if the `then` is missing and add it if so.

**Comment by alangpierce** [comment]
@eventualbuddha assigned to you, but I can also take care of it if you think you won't have the bandwidth to fix it.

**Comment by eventualbuddha** [comment]
I'll take it.
