### ISSUE TITLE
Trailing indented block comments can cause a crash

### ISSUE THREAD

**Issue by alangpierce** [decaffeinate/decaffeinate#687]
decaffeinate is crashing on my CoffeeScript input:

```coffee
a ->
  b
  ### c ###
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=a%20-%3E%0A%20%20b%0A%20%20%23%23%23%20c%20%23%23%23)

I get this error:

```
MainStage failed to parse: unexpected indentation
  2 |   b
  3 | )
> 4 |   ### c ###
    | ^^
```

Apparently block comments need to be properly indented, and the normalize stage doesn't make much of an attempt at that. This is particularly tricky because block comments aren't even in the decaffeinate-parser AST.

Found in https://github.com/jashkenas/coffeescript/blob/master/test/function_invocation.coffee

**Comment by eventualbuddha** [comment]
I was just thinking about block comments in the AST. Do you think we should preserve them?

**Comment by alangpierce** [comment]
Hmm, hard to say. My initial thought was to fix this by doing a post-processing step at the end of the normalize stage to fix any bad indentation. But really ideally we'd want the block comment to be within the function, and I guess at the moment it's tricky for decaffeinate to distinguish between a block comment at the end of a function and a block comment after the function.

I'm not sure how reasonable it is given the code, but another option that would fix this issue is to keep the function body as ending at the end of the third line, even if the comment doesn't show up in the AST. The function bounds in the CoffeeScript AST end at the end of the third line, but I think decaffeinate-parser shrinks it to end at the end of the second line instead.

In general I don't like the fact that CoffeeScript puts one type of comment in the AST but not the other. But it might also be easier to just go with CoffeeScript's approach here, especially if the normalize stage needs to produce CoffeeScript code where block comments are always in a place where a statement can go (at least that's my reading of it).

**Comment by alangpierce** [comment]
Oh, another thing I just noticed is the CoffeeScript test case that caused this:
```
test "implicit return", ->

  eq ok, new ->
    ok
    ### Should `return` implicitly   ###
    ### even with trailing comments. ###
```
So if we add block comments as statements in the AST, we'd at least need to change the implicit return code to ignore them. And maybe it would cause other trouble, not sure.
