### ISSUE TITLE
crash with combination of various problems

### ISSUE THREAD

**Issue by eventualbuddha** [decaffeinate/decaffeinate#717]
decaffeinate is crashing on my CoffeeScript input:

```coffee
(->
  if b
    c ->
      d
).then ->
```

([repl](http://decaffeinate-project.org/repl/#?evaluate=false&stage=full&code=(-%3E%0A%20%20if%20b%0A%20%20%20%20c%20-%3E%0A%20%20%20%20%20%20d%0A).then%20-%3E%0A))

I get this error:

```
Cannot read property 'edit' of null
> 1 | (->
> 2 |   if b
> 3 |     c ->
> 4 |       d
> 5 | ).then ->
  6 | 
decaffeinate · v2.41.0 · Distributed under MIT License
```

Attempting to reduce this, I get different errors:

```coffee
(->
  if b
    c ->
      d
)
```

```
AddVariableDeclarationsStage failed to parse: Unexpected token (5:3)
  3 |     return c(function() {
  4 |       return d;
> 5 | });)
    |    ^
  6 |   }
  7 | });
```

```coffee
(->
  if b
    c ->
      d
).then
```

```
cannot find '.' in member access
> 1 | (->
> 2 |   if b
> 3 |     c(->
> 4 |       d
> 5 | )).then
  6 | 
```

**Comment by alangpierce** [comment]
Looks like this is fixed now, maybe due to https://github.com/decaffeinate/decaffeinate/commit/51bcff8c2155f7ddbab09fb66e63eabdd2c07e1f ?
