### ISSUE TITLE
Failure when passing multiline string as an argument

### ISSUE THREAD

**Issue by LuckyDino** [decaffeinate/decaffeinate#723]
decaffeinate is crashing on my CoffeeScript input:

```coffee
parse("""
""")
```

[repl](http://decaffeinate-project.org/repl/#?evaluate=true&stage=AddVariableDeclarationsStage&code=parse(%22%22%22%0A%22%22%22)%0A)

I get this error:

```
AddVariableDeclarationsStage failed to parse: Unterminated string constant (1:8)
> 1 | parse("""
    |         ^
  2 | """);
  3 | 
```

**Comment by alangpierce** [comment]
Looks like this is fixed now. I think the repl was using an out-of-date fork of the CoffeeScript repo, but https://github.com/decaffeinate/decaffeinate/pull/722 pulled in https://github.com/decaffeinate/coffeescript/pull/9, so it's working now.
