### ISSUE TITLE
Compilation of function in parentheses fail

### ISSUE THREAD

**Issue by LuckyDino** [decaffeinate/decaffeinate#727]
decaffeinate is crashing on my CoffeeScript input:

```coffee
launchMissile(->
  setTimeout (->
    launch()
  ), 5000
)
```

[repl](http://decaffeinate-project.org/repl/#?evaluate=true&stage=EsnextStage&code=launchMissile(-%3E%0A%20%20setTimeout%20(-%3E%0A%20%20%20%20launch()%0A%20%20)%2C%205000%0A))

I get this error:

```
MainStage failed to parse: unmatched OUTDENT
  2 |   setTimeout((->
  3 |     launch()
> 4 |   ), 5000
> 5 | ))
```

**Comment by denizoguz** [comment]
Is there any workaround for this?

**Comment by alangpierce** [comment]
@denizoguz yeah, in this case, you can move the placement of the last paren and it works:

```coffee
launchMissile(->
  setTimeout (->
    launch()
  ), 5000)
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&stage=EsnextStage&code=launchMissile(-%3E%0A%20%20setTimeout%20(-%3E%0A%20%20%20%20launch()%0A%20%20)%2C%205000))

And in general, if you run into errors like these, usually you can open the code in the repl and make tweaks to it until decaffeinate can handle it without errors, then copy and paste that code back into your editor. In most cases, the error message shows the code that has problems (sometimes in an intermediate transformed step) and you can use that to figure out what code to tweak.

**Comment by denizoguz** [comment]
@alangpierce, that works. Thanks a lot.
