### ISSUE TITLE
Split out constification as separate module?

### ISSUE THREAD

**Issue by kasbah** [decaffeinate/decaffeinate#743]
Hey, I converted a codebase a while back before the `--prefer-const` option was added. I was wondering if the constification could be done on an existing javascript codebase? Would be quite a useful tool in general if that's possible.

EDIT: I suppose ESlint might be the more appropriate tool for this: http://eslint.org/docs/rules/prefer-const

**Comment by eventualbuddha** [comment]
The addition of `let` and `const` is done by [esnext](https://github.com/esnext/esnext) and is a JS-to-JS tool. As you pointed out, using eslint's auto-fixing is better for this case.
