### ISSUE TITLE
Fail on single line lambda with semicolon

### ISSUE THREAD

**Issue by refack** [decaffeinate/decaffeinate#748]
decaffeinate is producing the wrong JavaScript based on my CoffeeScript input:

```coffee
foo = () -> null for i in []; t
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=foo%20%3D%20()%20-%3E%20null%20for%20i%20in%20%5B%5D%3B%20t%0D%0A)

I get this output:

```js
let foo = () => [].map((i) => (null, t));
```

Here's what I expect it to be instead:
preferably:
```js
let foo = () => {[].map((i) => null); return t}
```
else at least as if it's a multiline function
```js
let foo = function() { 
  for (let i of []) { null; }
  return t;
};
```

**Comment by alangpierce** [comment]
Thanks for reporting. Looks like the bug is that the normalize step rewrites it as this:

```coffee
foo = () -> for i in [] then null; t
```

But I guess it needs to maintain the precedence, maybe by wrapping the loop in parens:
```coffee
foo = () -> (for i in [] then null); t
```

**Comment by refack** [comment]
LGTM
👍
