### ISSUE TITLE
binary operator in parens mistakenly treated as part of chain

### ISSUE THREAD

**Issue by eventualbuddha** [decaffeinate/decaffeinate#783]
decaffeinate is producing the wrong JavaScript based on my CoffeeScript input:

```coffee
(a == b) == c == d
```

[repl](http://decaffeinate-project.org/repl/#?evaluate=false&stage=full&code=(a%20%3D%3D%20b)%20%3D%3D%20c%20%3D%3D%20d)

I get this output:

```js
(a === b && b) === c && c === d;
```

Here's what I expect it to be instead:

```js
(a === b) === c && c === d;
```

This is most likely because the parens are transparent to the AST, so when processing the chained comparison operator we just go as deep as we can into binary comparison operators. Should the AST change to represent this better? Something like this?

```js
ChainedComparisonOp {
  operands: [
    EQOp {
      left: Identifier { data: "a" },
      right: Identifier { data: "b" }
    },
    Identifier { data: "c" },
    Identifier { data: "d" }
  ],
  operators: [
    { operator: '==', token: SourceToken { type: OPERATOR } },
    { operator: '==', token: SourceToken { type: OPERATOR } }
  ]
}
```

**Comment by alangpierce** [comment]
👍 sounds like the right fix to me. Hopefully the `Parens` nodes in the CoffeeScript AST should make this type of thing easy to detect? (Also I'm pretty sure in your last code block there should be two operators, not three.)

**Comment by eventualbuddha** [comment]
> Also I'm pretty sure in your last code block there should be two operators, not three.

Yep, fixed.
