### ISSUE TITLE
fat-arrow `do` expression with assignment crashes

### ISSUE THREAD

**Issue by eventualbuddha** [decaffeinate/decaffeinate#784]
decaffeinate is crashing on my CoffeeScript input:

```coffee
do a = =>
  b
```

[repl](http://decaffeinate-project.org/repl/#?evaluate=false&stage=full&code=do%20a%20%3D%20%3D%3E%0A%20%20b%0A)

I get this error:

```
AddVariableDeclarationsStage failed to parse: Unexpected token, expected ; (3:1)
  1 | a = () => {
  2 |   return b;
> 3 | }();
    |  ^
  4 | 
```

[Looks like adding parens around the arrow function inside the assignment causes it to work](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Ces2016%2Ces2017%2Creact%2Cstage-2&code=a%20%3D%20(()%20%3D%3E%20%7B%0A%20%20return%20b%3B%0A%7D)()).

**Comment by alangpierce** [comment]
This is basically the same as #637, although maybe slightly different.

**Comment by alangpierce** [comment]
Oh, and actually your suggested fix is wrong here, I think. The variable `a` should end up referring to the function, not the return value when calling the function.

**Comment by eventualbuddha** [comment]
Ah, you're right!
