### ISSUE TITLE
Closing paren is placed on next line for arrow functions

### ISSUE THREAD

**Issue by kasbah** [decaffeinate/decaffeinate#787]
decaffeinate is producing **ugly** JavaScript based on my CoffeeScript input. :laughing:  

```coffee
f () =>
  a = 1
  a
```

http://decaffeinate-project.org/repl/#?evaluate=false&stage=full&code=f%20()%20%3D%3E%0A%20%20a%20%3D%201%0A%20%20a

I get this output:

```js
f(() => {
  let a = 1;
  return a;
}
);
```

Here's what I expect it to be instead:

```js
f(() => {
  let a = 1;
  return a;
});
```

FYI if we use a thin arrow

```coffee
f () ->
  a = 1
  a
```

we get a nicer:

```js
f(function() {
  let a = 1;
  return a;
});
```

**Comment by alangpierce** [comment]
Makes sense, the `}` and `)` are generated at different times, so making them share the same line can be a little tricky sometimes, but this seems like it should be reasonable to fix.
