### ISSUE TITLE
Set up tooling to run decaffeinate on popular open source projects

### ISSUE THREAD

**Issue by alangpierce** [decaffeinate/decaffeinate#789]
decaffeinate has now gotten stable enough that it can run on some open source projects (e.g. hubot and autoprefixer) with no errors, and in some cases it's possible to then run all of the tests and have them all pass. It would be cool to have a collection of these projects, especially to use them as a stress test to spot regressions and work through the long tail of rare correctness issues.

Here's roughly what I have in mind:
* Make a new project, maybe `decaffeinate-examples`. It will effectively be a collection of scripts to run decaffeinate on various existing codebases, but it won't actually contain all of those codebases.
* Create a generic system for describing everything about a repo to automatically run decaffeinate and all tests. For example:
  * A config file with things like the clone URL for the repo.
  * A bulk-decaffeinate.config.js file with the proper options and excluded files.
  * Common config files that should be added, like .babelrc and maybe .eslintrc.
  * A patch to the codebase that changes the build system to use babel (if necessary).
  * A script to run all tests and report the result.
* For each supported project, make a directory in the `decaffeinate-examples` repo with the right config files, patch, etc.
* For each project, the tool can then clone the repo, do `npm install`, put the config files in place, apply the patch, run bulk-decaffeinate, run all tests, and report the result. I guess ideally it would also handle any cases where decaffeinate can't handle everything yet, and will report what files can be converted and what tests pass.
* Potentially we could have a github org with JS forks of all of these projects, and automatically run the latest decaffeinate on the latest code every week to make sure everything still works.

**Comment by madskonradsen** [comment]
Sounds like pretty cool idea! I tried doing something related some months ago https://travis-ci.org/madskonradsen/bulk-decaffeinate-codecombat but that does of course not include testing the produced JS :-/ ESLint do actually also do something similar for catching the regressions that their unit tests doesn't catch https://github.com/not-an-aardvark/eslint-canary

**Comment by alangpierce** [comment]
Cool, yeah, I remember you mentioning that earlier.

Thanks for mentioning eslint-canary, I hadn't seen that, and seems pretty similar.

**Comment by alangpierce** [comment]
Ok, I got started with a tool that currently can convert the hubot repo, including tests: https://github.com/decaffeinate/decaffeinate-examples . I'll work on that a bit more before calling this issue closed.

**Comment by eventualbuddha** [comment]
Thus is great! Made my day. 😊

**Comment by madskonradsen** [comment]
It could also be fun to include the codecombat repo as it's one of the biggest CS repos by LoC https://github.com/codecombat/codecombat

**Comment by alangpierce** [comment]
Yep! The other examples that I was planning to add are coffeescript, atom, and codecombat. At least, those are the ones that I've been testing on my machine (although I haven't set up tests for any of those three). Happy to hear other suggestions.

The atom project is actually a little weird in that it has about 50k lines of CoffeeScript in the core project: https://github.com/atom/atom/ , but the org ( https://github.com/atom ) consists of about 200 projects that together are about 200k lines of CoffeeScript. So I guess ideally I'd have a way to clone all projects in an org and run decaffeinate on all of them.

**Comment by alangpierce** [comment]
Ok, the new https://github.com/decaffeinate-examples org now has the JavaScript version of six CoffeeScript projects, and the https://github.com/decaffeinate/decaffeinate-examples project can automate all of it.

Still to do:
* Set up a CI build to run all conversions regularly.
* Improve the output reporting.
* Set up tests after decaffeinate for the remaining projects.

**Comment by alangpierce** [comment]
CI is set up and there's a table on the README. There are a few additional improvements that could be made, but it's probably safe to call this task done, and a task has been filed for each individual repo to get it working fully.
