### ISSUE TITLE
Preincrement operator in chained comparison causes a crash

### ISSUE THREAD

**Issue by alangpierce** [decaffeinate/decaffeinate#807]
decaffeinate is crashing on my CoffeeScript input:

```coffee
0<++c<2
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&stage=decaffeinate-parser&code=0%3C%2B%2Bc%3C2)

I get this error:

```
cannot find operator token in range: [1, 2]
```

Found in https://github.com/jashkenas/coffeescript/blob/master/test/compilation.coffee

**Comment by alangpierce** [comment]
Looks like this one is still broken.

**Comment by eventualbuddha** [comment]
Looks like the spaces matter. Taking another look.
