### ISSUE TITLE
Fully convert hubot example repo to JavaScript

### ISSUE THREAD

**Issue by alangpierce** [decaffeinate/decaffeinate#821]
This a tracking task for getting hubot completely working as a decaffeinate example.

Repo: https://github.com/decaffeinate-examples/hubot

The conversion succeeds for all files and all tests pass, so this is nearly complete.

As mentioned in https://github.com/decaffeinate/bulk-decaffeinate/issues/90 , the file [bin/hubot](https://github.com/decaffeinate-examples/hubot/blob/decaffeinate/bin/hubot) is still CoffeeScript because it doesn't end in .coffee, so I think the main remaining issue is getting bulk-decaffeinate to detect that type of file and convert it as well.

**Comment by eventualbuddha** [comment]
This applies to all of these projects, but I'll comment here. Do you think we should make PRs for these? Or at least create an issue to pose the question?

**Comment by alangpierce** [comment]
@eventualbuddha yeah, my thought was to file an issue with each project (except coffeelint and coffeescript) once things get stable enough. I think a PR might be a little overwhelming. 😄

My main focus for now, though, is to get the correctness issues worked out so I can run decaffeinate on my codebase at work with more confidence. I also think having the dashboard of conversion status for each project is nice proof that it actually works for people who see decaffeinate for the first time.

**Comment by alangpierce** [comment]
With bulk-decaffeinate converting extensionless scripts, the hubot fork is now 100% JavaScript, so this seems safe to close. (I'll probably make an attempt at moving hubot and others to JS modules at some point, but I'll call that out of scope for this issue.)
