### ISSUE TITLE
Fully convert coffeescript example repo to JavaScript

### ISSUE THREAD

**Issue by alangpierce** [decaffeinate/decaffeinate#824]
This a tracking task for getting coffeescript completely working as a decaffeinate example.

Repo: https://github.com/decaffeinate-examples/coffeescript

This is one of the most difficult repositories to convert because it intentionally contains many tricky edge cases in the CoffeeScript language. I haven't looked into running the tests after the conversion, and it's potentially unclear what that even means, but it seems like there should be some reasonable approach to take.

Some open bugs that affect this repo:

https://github.com/decaffeinate/decaffeinate/issues/813
https://github.com/decaffeinate/decaffeinate/issues/689
https://github.com/decaffeinate/decaffeinate/issues/687
https://github.com/decaffeinate/decaffeinate/issues/637

**Comment by alangpierce** [comment]
After a lot of bug fixes, decaffeinate can now convert all files in the CoffeeScript repo without crashing (once all PRs are merged). The next step is to get the tests working, which is a bit more interesting than for normal projects.

The obvious first step, like with any other project, is to run decaffeinate on the CoffeeScript compiler and its tests, change the build system to use babel, then run all tests. That certainly will be a good way to verify correctness of decaffeinate, but I think it won't necessarily be complete. Most (but not all) of the tests in the CoffeeScript repo are simply CoffeeScript files that make assertions about their own behavior, so running all the tests may not get much code coverage on the decaffeinated CoffeeScript compiler.

One approach to address this is to keep the CoffeeScript form of the test files, run the decaffeinated CoffeeScript compiler on them, and make sure those tests pass. Another approach, which should be more thorough, is to keep around both forms of the CoffeeScript compiler, run them on all CoffeeScript files in the repo, and make sure they produce the same JS output.

For now, though, I'll just focus on getting the regular tests working.

**Comment by eventualbuddha** [comment]
I think the two most valuable things to test would be:

1. Leave the tests as CoffeeScript and convert them with the decaffeinate-converted compiler. 
2. Maybe use the decaffeinate-converted compiler on other projects (like Atom) to see whether they work as expected.

**Comment by alangpierce** [comment]
I hooked up some tests for the CoffeeScript compiler itself, which seems to be working now. The CoffeeScript tests are still failing, but it's incorrectly showing as success because apparently `bin/cake test` doesn't set the exit code to 1 on failure, so I'll fix that when I get a chance.

**Comment by alangpierce** [comment]
The CoffeeScript tests have now all been fixed (or disabled and documented as known correctness issues: https://github.com/decaffeinate/decaffeinate/blob/master/docs/correctness-issues.md ), so this task can be closed.

**Comment by eventualbuddha** [comment]
🎉🎉

**Comment by alangpierce** [comment]
@eventualbuddha FYI I just posted this to hacker news and it's getting some discussion: https://news.ycombinator.com/item?id=14583882
