### ISSUE TITLE
Fully convert codecombat example repo to JavaScript

### ISSUE THREAD

**Issue by alangpierce** [decaffeinate/decaffeinate#826]
This a tracking task for getting codecombat completely working as a decaffeinate example.

Repo: https://github.com/decaffeinate-examples/codecombat

There are some conversion failures, and I haven't looked into running the tests.

Open bugs affecting this repo:
https://github.com/decaffeinate/decaffeinate/issues/790

**Comment by madskonradsen** [comment]
Congrats on reaching 0 conversion failures on codecombat! That's pretty huge! :)

**Comment by alangpierce** [comment]
Thanks! 😄 

Unfortunately, getting codecombat's build system working with babel is turning out to be pretty challenging (they're on an old version of brunch that seems to be incompatible with any recent babel brunch plugin), but I'm sure there's a way to make it work.

**Comment by eventualbuddha** [comment]
We could help update their version of brunch? 😝

**Comment by alangpierce** [comment]
Yeah, I'm certainly considering it...

Another option is to write a custom brunch plugin that uses new babel with old brunch. And I'm sure there are other possible creative solutions.

**Comment by alangpierce** [comment]
All files convert and all tests pass, so I think it's safe to close this.
