### ISSUE TITLE
Crash on class this-assigned to a keyword name

### ISSUE THREAD

**Issue by alangpierce** [decaffeinate/decaffeinate#853]
decaffeinate is crashing on my CoffeeScript input:

```coffee
class @for
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=class%20%40for)

I get this error:

```
AddVariableDeclarationsStage failed to parse: Unexpected token, expected { (1:17)
> 1 | this.for = class for {};
    |                  ^
```

I think it's actually incorrect to try to put the name of the class on the RHS anyway, since in normal conditions it introduces a new variable name when it shouldn't.

**Comment by eventualbuddha** [comment]
> I think it's actually incorrect to try to put the name of the class on the RHS anyway, since in normal conditions it introduces a new variable name when it shouldn't.

This is half true. It introduces a binding inside the class body, if I remember correctly, similar to how a named function expression creates a binding inside its body but not outside.
