### ISSUE TITLE
Regression: class constructor name isn't specified in complex cases

### ISSUE THREAD

**Issue by alangpierce** [decaffeinate/decaffeinate#861]
decaffeinate is producing the wrong JavaScript based on my CoffeeScript input:

```coffee
A = {}
class A.B
console.log A.B.name
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=false&stage=full&code=A%20%3D%20%7B%7D%0Aclass%20A.B%0Aconsole.log%20A.B.name)

I get this output:

```js
const A = {};
A.B = class {};
console.log(A.B.name);
```

Here's what I expect it to be instead:

```js
const A = {};
A.B = class B {};
console.log(A.B.name);
```

In particular, the output should be `B`.

Follow-up from https://github.com/decaffeinate/decaffeinate/pull/854#issuecomment-281123212 . I got rid of some code here that I thought was unnecessary, but actually is needed. I'll also at least need some special logic to avoid keyword class names.

**Comment by eventualbuddha** [comment]
Here's what CoffeeScript does for the example above but with the name `for`:

```js
var A;

A = {};

A["for"] = (function() {
  function _for() {}

  return _for;

})();

console.log(A["for"].name);
```

So we could do something like this:

```js
const A = {};
A.for = class _for {};
console.log(A.for.name);
```
