### ISSUE TITLE
Repl is broken

### ISSUE THREAD

**Issue by alangpierce** [decaffeinate/decaffeinate#863]
I get a 404 in the JS console when loading http://decaffeinate-project.org/repl/  and the repl doesn't work. Looks like decaffeinate.js doesn't load. I'm pretty sure this happened when the repl was updated for decaffeinate 2.50.8. I'll try publishing a new version to see if that fixes things.

**Comment by menixator** [comment]
Just as I found this project :disappointed:

**Comment by alangpierce** [comment]
@eventualbuddha looks like publishing the website again didn't fix it, it now says v2.50.9 but still fails to load. Are there maybe any surge.sh logs you could look at? The [travis logs](https://travis-ci.org/decaffeinate/decaffeinate-project.org/builds/203813411) don't show anything out of the ordinary (some errors, but those have been happening for a long time, and at the end it says the publish worked).

My current best guesses are that it surge.sh has an outage or that we hit some quota or threshold. Maybe one workaround is to switch to GitHub pages? It used to be hosted on GitHub pages, so it shouldn't be that hard to switch to it, right?

**Comment by alangpierce** [comment]
In the meantime, I just pushed an update to the gh-pages branch for my fork, so here's a working mirror: http://www.alangpierce.com/decaffeinate-project.org/repl/ (the version number at the bottom wasn't updated, but the code is the latest decaffeinate version).

**Comment by alangpierce** [comment]
Looks like this is working again now after the most recently publish. It looked like the CDN wasn't serving it properly, so maybe re-publishing without a code change didn't fix it because the contents were the same. Every file was being served correctly except decaffeinate.js, and it had a different 404 page from the others, so looks to me like it was a hosting problem, but seems to be fixed now.
