### ISSUE TITLE
Crash on file with mixed indentation

### ISSUE THREAD

**Issue by alangpierce** [decaffeinate/decaffeinate#893]
decaffeinate is crashing on my CoffeeScript input:

```coffee
while a
  b

while c
	if d
		e
```

[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=while%20a%0A%20%20b%0A%0Awhile%20c%0A%09if%20d%0A%09%09e)

I get this error:

```
cannot unindent line by -1 without enough indent
  1 | while a
> 2 |   b
    |  ^
  3 | 
  4 | while c
```

From https://github.com/decaffeinate-examples/codecombat/blob/decaffeinate/scripts/minify.coffee

**Comment by eventualbuddha** [comment]
Think normalize should fix indents to be whatever is most common?

**Comment by alangpierce** [comment]
I thought about that, but I worry about doing whitespace changes in the normalize stage because of CoffeeScript's subtle parsing rules. Also, while this file probably isn't so bad (part of it has two-space indents, part of it has tabs, and one line has spaces and then a tab), I worry that getting it right in the fully general case would be really hard. Changing all tabs to spaces may not be so bad, but I think that wouldn't fix all issues and it seems like a file that's 99% tabs should stay 99% tabs if possible.

My current thought is to just get rid of this error and ignore the unindent operation (decaffeinate is hitting an error trying to unindent a line indented with spaces when the indent character for the file is a tab). Since the error is in the main stage, the non-ideal indentation will be in JS, so it won't cause correctness issues. Occasional ugly code seems fine since this error is so rare. Also, it seems like the kind of thing that can be later cleaned up automatically by `eslint --fix` or another formatter.
