### ISSUE TITLE
crash when converting single-argument function with parens on multiple lines

### ISSUE THREAD

**Issue by benbriggs** [decaffeinate/decaffeinate#937]
decaffeinate is crashing on my CoffeeScript input:

```coffee
(
  b
) ->
  c
```

[link to repl](http://decaffeinate-project.org/repl/#?evaluate=false&stage=full&code=(%0A%20%20b%0A)%20-%3E%0A%20%20c)

I get this error:

```
EsnextStage failed to parse: Error running plugin functions.arrow: Unexpected token (3:1)
```

thank you!

**Comment by alangpierce** [comment]
Thanks for reporting! Should be a pretty easy fix, I think (probably the arrow function conversion should keep the parameter list parens in that case). Hoping to get to it in the next few days.

**Comment by benbriggs** [comment]
👍  sounds great, thanks again!
