### ISSUE TITLE
Decaffeinate fails to convert file from first-mate

### ISSUE THREAD

**Issue by 50Wliu** [decaffeinate/decaffeinate#969]
decaffeinate is crashing on `grammar.coffee` from atom/first-mate: https://github.com/atom/first-mate/blob/e06b550732b30e7d50991c6cab87b238a7282eeb/src/grammar.coffee.  Unfortunately I'm new to decaffeinate so I can't provide much more than that.  Seems a bit related to #869, but grammar.coffee doesn't have any supers.

[REPL](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=path%20%3D%20require%20'path'%0D%0A%0D%0A_%20%3D%20require%20'underscore-plus'%0D%0Afs%20%3D%20require%20'fs-plus'%0D%0A%7BOnigRegExp%7D%20%3D%20require%20'oniguruma'%0D%0A%7BEmitter%7D%20%3D%20require%20'event-kit'%0D%0AGrim%20%3D%20require%20'grim'%0D%0A%0D%0AInjections%20%3D%20require%20'.%2Finjections'%0D%0APattern%20%3D%20require%20'.%2Fpattern'%0D%0ARule%20%3D%20require%20'.%2Frule'%0D%0AScopeSelector%20%3D%20require%20'.%2Fscope-selector'%0D%0A%0D%0A%23%20Extended%3A%20Grammar%20that%20tokenizes%20lines%20of%20text.%0D%0A%23%0D%0A%23%20This%20class%20should%20not%20be%20instantiated%20directly%20but%20instead%20obtained%20from%0D%0A%23%20a%20%7BGrammarRegistry%7D%20by%20calling%20%7BGrammarRegistry%3A%3AloadGrammar%7D.%0D%0Amodule.exports%20%3D%0D%0Aclass%20Grammar%0D%0A%20%20registration%3A%20null%0D%0A%0D%0A%20%20constructor%3A%20(%40registry%2C%20options%3D%7B%7D)%20-%3E%0D%0A%20%20%20%20%7B%40name%2C%20%40fileTypes%2C%20%40scopeName%2C%20%40foldingStopMarker%2C%20%40maxTokensPerLine%2C%20%40maxLineLength%7D%20%3D%20options%0D%0A%20%20%20%20%7Binjections%2C%20injectionSelector%2C%20patterns%2C%20repository%2C%20firstLineMatch%7D%20%3D%20options%0D%0A%0D%0A%20%20%20%20%40emitter%20%3D%20new%20Emitter%0D%0A%20%20%20%20%40repository%20%3D%20null%0D%0A%20%20%20%20%40initialRule%20%3D%20null%0D%0A%0D%0A%20%20%20%20%40rawPatterns%20%3D%20patterns%0D%0A%20%20%20%20%40rawRepository%20%3D%20repository%0D%0A%0D%0A%20%20%20%20if%20injectionSelector%3F%0D%0A%20%20%20%20%20%20%40injectionSelector%20%3D%20new%20ScopeSelector(injectionSelector)%0D%0A%20%20%20%20else%0D%0A%20%20%20%20%20%20%40injectionSelector%20%3D%20null%0D%0A%0D%0A%20%20%20%20if%20firstLineMatch%0D%0A%20%20%20%20%20%20%40firstLineRegex%20%3D%20new%20OnigRegExp(firstLineMatch)%0D%0A%20%20%20%20else%0D%0A%20%20%20%20%20%20%40firstLineRegex%20%3D%20null%0D%0A%0D%0A%20%20%20%20%40fileTypes%20%3F%3D%20%5B%5D%0D%0A%20%20%20%20%40includedGrammarScopes%20%3D%20%5B%5D%0D%0A%0D%0A%20%20%20%20%23%20Create%20last%20since%20Injections%20uses%20APIs%20from%20this%20class%0D%0A%20%20%20%20%40injections%20%3D%20new%20Injections(this%2C%20injections)%0D%0A%0D%0A%20%20%23%23%23%0D%0A%20%20Section%3A%20Event%20Subscription%0D%0A%20%20%23%23%23%0D%0A%0D%0A%20%20%23%20Public%3A%20Invoke%20the%20given%20callback%20when%20this%20grammar%20is%20updated%20due%20to%20a%0D%0A%20%20%23%20grammar%20it%20depends%20on%20being%20added%20or%20removed%20from%20the%20registry.%0D%0A%20%20%23%0D%0A%20%20%23%20*%20%60callback%60%20%7BFunction%7D%20to%20call%20when%20this%20grammar%20is%20updated.%0D%0A%20%20%23%0D%0A%20%20%23%20Returns%20a%20%7BDisposable%7D%20on%20which%20%60.dispose()%60%20can%20be%20called%20to%20unsubscribe.%0D%0A%20%20onDidUpdate%3A%20(callback)%20-%3E%0D%0A%20%20%20%20%40emitter.on%20'did-update'%2C%20callback%0D%0A%0D%0A%20%20%23%23%23%0D%0A%20%20Section%3A%20Tokenizing%0D%0A%20%20%23%23%23%0D%0A%0D%0A%20%20%23%20Public%3A%20Tokenize%20all%20lines%20in%20the%20given%20text.%0D%0A%20%20%23%0D%0A%20%20%23%20*%20%60text%60%20A%20%7BString%7D%20containing%20one%20or%20more%20lines.%0D%0A%20%20%23%0D%0A%20%20%23%20Returns%20an%20%7BArray%7D%20of%20token%20arrays%20for%20each%20line%20tokenized.%0D%0A%20%20tokenizeLines%3A%20(text)%20-%3E%0D%0A%20%20%20%20lines%20%3D%20text.split('%5Cn')%0D%0A%20%20%20%20ruleStack%20%3D%20null%0D%0A%0D%0A%20%20%20%20scopes%20%3D%20%5B%5D%0D%0A%20%20%20%20for%20line%2C%20lineNumber%20in%20lines%0D%0A%20%20%20%20%20%20%7Btags%2C%20ruleStack%7D%20%3D%20%40tokenizeLine(line%2C%20ruleStack%2C%20lineNumber%20is%200)%0D%0A%20%20%20%20%20%20%40registry.decodeTokens(line%2C%20tags%2C%20scopes)%0D%0A%0D%0A%20%20%23%20Public%3A%20Tokenize%20the%20line%20of%20text.%0D%0A%20%20%23%0D%0A%20%20%23%20*%20%60line%60%20A%20%7BString%7D%20of%20text%20to%20tokenize.%0D%0A%20%20%23%20*%20%60ruleStack%60%20An%20optional%20%7BArray%7D%20of%20rules%20previously%20returned%20from%20this%0D%0A%20%20%23%20%20%20method.%20This%20should%20be%20null%20when%20tokenizing%20the%20first%20line%20in%20the%20file.%0D%0A%20%20%23%20*%20%60firstLine%60%20A%20optional%20%7BBoolean%7D%20denoting%20whether%20this%20is%20the%20first%20line%0D%0A%20%20%23%20%20%20in%20the%20file%20which%20defaults%20to%20%60false%60.%20This%20should%20be%20%60true%60%0D%0A%20%20%23%20%20%20when%20tokenizing%20the%20first%20line%20in%20the%20file.%0D%0A%20%20%23%0D%0A%20%20%23%20Returns%20an%20%7BObject%7D%20containing%20the%20following%20properties%3A%0D%0A%20%20%23%20*%20%60line%60%20The%20%7BString%7D%20of%20text%20that%20was%20tokenized.%0D%0A%20%20%23%20*%20%60tags%60%20An%20%7BArray%7D%20of%20integer%20scope%20ids%20and%20strings.%20Positive%20ids%0D%0A%20%20%23%20%20%20indicate%20the%20beginning%20of%20a%20scope%2C%20and%20negative%20tags%20indicate%20the%20end.%0D%0A%20%20%23%20%20%20To%20resolve%20ids%20to%20scope%20names%2C%20call%20%7BGrammarRegistry%3A%3AscopeForId%7D%20with%20the%0D%0A%20%20%23%20%20%20absolute%20value%20of%20the%20id.%0D%0A%20%20%23%20*%20%60tokens%60%20This%20is%20a%20dynamic%20property.%20Invoking%20it%20will%20incur%20additional%0D%0A%20%20%23%20%20%20overhead%2C%20but%20will%20automatically%20translate%20the%20%60tags%60%20into%20token%20objects%0D%0A%20%20%23%20%20%20with%20%60value%60%20and%20%60scopes%60%20properties.%0D%0A%20%20%23%20*%20%60ruleStack%60%20An%20%7BArray%7D%20of%20rules%20representing%20the%20tokenized%20state%20at%20the%0D%0A%20%20%23%20%20%20end%20of%20the%20line.%20These%20should%20be%20passed%20back%20into%20this%20method%20when%0D%0A%20%20%23%20%20%20tokenizing%20the%20next%20line%20in%20the%20file.%0D%0A%20%20tokenizeLine%3A%20(inputLine%2C%20ruleStack%2C%20firstLine%3Dfalse%2C%20compatibilityMode%3Dtrue)%20-%3E%0D%0A%20%20%20%20tags%20%3D%20%5B%5D%0D%0A%0D%0A%20%20%20%20truncatedLine%20%3D%20false%0D%0A%20%20%20%20if%20inputLine.length%20%3E%20%40maxLineLength%0D%0A%20%20%20%20%20%20line%20%3D%20inputLine.slice(0%2C%20%40maxLineLength)%0D%0A%20%20%20%20%20%20truncatedLine%20%3D%20true%0D%0A%20%20%20%20else%0D%0A%20%20%20%20%20%20line%20%3D%20inputLine%0D%0A%0D%0A%20%20%20%20if%20ruleStack%3F%0D%0A%20%20%20%20%20%20ruleStack%20%3D%20ruleStack.slice()%0D%0A%20%20%20%20%20%20if%20compatibilityMode%0D%0A%20%20%20%20%20%20%20%20openScopeTags%20%3D%20%5B%5D%0D%0A%20%20%20%20%20%20%20%20for%20%7BscopeName%2C%20contentScopeName%7D%20in%20ruleStack%0D%0A%20%20%20%20%20%20%20%20%20%20openScopeTags.push(%40registry.startIdForScope(scopeName))%20if%20scopeName%0D%0A%20%20%20%20%20%20%20%20%20%20openScopeTags.push(%40registry.startIdForScope(contentScopeName))%20if%20contentScopeName%0D%0A%20%20%20%20else%0D%0A%20%20%20%20%20%20openScopeTags%20%3D%20%5B%5D%20if%20compatibilityMode%0D%0A%20%20%20%20%20%20initialRule%20%3D%20%40getInitialRule()%0D%0A%20%20%20%20%20%20%7BscopeName%2C%20contentScopeName%7D%20%3D%20initialRule%0D%0A%20%20%20%20%20%20ruleStack%20%3D%20%5B%7Brule%3A%20initialRule%2C%20scopeName%2C%20contentScopeName%7D%5D%0D%0A%20%20%20%20%20%20tags.push(%40startIdForScope(initialRule.scopeName))%20if%20scopeName%0D%0A%20%20%20%20%20%20tags.push(%40startIdForScope(initialRule.contentScopeName))%20if%20contentScopeName%0D%0A%0D%0A%20%20%20%20initialRuleStackLength%20%3D%20ruleStack.length%0D%0A%20%20%20%20position%20%3D%200%0D%0A%20%20%20%20tokenCount%20%3D%200%0D%0A%0D%0A%20%20%20%20loop%0D%0A%20%20%20%20%20%20previousRuleStackLength%20%3D%20ruleStack.length%0D%0A%20%20%20%20%20%20previousPosition%20%3D%20position%0D%0A%0D%0A%20%20%20%20%20%20break%20if%20position%20is%20line.length%20%2B%201%20%23%20include%20trailing%20newline%20position%0D%0A%0D%0A%20%20%20%20%20%20if%20tokenCount%20%3E%3D%20%40getMaxTokensPerLine()%20-%201%0D%0A%20%20%20%20%20%20%20%20truncatedLine%20%3D%20true%0D%0A%20%20%20%20%20%20%20%20break%0D%0A%0D%0A%20%20%20%20%20%20if%20match%20%3D%20_.last(ruleStack).rule.getNextTags(ruleStack%2C%20line%2C%20position%2C%20firstLine)%0D%0A%20%20%20%20%20%20%20%20%7BnextTags%2C%20tagsStart%2C%20tagsEnd%7D%20%3D%20match%0D%0A%0D%0A%20%20%20%20%20%20%20%20%23%20Unmatched%20text%20before%20next%20tags%0D%0A%20%20%20%20%20%20%20%20if%20position%20%3C%20tagsStart%0D%0A%20%20%20%20%20%20%20%20%20%20tags.push(tagsStart%20-%20position)%0D%0A%20%20%20%20%20%20%20%20%20%20tokenCount%2B%2B%0D%0A%0D%0A%20%20%20%20%20%20%20%20tags.push(nextTags...)%0D%0A%20%20%20%20%20%20%20%20tokenCount%2B%2B%20for%20tag%20in%20nextTags%20when%20tag%20%3E%3D%200%0D%0A%20%20%20%20%20%20%20%20position%20%3D%20tagsEnd%0D%0A%0D%0A%20%20%20%20%20%20else%0D%0A%20%20%20%20%20%20%20%20%23%20Push%20filler%20token%20for%20unmatched%20text%20at%20end%20of%20line%0D%0A%20%20%20%20%20%20%20%20if%20position%20%3C%20line.length%20or%20line.length%20is%200%0D%0A%20%20%20%20%20%20%20%20%20%20tags.push(line.length%20-%20position)%0D%0A%20%20%20%20%20%20%20%20break%0D%0A%0D%0A%20%20%20%20%20%20if%20position%20is%20previousPosition%0D%0A%20%20%20%20%20%20%20%20if%20ruleStack.length%20is%20previousRuleStackLength%0D%0A%20%20%20%20%20%20%20%20%20%20console.error(%22Popping%20rule%20because%20it%20loops%20at%20column%20%23%7Bposition%7D%20of%20line%20'%23%7Bline%7D'%22%2C%20_.clone(ruleStack))%0D%0A%20%20%20%20%20%20%20%20%20%20if%20ruleStack.length%20%3E%201%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7BscopeName%2C%20contentScopeName%7D%20%3D%20ruleStack.pop()%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20tags.push(%40endIdForScope(contentScopeName))%20if%20contentScopeName%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20tags.push(%40endIdForScope(scopeName))%20if%20scopeName%0D%0A%20%20%20%20%20%20%20%20%20%20else%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20if%20position%20%3C%20line.length%20or%20(line.length%20is%200%20and%20tags.length%20is%200)%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20tags.push(line.length%20-%20position)%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20break%0D%0A%20%20%20%20%20%20%20%20else%20if%20ruleStack.length%20%3E%20previousRuleStackLength%20%23%20Stack%20size%20increased%20with%20zero%20length%20match%0D%0A%20%20%20%20%20%20%20%20%20%20%5B%7Brule%3A%20penultimateRule%7D%2C%20%7Brule%3A%20lastRule%7D%5D%20%3D%20ruleStack%5B-2..%5D%0D%0A%0D%0A%20%20%20%20%20%20%20%20%20%20%23%20Same%20exact%20rule%20was%20pushed%20but%20position%20wasn't%20advanced%0D%0A%20%20%20%20%20%20%20%20%20%20if%20lastRule%3F%20and%20lastRule%20is%20penultimateRule%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20popStack%20%3D%20true%0D%0A%0D%0A%20%20%20%20%20%20%20%20%20%20%23%20Rule%20with%20same%20scope%20name%20as%20previous%20rule%20was%20pushed%20but%20position%20wasn't%20advanced%0D%0A%20%20%20%20%20%20%20%20%20%20if%20lastRule%3F.scopeName%3F%20and%20penultimateRule.scopeName%20is%20lastRule.scopeName%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20popStack%20%3D%20true%0D%0A%0D%0A%20%20%20%20%20%20%20%20%20%20if%20popStack%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20ruleStack.pop()%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20lastSymbol%20%3D%20_.last(tags)%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20if%20lastSymbol%20%3C%200%20and%20lastSymbol%20is%20%40startIdForScope(lastRule.scopeName)%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20tags.pop()%20%23%20also%20pop%20the%20duplicated%20start%20scope%20if%20it%20was%20pushed%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20tags.push(line.length%20-%20position)%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20break%0D%0A%0D%0A%20%20%20%20if%20truncatedLine%0D%0A%20%20%20%20%20%20tagCount%20%3D%20tags.length%0D%0A%20%20%20%20%20%20if%20tags%5BtagCount%20-%201%5D%20%3E%200%0D%0A%20%20%20%20%20%20%20%20tags%5BtagCount%20-%201%5D%20%2B%3D%20inputLine.length%20-%20position%0D%0A%20%20%20%20%20%20else%0D%0A%20%20%20%20%20%20%20%20tags.push(inputLine.length%20-%20position)%0D%0A%20%20%20%20%20%20while%20ruleStack.length%20%3E%20initialRuleStackLength%0D%0A%20%20%20%20%20%20%20%20%7BscopeName%2C%20contentScopeName%7D%20%3D%20ruleStack.pop()%0D%0A%20%20%20%20%20%20%20%20tags.push(%40endIdForScope(contentScopeName))%20if%20contentScopeName%0D%0A%20%20%20%20%20%20%20%20tags.push(%40endIdForScope(scopeName))%20if%20scopeName%0D%0A%0D%0A%20%20%20%20rule.clearAnchorPosition()%20for%20%7Brule%7D%20in%20ruleStack%0D%0A%0D%0A%20%20%20%20if%20compatibilityMode%0D%0A%20%20%20%20%20%20new%20TokenizeLineResult(inputLine%2C%20openScopeTags%2C%20tags%2C%20ruleStack%2C%20%40registry)%0D%0A%20%20%20%20else%0D%0A%20%20%20%20%20%20%7Bline%3A%20inputLine%2C%20tags%2C%20ruleStack%7D%0D%0A%0D%0A%20%20activate%3A%20-%3E%0D%0A%20%20%20%20%40registration%20%3D%20%40registry.addGrammar(this)%0D%0A%0D%0A%20%20deactivate%3A%20-%3E%0D%0A%20%20%20%20%40emitter%20%3D%20new%20Emitter%0D%0A%20%20%20%20%40registration%3F.dispose()%0D%0A%20%20%20%20%40registration%20%3D%20null%0D%0A%0D%0A%20%20clearRules%3A%20-%3E%0D%0A%20%20%20%20%40initialRule%20%3D%20null%0D%0A%20%20%20%20%40repository%20%3D%20null%0D%0A%0D%0A%20%20getInitialRule%3A%20-%3E%0D%0A%20%20%20%20%40initialRule%20%3F%3D%20%40createRule(%7B%40scopeName%2C%20patterns%3A%20%40rawPatterns%7D)%0D%0A%0D%0A%20%20getRepository%3A%20-%3E%0D%0A%20%20%20%20%40repository%20%3F%3D%20do%20%3D%3E%0D%0A%20%20%20%20%20%20repository%20%3D%20%7B%7D%0D%0A%20%20%20%20%20%20for%20name%2C%20data%20of%20%40rawRepository%0D%0A%20%20%20%20%20%20%20%20data%20%3D%20%7Bpatterns%3A%20%5Bdata%5D%2C%20tempName%3A%20name%7D%20if%20data.begin%3F%20or%20data.match%3F%0D%0A%20%20%20%20%20%20%20%20repository%5Bname%5D%20%3D%20%40createRule(data)%0D%0A%20%20%20%20%20%20repository%0D%0A%0D%0A%20%20addIncludedGrammarScope%3A%20(scope)%20-%3E%0D%0A%20%20%20%20%40includedGrammarScopes.push(scope)%20unless%20_.include(%40includedGrammarScopes%2C%20scope)%0D%0A%0D%0A%20%20grammarUpdated%3A%20(scopeName)%20-%3E%0D%0A%20%20%20%20return%20false%20unless%20_.include(%40includedGrammarScopes%2C%20scopeName)%0D%0A%20%20%20%20%40clearRules()%0D%0A%20%20%20%20%40registry.grammarUpdated(%40scopeName)%0D%0A%20%20%20%20%40emit%20'grammar-updated'%20if%20Grim.includeDeprecatedAPIs%0D%0A%20%20%20%20%40emitter.emit%20'did-update'%0D%0A%20%20%20%20true%0D%0A%0D%0A%20%20startIdForScope%3A%20(scope)%20-%3E%20%40registry.startIdForScope(scope)%0D%0A%0D%0A%20%20endIdForScope%3A%20(scope)%20-%3E%20%40registry.endIdForScope(scope)%0D%0A%0D%0A%20%20scopeForId%3A%20(id)%20-%3E%20%40registry.scopeForId(id)%0D%0A%0D%0A%20%20createRule%3A%20(options)%20-%3E%20new%20Rule(this%2C%20%40registry%2C%20options)%0D%0A%0D%0A%20%20createPattern%3A%20(options)%20-%3E%20new%20Pattern(this%2C%20%40registry%2C%20options)%0D%0A%0D%0A%20%20getMaxTokensPerLine%3A%20-%3E%0D%0A%20%20%20%20%40maxTokensPerLine%0D%0A%0D%0A%20%20scopesFromStack%3A%20(stack%2C%20rule%2C%20endPatternMatch)%20-%3E%0D%0A%20%20%20%20scopes%20%3D%20%5B%5D%0D%0A%20%20%20%20for%20%7BscopeName%2C%20contentScopeName%7D%20in%20stack%0D%0A%20%20%20%20%20%20scopes.push(scopeName)%20if%20scopeName%0D%0A%20%20%20%20%20%20scopes.push(contentScopeName)%20if%20contentScopeName%0D%0A%0D%0A%20%20%20%20%23%20Pop%20the%20last%20content%20name%20scope%20if%20the%20end%20pattern%20at%20the%20top%20of%20the%20stack%0D%0A%20%20%20%20%23%20was%20matched%20since%20only%20text%20between%20the%20begin%2Fend%20patterns%20should%20have%20the%0D%0A%20%20%20%20%23%20content%20name%20scope%0D%0A%20%20%20%20if%20endPatternMatch%20and%20rule%3F.contentScopeName%20and%20rule%20is%20stack%5Bstack.length%20-%201%5D%0D%0A%20%20%20%20%20%20scopes.pop()%0D%0A%0D%0A%20%20%20%20scopes%0D%0A%0D%0Aif%20Grim.includeDeprecatedAPIs%0D%0A%20%20EmitterMixin%20%3D%20require('emissary').Emitter%0D%0A%20%20EmitterMixin.includeInto(Grammar)%0D%0A%0D%0A%20%20Grammar%3A%3Aon%20%3D%20(eventName)%20-%3E%0D%0A%20%20%20%20if%20eventName%20is%20'did-update'%0D%0A%20%20%20%20%20%20Grim.deprecate(%22Call%20Grammar%3A%3AonDidUpdate%20instead%22)%0D%0A%20%20%20%20else%0D%0A%20%20%20%20%20%20Grim.deprecate(%22Call%20explicit%20event%20subscription%20methods%20instead%22)%0D%0A%0D%0A%20%20%20%20EmitterMixin%3A%3Aon.apply(this%2C%20arguments)%0D%0A%0D%0Aclass%20TokenizeLineResult%0D%0A%20%20constructor%3A%20(%40line%2C%20%40openScopeTags%2C%20%40tags%2C%20%40ruleStack%2C%20%40registry)%20-%3E%0D%0A%0D%0A%20%20Object.defineProperty%20%40prototype%2C%20'tokens'%2C%20get%3A%20-%3E%0D%0A%20%20%20%20%40registry.decodeTokens(%40line%2C%20%40tags%2C%20%40openScopeTags)%0D%0A)

I get this error:

```
grammar.coffee: EsnextStage failed to parse: Error running plugin modules.commonjs: Unexpected token, expected ; (320:4)
  318 |   Grammar.initClass();
  319 |   return Grammar;
> 320 | })());
      |     ^
  321 |
  322 | if (Grim.includeDeprecatedAPIs) {
```

**Comment by alangpierce** [comment]
Thanks for reporting! Here's a simplified test case:
```
module.exports = class A
  b: c
```
[(repl)](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=module.exports%20%3D%20class%20A%0D%0A%20%20b%3A%20c)

As a workaround you can pass `--keep-commonjs` to decaffeinate, which skips the conversion to `export` syntax.
