### ISSUE TITLE
Handle the jquery ready shortcut

### ISSUE THREAD

**Issue by jcoyne** [decaffeinate/decaffeinate#989]
decaffeinate is producing the wrong JavaScript based on my CoffeeScript input:

```coffee
$ - >
  ...
```

I get this output:

```js
$(function() { ... })
```

Here's what I expect it to be instead:

```js
$(document).ready(function() { ... })
```

**Comment by eventualbuddha** [comment]
Why do you expect it to expand it like that? Your output looks right to me.

**Comment by jcoyne** [comment]
@eventualbuddha Hmmm, I guess I didn't realize that `$()` was the same as `$(document).ready()`
