### ISSUE TITLE
Wrong code for existential operator in unless condition

### ISSUE THREAD

**Issue by gduarte** [decaffeinate/decaffeinate#995]
decaffeinate is producing the wrong JavaScript based on my CoffeeScript input:

```coffee
#!/usr/bin/env coffee
zed = { isDead: () -> true }

unless (zed?.isDead())
    console.log("zed is alive")
else
    console.log("zed is dead")
```

I get this output:

```js
#!/usr/bin/env node
const zed = { isDead() { return true; } };

if (!zed != null ? zed.isDead() : undefined) {
    console.log("zed is alive");
} else {
    console.log("zed is dead");
}
```

Zed is dead in CoffeeScript, but alive in JS. Looks like we must parenthesize either the entire negation in the `unless` or the check for `null`.

Thanks for this great project, it was a huge help.

**Comment by alangpierce** [comment]
Thanks for reporting! There have been a few bugs of this form in the past, so I imagine this won't be too hard to fix. Looks like decaffeinate sees the existing parentheses around `zed?.isDead()` and thinks that parens don't need to be added, but some other code path ends up removing them, so it ends up without parens.

I can probably get to it this weekend or earlier.
